### ISSUE TITLE
We should only have one version of loopdiagram.py

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#105]
At present we have <strike>three</strike> four very similar modules.

`eppy/loopdiagram.py`
`eppy/ex_loopdiagram.py`
`eppy/useful_scripts/loopdiagram.py`
`eppy/useful_scripts/loopdiagram1.py`

We should only have one of these, so that any changes/fixes only need to happen once.

**Comment by santoshphilip** [comment]
this is a clean up issue.
I'll start to look into it

**Comment by jamiebull1** [comment]
Resolved in #127
