### ISSUE TITLE
Add the capability to fetch a linked object directly from the linking object

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#106]
A suggestion from the [Slack channel](https://unmethours.slack.com/archives/eppy-dev):

>julien: is there a way to directly fetch an object linked? like for a electricloadcenter:distribution, I want to fetch the object from the "Inverter Name" field?

>jamie_bull: you'd like to be able to call `linked_object = myobject.Inverter_Name.something` and have it return the EpBunch that represents the inverter?
>jamie_bull: like `myobject.Inverter_Name.object` maybe?

To do this as it stands you need to know the `key` of the object being referred to:
`idf.getobject(key, myobject.Inverter_Name)`

I think this might be possible after the changes in #102. What we need to do is fetch the key from the `\ref` field in the IDD.

**Comment by jamiebull1** [comment]
Looking into this a bit further, the IDD doesn't actually specify the key of a referenced object. That makes sense since in some situations, more than one object type is a valid value.

In your example, @jmarrec, the IDD entry for the `Inverter Name` field is:

      A7,  \field Inverter Name
           \note required when Electrical Buss Type=DirectCurrentWithInverter, DirectCurrentWithInverterDCStorage,
           \note or DirectCurrentWithInverterACStorage
           \type object-list
           \object-list InverterList

Nothing there that specifies the object type that we need to use as the key.

**Comment by jmarrec** [comment]
You find the `\object-list ListName`, then you find every IDD object key where there is `\reference ListName`, and then you try getobject(key, name). You cannot have duplicate object names for these.

For my example, there are three objects where you find `\reference InverterList`: `ElectricLoadCenter:Inverter:Simple`, `ElectricLoadCenter:Inverter:FunctionOfPower` and `ElectricLoadCenter:Inverter:LookUpTable`

**Comment by santoshphilip** [comment]
@jmarrec can you describe a function that will do what you are asking.
Is this similar to saying
    
    zone.zonesurfaces
        returns a list of the surfaces in that zone

Am I understanding you question right ?
If that is the case, we may be close to having such a generic function.

**Comment by jmarrec** [comment]
If elcd is my electric load center distribution object

inverter = elcd.Inverter_Name.object

and it would return None if the field is blank, and the appropriate inverter object if it's not blank.

In pseudo code:
* If a field is an alpha and has \object-list attached, then it should have this method
* Find the possible "key" (type of object) from the idd with \reference matchibg thge \object-list
* try getobject(key, name) and return if found (and return None if not).


----

For the record Right now I monkey-patched the IDF class to do kinda the same thing but very crudely and very brutally.

def getobject_by_name(self, objname):
    found = None
    for key, obj_list in self.idfobjects.items():
        for obj in obj_list:
            if hasattr(obj, 'Name'):
                if obj.Name == objname:
                    found = obj
                    break
    return found

IDF.getobject_by_name = getobject_by_name

inverter = idf.getobject_by_name(elcd.Inverter_Name)

**Comment by jamiebull1** [comment]
I approached it slightly differently and have:

class EpBunch(Bunch):
    ...
    def get_referenced_object(self, fieldname):
        """Get an object referred to by a field in another object.
        """
        return get_referenced_object(self, fieldname)
    
def get_referenced_object(referring_object, fieldname):
    """Get an object referred to by a field in another object.
    """
    referenced_object_name = referring_object.__getattr__(fieldname)
    # find the key
    for key in referring_object.theidf.idfobjects.keys():
        obj = referring_object.theidf.getobject(key, referenced_object_name)
        if obj is not None:
            return obj

**Comment by jamiebull1** [comment]
I approached it slightly differently and have:

	class EpBunch(Bunch):
		...
		def get_referenced_object(self, fieldname):
			"""Get an object referred to by a field in another object.
			"""
			return get_referenced_object(self, fieldname)


	def get_referenced_object(referring_object, fieldname):
		"""Get an object referred to by a field in another object.
		"""
		referenced_object_name = referring_object.__getattr__(fieldname)
		# here we should find the correct key rather than looping over all keys
		for key in referring_object.theidf.idfobjects.keys():
			obj = referring_object.theidf.getobject(key, referenced_object_name)
			if obj is not None:
				return obj

So you can call something like:

    inverter = elcd.get_referenced_object('Inverter_Name')

**Comment by jmarrec** [comment]
works for me. I don't get the EpBunch stuff but I haven't looked at the source code at all so that's expected.

Thanks Jamie

**Comment by jamiebull1** [comment]
Ok, thanks to your explanation of the steps above, this should now work and avoid the potential bug with duplicate names.

```python
def get_referenced_object(referring_object, fieldname):
    """Get an object referred to by a field in another object.
    """
    referenced_object_name = referring_object.__getattr__(fieldname)
    object_list = [
        field['object-list'][0] for field in referring_object.objidd[1:]
        if field['field'][0].upper().replace(' ', '_') == fieldname.upper()]
    
    # get keys which have a reference to an object-list in object_list
    valid_keys = []
    for key in referring_object.theidf.idd_info:
        try:
            reference = key[1]['reference']
        except (IndexError, KeyError):
            continue
        if reference[0] in object_list:
            valid_keys.append(key[0]['idfobj'].upper())

    # loop over the valid keys until we find a referring object
    for key in valid_keys:
        try:
            obj = referring_object.theidf.getobject(key, referenced_object_name)
            if obj is not None:
                return obj
        except KeyError:
            continue
```

**Comment by jamiebull1** [comment]
`EpBunch` is the class that represents an EnergyPlus object. It seems a better place for this function than in the `IDF` class.

**Comment by santoshphilip** [comment]
@jamiebull1 @jmarrec I have a small function that does all of this. So don't do too much coding yet. I'll release this in a day or so.

**Comment by santoshphilip** [comment]
@jamiebull1 @jmarrec take a look at branch `i102_zonesurfaces`
look in `eppy/function_helpers`
see `function_helpers.zonesurfaces`
and `function_helpers.subsurfaces`

The tests for this are in `eppy/tests/test_idffunctions` (I'll be moving it out of here soon)

Note: The internal data structure was enhanced to make this work. Earlier `eppy` was unaware of groups in the idd file. I spent some changing the code so that `eppy` sucks the group information out of the idd file

I am still in the thick of doing this. So the code will look unorganized with bad documentation. 

I have called the core function `getreferingobjs` 

(I hope I am talking of the same thing you guys are talking of above :-)

**Comment by santoshphilip** [comment]
Ok ... `getreferingobjs` does not solve the problem you are addressing here.
It addresses the search going in the reverse direction.

@jamiebull1 's final code is the right way to go for this.

**Comment by jamiebull1** [comment]
Implemented in #108 Closing

**Comment by santoshphilip** [comment]
@jamiebull1 
I did an alternate implementation of `get_referenced_object`
called it `get_referenced_object_alter`
this is branch `i102_zonesurfaces_1`

I would like you to take a look at it because I have written a number of useful functions that I am using in it. I am taking every opportunity to write functions that are syntactic sugar for the underlying data structure.

You may find some of these functions useful when you are coding.

Which reminds me: We are writing a lot of code and none of this is getting into the user documentation :-(
Well .... one thing at a time.

**Comment by jamiebull1** [comment]
Yes, that's much better. I've got rid of the old version and documented your one.

**Comment by santoshphilip** [comment]
`i102_zonesurfaces_1` merged into `i102_zonesurfaces`
`i102_zonesurfaces ` will be later merged into `develop`

**Comment by santoshphilip** [comment]
Just a note:
On larger idf files, functions that deal with `object-list` and `reference` take time to search through the idd file
The idd file is effectively a large database without indexing.
I have some initial thoughts on indexing parts of it in a nonintrusive (maybe intuitive) manner

**Comment by jamiebull1** [comment]
Resolved in `i111_iddindex`
