### ISSUE TITLE
Returns floats for numeric fields

### ISSUE THREAD

**Issue by jmarrec** [santoshphilip/eppy#107]
Need to check the IDD field, if the code starts with N (N1, N2, etc), return a float instead of a string

**Comment by santoshphilip** [comment]
It should do this right now.
eppy looks at the idd file for type
(not at N1, N2)

Can you confirm that it is not working

**Comment by jmarrec** [comment]
In case it wasn't clear I meant look in idd and see if the field is listed as N something. Initially I thought looking at the \type (real) would do but a bunch don't have this \type attribute. The only sure way afaik is to look at the field ID (N for numeric, A for alpha)

Envoyé de mon iPhone

**Comment by santoshphilip** [comment]
I did not notice that some of them do not have type.
It would be good to have N and A as a backup

Should not be hard to do. 
Will take a stab at it

**Comment by santoshphilip** [comment]
@jmarrec Can you give a an example of this case, where the field does not have a type. (I am being a little lazy here :-)
Do you think
- this is a common occurrence
- or is it a case where the makers of the idd file forgot to put it in

**Comment by jamiebull1** [comment]
@santoshphilip I spotted some while working on simplesurface.py today. All of them that I checked are missing types.

**Comment by santoshphilip** [comment]
this has been fixed in  and closed in issue #188
