### ISSUE TITLE
Thermal properties of construction does not work (or fail gracefully) for all material types

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#110]
construction.ufactor works only if all the layers are `MATERIAL`
An airgap is a `MATERIAL:AIRGAP`

I took a look at this and it might take a bit of work to get it to work in all cases.
I suggest that we remove the function from EpBunch and add it later once it is resolved.
(This issue can be left open until it is done)

Dammit ! I was just starting to use this function in one of my projects

**Comment by jamiebull1** [comment]
I'll take a look at it today. I have a bit of time.

J

**Comment by jamiebull1** [comment]
@santoshphilip It's easy enough to do this just for `MATERIAL:AIRGAP` but I assume the difficulty you mention is that there are a lot of valid material types that can serve as layers in a `CONSTRUCTION`?

This would be helped if we had a function to get valid objects (everything which has `MaterialName` as a `reference`).

We could then loop through them looking for the necessary fields and either raising a warning or throwing an exception in the case that it's not possible to calculate the property.

For now, I've slightly reworked `rvalue` and `heatcapacity` and added `MATERIAL:AIRGAP` to the list of names that get the thermal properties functions added in `EpBunch` so you can keep on using it.

**Comment by santoshphilip** [comment]
Thanks for the quick fix.
I can use it now.

your point about the difficulty is correct. There are a lot of material types and may need different calculations for rvalue.

**Comment by santoshphilip** [comment]
works like a charm.
The output matches the value in the table report

Possible check in an integration test
- run the simulation 
- assert construction.ufactor == value from table report

**Comment by jamiebull1** [comment]
Good idea. I'll add that when I get back from London next week.

On the other object types in the `MaterialName` object-list I'm working on something that should cover them all. Any preference on what we should do if a user tries to do something like `construction.heatcapacity` on a construction with a `MATERIAL:NOMASS` layer? I think we should raise an exception for `nomass_material.heatcapacity`, but not sure if we should do the same for a construction, or whether we should just output a warning to stdout and return the heat capacity of the rest of the construction.

**Comment by jamiebull1** [comment]
@santoshphilip This is now working with all the non-window material types, and raises sensible warnings/errors where that seems necessary - particularly for `MATERIAL:ROOFVEGETATION` where the calculation assumed dry soil, and where `MATERIAL:NOMASS` layers are included in a construction.

It's also up to date with the `six` branch so can be merged into that rather than `develop`.

**Comment by santoshphilip** [comment]
`i98_thermal_properties` has been merged into `i87_six`
