### ISSUE TITLE
Functions dealing with object-list and reference are slow to search the IDD file

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#111]
Reproducing @santoshphilip 's comment on #106 
"On larger idf files, functions that deal with object-list and reference take time to search through the idd file
The idd file is effectively a large database without indexing.
I have some initial thoughts on indexing parts of it in a nonintrusive (maybe intuitive) manner."

**Comment by jamiebull1** [comment]
I'd also noticed that some of the tests are fairly slow and was planning on doing some profiling to see where the bottle-necks are.

A couple of initial thoughts

1. make a dictionary keyed by `reference` that returns a list of valid objects. This would happen when reading the IDD for the first time
2. See whether there are places we can use generators instead of lists

**Comment by santoshphilip** [comment]
I'll take a stab at coding something, just to get a feel of the problem

**Comment by jamiebull1** [comment]
I've been taking a look at this too. Without your new functions, this is what I came up with. I'm sure you can improve it and see where/when it should be used - presumably when the IDD is first read in?

```python
def test_object_lists():
    block, commlst, commdct = parse_idd.extractidddata(iddfhandle)
    theidd = eplusdata.Idd(block, 2)
    references = set()
    for item in commdct:
        try:
            if item[1].get('reference'):
                references |= set(item[1]['reference'])
        except IndexError:
            pass
        
    valid_objects = defaultdict(set)
    for reference, item in product(references, commdct):
        try:
            if item[1].get('reference')[0] == reference:
                objtype = item[0]['idfobj']
                valid_objects[reference] |= set([objtype])
        except (IndexError, TypeError) as e:
            pass
    expected = set([u'Material', u'Material:AirGap', u'Material:NoMass',
                    u'Material:InfraredTransparent', u'Material:RoofVegetation',
                    u'WindowMaterial:Shade', u'WindowMaterial:Screen',
                    u'WindowMaterial:Glazing:RefractionExtinctionMethod',
                    u'WindowMaterial:GlazingGroup:Thermochromic',
                    u'WindowMaterial:Gap', u'WindowMaterial:Blind',
                    u'WindowMaterial:Glazing', u'WindowMaterial:GasMixture',
                    u'WindowMaterial:SimpleGlazingSystem',
                     u'WindowMaterial:Gas'])
    assert valid_objects['MaterialName'] == expected
```

**Comment by santoshphilip** [comment]
made a branch `i111_iddindex` to work on this

**Comment by santoshphilip** [comment]
@jamiebull1 I have added to the data structure of the idd within eppy
This is happening in branch `i111_iddindex`
open an idf file and get a surface

    surf = idf.idfobjects['BuildingSurface:Detailed'.upper()][0]

get the idd of the field `Construction_Name`

    surf.getfieldidd('Construction_Name')

You get:

    {u'field': [u'Construction Name'],
     u'note': [u'To be matched with a construction in this input file'],
     u'object-list': [u'ConstructionNames'],
     u'pointsto': {u'CONSTRUCTION',
      u'CONSTRUCTION:CFACTORUNDERGROUNDWALL',
      u'CONSTRUCTION:COMPLEXFENESTRATIONSTATE',
      u'CONSTRUCTION:FFACTORGROUNDFLOOR',
      u'CONSTRUCTION:INTERNALSOURCE',
      u'CONSTRUCTION:WINDOWDATAFILE'},
     u'required-field': [u''],
     u'type': [u'object-list']}


Note the new key `pointsto`. (it points to a set) 
I have added this for all fields that have the key `object-list`
With this data structure you don't have to search through the entire idf to find what `u'object-list': [u'ConstructionNames']` is referring to.

Let me know if this makes sense. 
I can merge this into branch `develop` after your comments.
(should I use `pointsto` or `refersto` ?)

also take a look at `idf.idd_index` 
The `pointsto` is using the set from `idf.idd_index['ref2names']`

**Comment by jamiebull1** [comment]
This makes sense to me, yes. I've opened a pull request #114 for comments on your code, though I don't have much to add as it's not an area of the code I'm familiar with.

I'd prefer `validobjects` to either `pointsto` or `refersto` as it makes it clearer what is in the set and that it's related to `object-list` but I'm not wedded to it.

**Comment by santoshphilip** [comment]
Made some updates based on your comments
tests pass
Will merge it into branch `develop`

**Comment by santoshphilip** [comment]
changed `pointsto` to `validobjects`
does seem more meaningful
