### ISSUE TITLE
tab completion in ipython for idf object fields

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#113]
Right now if we have idf object like a zone, we can access it's fields by 

```
zone.Name
zone.Construction_Name
```

In `ipython`, `ipython notebook` or `jupyter notebook`, you would expect to be able type

```
zone.N->  hit the tab key
zone.Con-> hit the tab key
```

and the rest of the field name is filled in (in ipython)
or you get a list of fields in a dropbox that that you can select (in notebook)

This does not happen.

How to fix it:
- ipython only autocompletes strings that are returned by `zone.__dir__()`
- override `__dir__` so that it returns all the fields

**Comment by santoshphilip** [comment]
This has been coded in branch `i113_tabcompletion`. pretty simple

    def __dir__(self):
        fnames = self.fieldnames
        func_names = self['__functions'].keys()
        return super(EpBunch, self).__dir__() + fnames + func_names

test are all passing. 
The tab completion works in `ipython` and `python notebook`

merging this into branch `develop`

**Comment by santoshphilip** [comment]
Looks good .. I am closing this

**Comment by Wbec** [comment]
It appears that `__dir__` for is broken for EpBunch objects in python 3.
```python
meter = idf.idfobjects['OUTPUT:METER'][0]
dir(meter)
```
The above will raise a type error:
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-14-007803909ad6> in <module>()
----> 1 dir(idf.idfobjects['OUTPUT:METER'][0])

~/.local/lib/python3.6/site-packages/eppy/bunch_subclass.py in __dir__(self)
    375         fnames = self.fieldnames
    376         func_names = self['__functions'].keys()
--> 377         return super(EpBunch, self).__dir__() + fnames + func_names
    378 
    379 

TypeError: can only concatenate list (not "dict_keys") to list.
```
It looks like this is caused by `dict.keys()` returning a view instead of a list in python 3. Changing the line to `func_names = list(self['__functions'].keys())` should fix it.

**Comment by samuelduchesne** [comment]
I just found out about this quick fix by @Wbec. It is definitely annoying that whenever I open an EpBunch in the variables viewer of PyCharm (while debugging), I get a `TypeError: can only concatenate list (not "dict_keys") to list`.

Does changing from a `dict_key` to a `list` break Python2?

**Comment by jamiebull1** [comment]
>Does changing from a dict_key to a list break Python2?

Why not try it? If you open a pull request, the CI will run the tests against py 2.7.

**Comment by santoshphilip** [comment]
@samuelduchesne pull request has been merged
