### ISSUE TITLE
Installation is broken on Python 3.5 - at least Windows

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#119]
This is pretty serious - we should prioritise fixing this before anything else as I imagine we're losing users over it. I've already had to direct people to install the `i87_six` branch as I know that's working cross-platform.

Steps to reproduce:

    conda create -n test_eppy3_install python=3.5 -y
    activate test_eppy3_install
    pip install eppy
    python
    from eppy.EPlusInterfaceFunctions import readidf
	
This is the full output on my machine:

	C:\Users\Jamie\git\test_installs>conda create -n test_eppy3_install python=3.5
	Fetching package metadata: ....
	Solving package specifications: ..........
	Package plan for installation in environment C:\Users\Jamie\Miniconda2\envs\test_eppy3_install:

	The following NEW packages will be INSTALLED:

		pip:            8.1.2-py35_0
		python:         3.5.2-0
		setuptools:     25.1.6-py35_0
		vs2015_runtime: 14.0.25123-0
		wheel:          0.29.0-py35_0

	Proceed ([y]/n)? y

	Linking packages ...
	[      COMPLETE      ]|##################################################| 100%
	#
	# To activate this environment, use:
	# > activate test_eppy3_install
	#

	C:\Users\Jamie\git\test_installs>activate test_eppy3_install
	Activating environment "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install"...

	[test_eppy3_install] C:\Users\Jamie\git\test_installs>pip install eppy
	Collecting eppy
	Collecting munch>=2.0.2 (from eppy)
	Collecting pyparsing>=pyparsing (from eppy)
	  Using cached pyparsing-2.1.8-py2.py3-none-any.whl
	Collecting pytest>=2.3.5 (from eppy)
	  Downloading pytest-3.0.1-py2.py3-none-any.whl (169kB)
		100% |################################| 174kB 839kB/s
	Collecting beautifulsoup4>=4.2.1 (from eppy)
	  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
	Collecting pydot>1.0 (from eppy)
	Collecting py>=1.4.29 (from pytest>=2.3.5->eppy)
	  Using cached py-1.4.31-py2.py3-none-any.whl
	Collecting colorama; sys_platform == "win32" (from pytest>=2.3.5->eppy)
	  Using cached colorama-0.3.7-py2.py3-none-any.whl
	Installing collected packages: munch, pyparsing, py, colorama, pytest, beautifulsoup4, pydot, eppy
	Successfully installed beautifulsoup4-4.5.1 colorama-0.3.7 eppy-0.5.2 munch-2.0.4 py-1.4.31 pydot-1.2.2 pyparsing-2.1.8 pytest-3.0.1

	[test_eppy3_install] C:\Users\Jamie\git\test_installs>python
	Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
	Type "help", "copyright", "credits" or "license" for more information.
	>>> from eppy import modeleditor
	Traceback (most recent call last):
	  File "<stdin>", line 1, in <module>
	  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\modeleditor.py", line 19, in <module>
		from eppy.idfreader import idfreader1
	  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\idfreader.py", line 15, in <module>
		from eppy.EPlusInterfaceFunctions import readidf
	  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\EPlusInterfaceFunctions\readidf.py", line 17, in <module>
		import eppy.EPlusInterfaceFunctions.parse_idd as parse_idd
	  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\EPlusInterfaceFunctions\parse_idd.py", line 19, in <module>
		import eppy.EPlusInterfaceFunctions.mylib2 as mylib2
	  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\EPlusInterfaceFunctions\mylib2.py", line 16, in <module>
		import os, pickle, cPickle
	ImportError: No module named 'cPickle'
	>>>

**Comment by santoshphilip** [comment]
I am at a location with poor internet connection. So my response is going to be slow for a day or so.


I looked at the code.
`cPickle` is used by functions `cpickleload` and `cpickledump` in `mylib2`
eppy does not call these functions at all.

We should be fine just removing that `import cPickle`  and the two functions. 
Can you test to see if this fixes the problem.

Once I get back I'll do a bug fix release.

**Comment by jamiebull1** [comment]
@santoshphilip I'm still having problems installing Eppy for Python 3 with `pip`.

```
____________________ ERROR collecting tests/test_builder.py ____________________

ImportError while importing test module '/home/travis/build/jamiebull1/geomeppy/tests/test_builder.py'.

Original error message:

'No module named 'StringIO''

Make sure your test modules/packages have valid Python names.
```

It looks like `pip install eppy` is installing the Python 2 code into a Python 3 environment, judging by the warnings produced during installation.

```
Installed /home/travis/miniconda/envs/geomeppy/lib/python3.5/site-packages/pyclipper-1.0.5-py3.5-linux-x86_64.egg

Searching for eppy==0.5.3

Reading https://pypi.python.org/simple/eppy/

Downloading https://pypi.python.org/packages/dd/a7/775c581e87ad05950c7128e4774a1061d5d9dba0c2e242ad58118fd46ace/eppy-0.5.3.tar.gz#md5=b64b65b740177d1cdea97f1ca0276690

Best match: eppy 0.5.3

Processing eppy-0.5.3.tar.gz

Writing /tmp/easy_install-suuztzjs/eppy-0.5.3/setup.cfg

Running eppy-0.5.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-suuztzjs/eppy-0.5.3/egg-dist-tmp-9zmmn3di

  File "build/bdist.linux-x86_64/egg/eppy/Main_Tutorial.py", line 132

    print idf1.idfobjects['BUILDING']  # put the name of the object you'd like to look at in brackets

             ^

SyntaxError: Missing parentheses in call to 'print'

  File "build/bdist.linux-x86_64/egg/eppy/idf_msequence.py", line 28

    raise TypeError, val

                   ^

SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/eppy/ex_loopdiagram.py", line 74

    except ValueError, e:

                     ^

SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/eppy/loopdiagram.py", line 71

    except ValueError, err:

                     ^

SyntaxError: invalid syntax

  File "build/bdist.linux-x86_64/egg/eppy/loops.py", line 37

    except KeyError, err:

                   ^

SyntaxError: invalid syntax
```

**Comment by jamiebull1** [comment]
Here's the steps to reproduce the error (the same steps as previously):

```
C:\Users\Jamie\git\test>conda create -n test_eppy3_install python=3.5 -y
Fetching package metadata: ....
Solving package specifications: ..........
Package plan for installation in environment C:\Users\Jamie\Miniconda2\envs\test_eppy3_install:

The following NEW packages will be INSTALLED:

    pip:            8.1.2-py35_0
    python:         3.5.2-0
    setuptools:     26.1.1-py35_0
    vs2015_runtime: 14.0.25123-0
    wheel:          0.29.0-py35_0

Linking packages ...
[      COMPLETE      ]|##################################################| 100%
#
# To activate this environment, use:
# > activate test_eppy3_install
#

C:\Users\Jamie\git\test>activate test_eppy3_install
Activating environment "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install"...

[test_eppy3_install] C:\Users\Jamie\git\test>pip install eppy
Collecting eppy
  Downloading eppy-0.5.31.tar.gz (814kB)
    100% |################################| 819kB 492kB/s
Collecting munch>=2.0.2 (from eppy)
Collecting beautifulsoup4>=4.2.1 (from eppy)
  Using cached beautifulsoup4-4.5.1-py3-none-any.whl
Collecting pyparsing>=pyparsing (from eppy)
  Using cached pyparsing-2.1.8-py2.py3-none-any.whl
Collecting tinynumpy (from eppy)
Collecting decorator (from eppy)
  Using cached decorator-4.0.10-py2.py3-none-any.whl
Collecting pydot>1.0 (from eppy)
Collecting pytest>=2.3.5 (from eppy)
  Using cached pytest-3.0.2-py2.py3-none-any.whl
Collecting colorama; sys_platform == "win32" (from pytest>=2.3.5->eppy)
  Using cached colorama-0.3.7-py2.py3-none-any.whl
Collecting py>=1.4.29 (from pytest>=2.3.5->eppy)
  Using cached py-1.4.31-py2.py3-none-any.whl
Building wheels for collected packages: eppy
  Running setup.py bdist_wheel for eppy ... done
  Stored in directory: C:\Users\Jamie\AppData\Local\pip\Cache\wheels\f9\fc\c6\5bc614867910fcc9ec51986a7bb34c7bb3321e66c5cd3a6c70
Successfully built eppy
Installing collected packages: munch, beautifulsoup4, pyparsing, tinynumpy, decorator, pydot, colorama, py, pytest, eppy
Successfully installed beautifulsoup4-4.5.1 colorama-0.3.7 decorator-4.0.10 eppy-0.5.31 munch-2.0.4 py-1.4.31 pydot-1.2.2 pyparsing-2.1.8 pytest-3.0.2 tinynumpy-1.2.1

[test_eppy3_install] C:\Users\Jamie\git\test>python
Python 3.5.2 |Continuum Analytics, Inc.| (default, Jul  5 2016, 11:41:13) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from eppy.EPlusInterfaceFunctions import readidf
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\EPlusInterfaceFunctions\readidf.py", line 17, in <module>
    import eppy.EPlusInterfaceFunctions.parse_idd as parse_idd
  File "C:\Users\Jamie\Miniconda2\envs\test_eppy3_install\lib\site-packages\eppy\EPlusInterfaceFunctions\parse_idd.py", line 18, in <module>
    from StringIO import StringIO
ImportError: No module named 'StringIO'
>>>
```

**Comment by santoshphilip** [comment]
@jamiebull1 , I don't think `pip install eppy` ever worked for python3.
`pip install eppy` comes from the http://pypi.python.org which has a copy of the `master` branch

Only when we merge your work with `six` into `master` branch and release into pypi will the pip install work for python3

(I hope I am understanding the situation correctly)

Is this mission critical for you ?
I can do a merge for your `six` branch into `develop` and then `master` and do a release on pypi

**Comment by jamiebull1** [comment]
It's not totally critical for me. I can work around it by using the `six`
branch. It's not ideal for other people at UCL I'm hoping can use the
`geomeppy` package though. It would be great to get `pip install` working
properly. Do you need anything from me to get comfortable with what's
happening with `six`?

**Comment by santoshphilip** [comment]
ha!
If you reconfirm your confidence level in branch `i87_six`, I'll go with it and take steps to release on pypi
(I assume it is branch `i87_six`)

I spent enough time to be familiar with what you were doing in `i87_six`. That is good enough for me. Beyond that ... the tests are passing and in principle, the is what we should depend on.
I'll also test the install process before release.

So, awaiting your confirmation.

**Comment by jamiebull1** [comment]
Yep, I'm happy with it. Medium term, it would be good to get the
`improve_coverage` work merged in, but the `i87_six` branch is a much
lighter touch. I'm using it as my main branch, and have other people who
are on python 3 using it as their regular branch too.

**Comment by santoshphilip** [comment]
OK.  will release over the next day or so.
