### ISSUE TITLE
Python 3.5 error in ex_loopdiagram.py

### ISSUE THREAD

**Issue by kostovmike** [santoshphilip/eppy#126]
File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py", line 553, in getedges
    data, commdct = readidf.readdatacommdct(fname, iddfile=iddfile)

ValueError: too many values to unpack (expected 2)

**Comment by jamiebull1** [comment]
@kostovmike @santoshphilip I know what this is. I'm away from my laptop for a couple of hours now so if you want to pick it up, Santosh, go ahead. Otherwise I'll raise a PR to fix later on today.

**Comment by santoshphilip** [comment]
I may not be able to get to this today.

**Comment by kostovmike** [comment]
Thank you both for the prompt response and compliments for the amazing work on eppy.

**Comment by jamiebull1** [comment]
@santoshphilip I've taken this as a cue to pull in the changes from `improve_coverage` which remove the various versions of `loopdiagram.py`, leaving just the one in `useful_scripts`, a well as adding both unit and integration testing for it.

If that's not the way you want to go, the simple fix is just to change both line 553 and 584 from:
```data, commdct = readidf.readdatacommdct(fname, iddfile=iddfile)```
to:
```data, commdct, idd_index = readidf.readdatacommdct(fname, iddfile=iddfile)```

@kostovmike Until this bugfix/cleanup gets accepted, you can install the working version with `pip install https://github.com/santoshphilip/eppy/archive/i126_loopdiagram.zip`. Then you will have the same function as you were using in `eppy/ex_loopdiagram.py` but you'll need to call it from `eppy/useful_scripts/loopdiagram.py`.

**Comment by kostovmike** [comment]
@jamiebull1 Problem solved!

**Comment by santoshphilip** [comment]
I have released this on pipit as version 0.5.41
So you can do a `pip install`
