### ISSUE TITLE
Python 3.5 Error in creating .dot diagram

### ISSUE THREAD

**Issue by kostovmike** [santoshphilip/eppy#128]
Haven't installed 0.5.41 yet so the issue might be already resolved, however worth mentioning the above error when trying to create .dot diagram in 0.5.40 for viewing in graphviz
The error appeard before and after manually updating lines 553 and 584 to data, commdct, idd_index = readidf.readdatacommdct(fname, iddfile=iddfile)

kostovmike$ python /Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py /Users/kostovmike/Desktop/MY-PYTHON/eppy/myidf.idf
readingfile
constructing the loops
making the diagram
Traceback (most recent call last):
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py", line 602, in <module>
    sys.exit(main())
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py", line 590, in main
    g = makediagram(edges)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py", line 191, in makediagram
    nodes = edges2nodes(edges)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/ex_loopdiagram.py", line 175, in edges2nodes
    justnodes.sort()
TypeError: unorderable types: str() < tuple()

kostovmike$

**Comment by jamiebull1** [comment]
@kostovmike Let me know if upgrading to `0.5.41` doesn't work.

I'm not going to be in much of a hurry to fix a bug in a module that's already been removed from `eppy`, but if there's still a problem in `0.5.41` I'll get right on it.

**Comment by jamiebull1** [comment]
@kostovmike Was this resolved when you upgraded to `0.5.41` or do we still need this issue open?

**Comment by kostovmike** [comment]
Sadly not, I believe this somehow relates to the old issue with edges in loopdiagram.py

**Comment by jamiebull1** [comment]
Ok, let's have a look then.

Can you try replacing the `get_edges` function with this:

	def edges2nodes(edges):
		"""Gather the unique nodes from the edges and return as a sorted list.
		"""
		nodes = itertools.chain(*edges)
		unique_nodes = list(set(nodes))

		return sorted(unique_nodes)

And if that doesn't work, can you provide a simple example idf that reproduces your bug?

**Comment by kostovmike** [comment]
Great! Just to double check that I understand correctly..
In useful_scripts/loopdiagram.py line 122 has already defined function 'edges2nodes'
In the same file, I can see the problematic 'getedges' function, line 492.
Do I need to replace 'getedges' line 492 with your code?

**Comment by jamiebull1** [comment]
No, you just need to replace `edges2nodes` and `import itertools`.

**Comment by kostovmike** [comment]
I've got it!

**Comment by kostovmike** [comment]
After I've run loopdiagram in terminal:
kostovmike$ python /Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py /Users/kostovmike/Desktop/MY-PYTHON/eppy/myidf.idf
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 551, in <module>
    sys.exit(main())
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 542, in main
    required=True)
  File "/Users/kostovmike/anaconda/lib/python3.5/argparse.py", line 1312, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "/Users/kostovmike/anaconda/lib/python3.5/argparse.py", line 1424, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals

**Comment by jamiebull1** [comment]
I knew there would be a bug in there if I didn't unit test it. Note to self: it's not finished if it doesn't have 100% coverage!

You should be able to just remove the `required=True` arguments from the two `parser.add_argument` lines. Let me know if that works.

**Comment by kostovmike** [comment]
after removing the last argument 'required=True' and re-run:
kostovmike$ python /Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py /Users/kostovmike/Desktop/MY-PYTHON/eppy/PlantApplicationsGuide_Example2.idf
Couldn't import dot_parser, loading of dot files will not be possible.
usage: loopdiagram.py [-h] idd file
loopdiagram.py: error: the following arguments are required: file

**Comment by kostovmike** [comment]
after removing required=True from the two parser.add_argument lines now looks like this:
    parser.add_argument('idd', type=str, action='store', 
        help='location of idd file = ./somewhere/eplusv8-0-1.idd')
    parser.add_argument('file', type=str, action='store', 
        help='location of idf file = ./somewhere/f1.idf')

**Comment by jamiebull1** [comment]
Ok, I've managed to get it to give me the same error as your original one now. Progress of a sort.

The argparse lines should read:

    parser.add_argument('file', nargs='?', type=str, action='store', 
        help='location of idf file = ./somewhere/f1.idf')
    parser.add_argument('idd', nargs='?', type=str, action='store', 
        help='location of idd file = ./somewhere/eplusv8-0-1.idd')

**Comment by jamiebull1** [comment]
If you revert `edges_to_nodes` to:

	def edges2nodes(edges):
		"""gather the nodes from the edges"""
		nodes = []
		for e1, e2 in edges:
			nodes.append(e1)
			nodes.append(e2)
		nodedict = dict([(n, None) for n in nodes])
		justnodes = list(nodedict.keys())
		# justnodes.sort()
		justnodes = sorted(justnodes, key=lambda x: str(x[0]))
		return justnodes
		
Does that fix it?

**Comment by kostovmike** [comment]
I have a feeling we are almost there:
kostovmike$ python /Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py /Users/kostovmike/Desktop/MY-PYTHON/eppy/PlantApplicationsGuide_Example2.idf
Couldn't import dot_parser, loading of dot files will not be possible.
Traceback (most recent call last):
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/EPlusInterfaceFunctions/parse_idd.py", line 84, in _readfname
    if isinstance(fname, (file, StringIO)):
NameError: name 'file' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 553, in <module>
    sys.exit(main())
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 549, in main
    make_and_save_diagram(args.file, args.idd)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 515, in make_and_save_diagram
    g = process_idf(fname, iddfile)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py", line 520, in process_idf
    data, commdct, _iddindex = readidf.readdatacommdct(fname, iddfile=iddfile)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/EPlusInterfaceFunctions/readidf.py", line 75, in readdatacommdct
    block, commlst, commdct, idd_index = parse_idd.extractidddata(iddfile)
  File "<decorator-gen-4>", line 2, in extractidddata
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/EPlusInterfaceFunctions/parse_idd.py", line 98, in make_idd_index
    astr = _readfname(fname)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/EPlusInterfaceFunctions/parse_idd.py", line 92, in _readfname
    astr = mylib2.readfile(fname)
  File "/Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/EPlusInterfaceFunctions/mylib2.py", line 24, in readfile
    fhandle = open(filename, 'rb')
TypeError: invalid file: None

**Comment by jamiebull1** [comment]
We may be close, but I'm afraid I have to leave this hanging for now as I have to go out. I'll have another look when I get a chance, probably tomorrow now.

**Comment by kostovmike** [comment]
Thanks!

**Comment by jamiebull1** [comment]
Just to check, what's the terminal command you're calling? The error looks
like either you're not passing an IDD file, or its not getting picked up by
argparse.

**Comment by kostovmike** [comment]
In loopdiagram.py .. Do I need to change manually the location of the .idd file that I use?
This is under parser.add_argument ...?

**Comment by jamiebull1** [comment]
No, when you call from the command line it should just call `python
loopdiagram.py <the idf> <the idd>`

**Comment by jamiebull1** [comment]
The one in `parser.add_argument` is just an example for the heldocumentation if you call `python loop diagram.py -h`

**Comment by kostovmike** [comment]
I didn't know I need to call the idd :)
Give me a sec

**Comment by kostovmike** [comment]
@jamiebull1  It worked! 👍 
.dot and .png are now generated...
there is still this error "Couldn't import dot_parser, loading of dot files will not be possible." but that's pretty much everything, I can now move on - thank you so much!

kostovmike$ python /Users/kostovmike/anaconda/lib/python3.5/site-packages/eppy/useful_scripts/loopdiagram.py /Users/kostovmike/Desktop/MY-PYTHON/myeppy/PlantApplicationsGuide_Example2.idf /Users/kostovmike/Desktop/MY-PYTHON/myeppy/Energy+.idd
Couldn't import dot_parser, loading of dot files will not be possible.
constructing the loops
cleaning edges
making the diagram
saved file: /Users/kostovmike/Desktop/MY-PYTHON/myeppy/PlantApplicationsGuide_Example2.dot
saved file: /Users/kostovmike/Desktop/MY-PYTHON/myeppy/PlantApplicationsGuide_Example2.png

**Comment by jamiebull1** [comment]
That isn't a problem. We don't use the dot_parser at any point. Glad we got
that fixed - and in the process found the bug in the argparser arguments.

@santoshphilip, when I get home I'll raise a PR which fixes the argparser.

**Comment by jamiebull1** [comment]
Updated PR #130 with fixes
