### ISSUE TITLE
Eppy fails to read EnergyPlus 8.5 IDD

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#135]
Reported on UnmetHours [here](https://unmethours.com/question/20186/eppy-with-energyplus-85-and-charmap-codec-error/).

The error they're seeing is:

    UnicodeEncodeError: 'charmap' codec can't encode characters in position 26-27: character maps to <undefined>

Edited to remove a note about a similar error on my machine - I'd accidentally changed the encoding on the IDD file, fixed by reinstalling. That's what I've suggested on the UnmetHours question, and so hopefully this issue won't be needed.

**Comment by santoshphilip** [comment]
I am tied up with another project right now.

Does this need a long term fix ?
(I see that we have a fix for the moment)

**Comment by santoshphilip** [comment]
OK ... Let us wait and see if the problem resolves itself for Justin.

**Comment by jamiebull1** [comment]
I'm not sure. I saw the same error when I tried to create an `iddv850.py` for use by `iddcurrent.py` and didn't get to the bottom of it, so there's possibly something underlying worth looking into.

But yes, we at least need to see if Justin's problem is resolved by reinstalling.

**Comment by jamiebull1** [comment]
Closing as invalid. Turns out the problem was caused by accidentally trying to read a non-IDF file - [see comment](https://unmethours.com/question/20186/eppy-with-energyplus-85-and-charmap-codec-error/?comment=20250).

**Comment by santoshphilip** [comment]
I wanted to post a few issues that came up in my mind when this issue was open.
See following two posts:

**Comment by santoshphilip** [comment]
### Skipping some objects

When the idd parser was written, there were a couple of IDD objects that I could not parse (I suspect the IDD was malformed). My solution was to skip those objects. As long as the IDF did not use those objects, all would be fine.

This needs to be revisited. The newer version of E+ have less (maybe none) IDD objects that need to be skipped. I have not checked for some time. 

At the same time the skipping should be retained to maintained the ability to read older versions of E+

**Comment by santoshphilip** [comment]
### Will eppy break with new versions of E+ ?

eppy is dependent on reading and parsing IDD file. As long as the IDD file is read correctly, it should largely work in terms of reading the objects and fields and editing them.

One way to test this is to 
- read the idf file with eppy and write it back to disk (without comments)
- now read the idf file with a simple python script and write it disk without comments (use a identical format to eppy output)
- if the two files match, the test passes
- Do this for all the example files in E+
- If all of them pass, we are good.

this script has been written , but not documented.
When I ran the script (takes a while to run), it failed on a couple of example files.

I have not run the script recently.
We should set up a process where this script is run every time a new version of E+ is released.
Ideally it should be someone who is not coding eppy.

**Comment by jamiebull1** [comment]
On the second one, that sounds like a relatively easy thing to tack onto the CI as a separate build. Version 8.6 came out three days ago so it's probably a good time to do that. I'll take a look at your script and see how we can run it on Travis,

**Comment by santoshphilip** [comment]
The script is at:
- `eppy/useful_scripts/eppyreadtest_file.py`
- `eppy/useful_scripts/eppyreadtest_folder.py`

i had not yet documented it, although I did leave a placeholder at 
http://pythonhosted.org/eppy/useful_scripts.html#eppyreadtest-folder-py

The code documentation seems OK.
