### ISSUE TITLE
loopdiagram.py failing

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#141]
this is in the develop branch.

running from ./eppy/useful_scripts folder I get 

    python loopdiagram.py ../resources/iddfiles/Energy+V8_0_0.idd ../resources/idffiles/V8_0_0/5ZoneWaterLoopHeatPump.idf 
    Traceback (most recent call last):
      File "loopdiagram.py", line 594, in <module>
        sys.exit(main())
      File "loopdiagram.py", line 579, in main
        data, commdct = readidf.readdatacommdct(fname, iddfile=iddfile)
    ValueError: too many values to unpack

**Comment by jamiebull1** [comment]
Feels like something that we've fixed before. I'm just heading out for the night but I'll take a look tomorrow.

**Comment by santoshphilip** [comment]
thanx. 
I need to make a presentation with this next week to a delegation from Japan. Having it working would help

**Comment by MatthewSteen** [comment]
I'm getting a different error running this script on an 8.6.0 example file via a Jupyter 2.7 notebook:

```
%%bash
python loopdiagram.py "C:\EnergyPlusV8-6-0\Energy+.idd" "C:\EnergyPlusV8-6-0\ExampleFiles\5ZoneDetailedIceStorage.idf"
```

```
Traceback (most recent call last):
  File "loopdiagram.py", line 554, in <module>
    sys.exit(main())
  File "loopdiagram.py", line 545, in main
    required=True)
  File "C:\Miniconda2\lib\argparse.py", line 1276, in add_argument
    kwargs = self._get_positional_kwargs(*args, **kwargs)
  File "C:\Miniconda2\lib\argparse.py", line 1388, in _get_positional_kwargs
    raise TypeError(msg)
TypeError: 'required' is an invalid argument for positionals
```

**Comment by jamiebull1** [comment]
@MatthewSteen I'm forever fixing this one in a hurry just to get something working so I'll make an effort to get it merged.
