### ISSUE TITLE
Some objects have problems in fieldnames:

### ISSUE THREAD

**Issue by wta12** [santoshphilip/eppy#144]
```python 
key = "GROUNDHEATTRANSFER:SLAB:XFACE"
print(obs[key][0].fieldnames)         
['key', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a'] 
```
There are some objects which field names have problem : 

> GGROUNDHEATTRANSFER:SLAB:YFACE
> GROUNDHEATTRANSFER:SLAB:ZFACE
> SITE:SPECTRUMDATA
> GROUNDHEATTRANSFER:BASEMENT:XFACE
> GROUNDHEATTRANSFER:SLAB:XFACE
> GROUNDHEATTRANSFER:BASEMENT:YFACE
> GROUNDHEATTRANSFER:BASEMENT:ZFACE

Which part has problem ? Energy+.idd or eppy module ?
Thank

**Comment by santoshphilip** [comment]
Something looks really broken.
Which version of E+ are you using when you run into these problems.
I'll take a look.

**Comment by wta12** [comment]
the E+ 8.6 used,
Thanks

**Comment by santoshphilip** [comment]
E+ !IDD_Version 8.6.0 has idfobjects that has fields with no field names. 

eppy picks up the field names from the idd file. The  objects you have listed havefields that do not have field names. See the idd snippet below

    GroundHeatTransfer:Slab:XFACE,
             \memo This is only needed when using manual gridding (not recommended)
             \memo XFACE: X Direction cell face coordinates: m
            N1, N2, N3, N4, N5, N6, N7, N8, N9, N10, N11, N12, N13, N14,                  \note fields as indicated
            N15, N16, N17, N18, N19, N20, N21, N22, N23, N24, N25, N26, N27, N28, N29,    \note fields as indicated
            N30, N31, N32, N33, N34, N35, N36, N37, N38, N39, N40;                        \note fields as indicated
    
An idfobject that has field names would look like this:

        Version,
              \memo Specifies the EnergyPlus version of the IDF file.
              \unique-object
              \format singleLine
          A1 ; \field Version Identifier
              \default 8.6
        
See:

    A1 ; \field Version Identifier
    
The field name here is `Version Identifier`. `Eppy` will treat this as `Version_Identifier`. Note that `GROUNDHEATTRANSFER:SLAB:XFACE` does not have any field names. 

Without field names, looks like eppy is fundamentally broken. But all is not lost, we can still work with this. Let me demonstrate with this sample code

    from eppy import modeleditor 
    from eppy.modeleditor import IDF
    iddfile = "/Applications/EnergyPlus-8-6-0/Energy+.idd"

    import StringIO
    IDF.setiddname(iddfile)
    idf = IDF(StringIO.StringIO(""))
    
    ver = idf.newidfobject("version".upper())
    print ver
    
    ----
    VERSION,                  
        8.6;                      !- Version Identifier
    ----

    print ver.obj

    ----    
    ['VERSION', u'8.6']
    ----
    
The actual data structure for the idfobject is in the list ver.obj. Eppy is really syntactic sugar around this list. So let us change this list directly and see what happens.

    ver.obj[-1] = 'Spiderman'
    print ver.obj
    print ver
    
    ----    
    ['VERSION', 'Spiderman']

    VERSION,                  
        Spiderman;                !- Version Identifier
    ----    

We can do the same with `GROUNDHEATTRANSFER:SLAB:XFACE`:

    groundtr_x = idf.newidfobject("GROUNDHEATTRANSFER:SLAB:XFACE")
    print groundtr_x.obj
    
    ----    
    ['GROUNDHEATTRANSFER:SLAB:XFACE']
    ----    
    
To add new fields to it we directly change groundtr_x.obj

    groundtr_x.obj.append(5)
    print groundtr_x.obj
    print groundtr_x
    

    ----    
    ['GROUNDHEATTRANSFER:SLAB:XFACE', 5]

    GROUNDHEATTRANSFER:SLAB:XFACE,
        5;                        !- a
    ----    

Going further we can also do this:

    groundtr_x.obj.extend([6,7,99])
    print groundtr_x.obj
    print groundtr_x
    
    ----    
    ['GROUNDHEATTRANSFER:SLAB:XFACE', 5, 6, 7, 99]

    GROUNDHEATTRANSFER:SLAB:XFACE,
        5,                        !- a
        6,                        !- a
        7,                        !- a
        99;                       !- a
    ----    

This will give a stop gap measure to still be able to use eppy.

I am not sure of what is the best long term solution to this. Would appreciate any suggestions from others who are following this thread. (I am travelling with poor internet connectivity, so my responses may be delayed)

**Comment by santoshphilip** [comment]
@wta12 Can you take a look at what these objects look like in the IDF Editor. Post a screen shot if you can. I am on a Mac without access to a Windows machine. I am trying to get a sense of direction as to how to handle this in eppy

**Comment by wta12** [comment]
![image](https://cloud.githubusercontent.com/assets/16380735/21506968/1cd11a7c-cc3a-11e6-9d9c-44cce3d995f7.png)
![Uploading image.png…]()

**Comment by santoshphilip** [comment]
Thanks.

I'll have to update eppy function in the same way.
This will happen in the next release.

**Comment by wta12** [comment]
Thank a lot @santoshphilip : Please ask EP team about this object before because they seem new objects and have completely difference description in idd

**Comment by santoshphilip** [comment]
Looks like the E+ team got those objects out in a hurry and did not make field names. In any case I'll update eppy so that it will work without field names. I would like eppy to work with all versions of E+.

Yes. I'll check with E+ team about this

**Comment by santoshphilip** [comment]
@JasonGlazer @jwitte Looks like E+ version 8.6 has some objects with fields that have no field names (in the IDD file). What would be the best place to report this ? Should I open an issue at https://github.com/NREL/EnergyPlus/issues . 

I can update the IDD  such that they have field names and any other missing attributes, so they can be incorporated into the next release.  Would it make sense to fork the repository and then make a pull request ?

**Comment by JasonGlazer** [comment]
@santoshphilip @mjwitte The GroundHeatTransfer:Slab:ZFACE (as well as the XFACE and YFACE) do not have field names and haven't had them for a while (EnergyPlus 6.0 to 8.6 did not have field names). Given that, I presume this was an intentional decision to leave them out.

**Comment by mjwitte** [comment]
@santoshphilip  These particular objects were copied almost verbatim from the SlabGHT.idd, and they don't have field names there either.  There are other places in the IDD where the first few groups of fields have field names, but then the remaining fields do not, such as ZoneProperty:UserViewFactors:bySurfaceName and Table:MultiVariableLookup.  So, field names are not required and I'm not sure it's worth changing that now, especially for these objects which are pre-processor objects that are not read directly by EnergyPlus.  I certainly wouldn't want to add a field name to every one of the fields in objects like Table:MultiVariableLookup. If eppy needs field names to work with, it could default to the N1/A1 as a field name.  

That said, if you want to propose changes, then yes, fork the EnergyPlus repo, make a new branch with the changes, and make a pull request.  You also need to agree to the [contribution terms](https://www.energyplus.net/contributing).

**Comment by jamiebull1** [comment]
+1 for defaulting to N1/A1 etc.

**Comment by santoshphilip** [comment]
Yes, I agree that eppy should use N1/A1 when there are no field names. I'll go ahead and update eppy to do so.

Having said that, some thinking aloud below.

I tested

    ZoneProperty:UserViewFactors:bySurfaceName
    Table:MultiVariableLookup
    Table:MultiVariableLookup
    
with eppy.

Eppy will automatically generate field names, if the first few names are give and the there is a note saying:

    \note fields as indicated
    
Eppy depends on the IDD to file to make sense of E+ and eppy has a lot of internal code to do this. As a result it would be easy to write scripts for eppy to check if the IDD file is coherent and consistent. These scripts could be used  like mathdiff and tablediff before a release. 

This is not a priority on eppy's roadmap (non-existent roadmap, I must say), but an interesting and unexpected possibility.

**Comment by santoshphilip** [comment]
branch `i144_fieldnames` has been updated to have N1/A1 fields for idfobjects that have no field names.

I am on a bad internet connection. I'll merge this into master and make a new release once I get to a better connection.

**Comment by santoshphilip** [comment]
This has been released as r0.5.43 and uploaded to pypi
