### ISSUE TITLE
assign while looping through fieldnames

### ISSUE THREAD

**Issue by grilloz89** [santoshphilip/eppy#146]
Hi, 

I am trying to assign a set of values to all the fields in an object, specifically 24 temperature setpoint values to a Schedule:Day:Hourly object.

I wanted to do this with a for loop but I can't get the assign operation to work.  I know that .fieldnames method return a list of strings but I can't find a way to loop through the actual fields of the object.

I checked the documentation with the printing example but I can't achieve the assign operation. Here a rudimentary code of what I am trying to achieve 

``` setpoint_list = [21,21,21.........]
hourly_schedules = test.idfobjects['SCHEDULE:DAY:HOURLY']

for i in hourly_schedules[7].fields:
    field[i] = setpoint_list[i]
```

I hope to have explained myself. Thanks!

**Comment by lymereJ** [comment]
Hi - 

If I understand your problem correctly the code below might work. It creates a blank idf file, creates a Schedule:Day:Hourly object, names it and loop through its fields and assign a value of 24 to each hourly field. Is that what you are trying to do?

`from eppy import modeleditor
from eppy.modeleditor import IDF

IDDFile = 'C:\EnergyPlusV8-6-0\Energy+.idd'
IDF.setiddname(IDDFile)

idf_filen = open("blank.idf",'w+')
idf_filen.close
idf_file = IDF(idf_filen)

hr_sch = idf_file.newidfobject('SCHEDULE:DAY:HOURLY')
hr_sch_fields = hr_sch.fieldnames

for i in range(1,len(hr_sch_fields)):
	if hr_sch_fields[i] == "Name":
		hr_sch[hr_sch_fields[i]] = "Dummy Schedule"
	elif hr_sch_fields[i] == "Schedule_Type_Limits_Name":
		pass
	else:
		hr_sch[hr_sch_fields[i]] = 24

idf_file.saveas("dummy_schedule.idf")`

**Comment by santoshphilip** [comment]
@grilloz89 @lymereJ , 
   There is a more sneaky undocumented way of doing this.
   
continuing with @lymereJ code::

    from eppy import modeleditor
    from eppy.modeleditor import IDF

    IDDFile = 'C:\EnergyPlusV8-6-0\Energy+.idd'
    IDF.setiddname(IDDFile)

    idf_filen = open("blank.idf",'w+')
    idf_filen.close
    idf_file = IDF(idf_filen)

    hr_sch = idf_file.newidfobject('SCHEDULE:DAY:HOURLY')
    hr_sch_fields = hr_sch.fieldnames

hr_sch holds its data in a list. Everything else is syntactic sugar around it.
The data is is hr_sch.obj

    print hr_sch.obj
    
    ['SCHEDULE:DAY:HOURLY', u'', u'', 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
We can directly change the list::

    hr_sch.obj[3] = 15
    print hr_sch.obj
    
    ['SCHEDULE:DAY:HOURLY', u'', u'', 15, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    
     print hr_sch.Hour_1
     
     15
     
So if you have a list of hourdata you want to put into SCHEDULE:DAY:HOURLY, you could do the following::

    hourdata = [1,2,3,4,5,6,7,8,9,10,11,12,12,11,10,9,8,7,6,5,4,3,2,1]
    hr_sch.obj[3:] = hourdata
    print hr_sch.obj

    ['SCHEDULE:DAY:HOURLY', u'', u'', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]
    
    print hr_sch
    
    SCHEDULE:DAY:HOURLY,      
        ,                         !- Name
        ,                         !- Schedule Type Limits Name
        1,                        !- Hour 1
        2,                        !- Hour 2
        3,                        !- Hour 3
        4,                        !- Hour 4
        5,                        !- Hour 5
        6,                        !- Hour 6
        7,                        !- Hour 7
        8,                        !- Hour 8
        9,                        !- Hour 9
        10,                       !- Hour 10
        11,                       !- Hour 11
        12,                       !- Hour 12
        12,                       !- Hour 13
        11,                       !- Hour 14
        10,                       !- Hour 15
        9,                        !- Hour 16
        8,                        !- Hour 17
        7,                        !- Hour 18
        6,                        !- Hour 19
        5,                        !- Hour 20
        4,                        !- Hour 21
        3,                        !- Hour 22
        2,                        !- Hour 23
        1;                        !- Hour 24

**Comment by lymereJ** [comment]
This is great! Thank you @santoshphilip for sharing!

**Comment by santoshphilip** [comment]
I realized that the above code is much clearer is you use fieldvalues:

    print hr_sch.fieldvalues
    
    ['SCHEDULE:DAY:HOURLY', u'', u'', 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


All that was coded with hr_sch.obj will work hr_sch.filednames

    hr_sch.fieldvalues[5] = 111
    print hr_sch.fieldvalues

    ['SCHEDULE:DAY:HOURLY', u'', u'', 1, 2, 111, 4, 5, 6, 7, 8, 9, 10, 11, 12, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]  

    print hr_sch.Hour_3

    111
