### ISSUE TITLE
Testing for IronPython

### ISSUE THREAD

**Issue by yiyuan1840** [santoshphilip/eppy#150]

**Comment by yiyuan1840** [comment]
I found another problem when importing `modeleditor.py` in InronPython, this time it complains another python package called "py". 
This is the second time I met this kind of issue that the error is caused by eppy but by a python package that was called by eppy. It sort of becomes a nested problem... 

When I do `from eppy import modeleditor`
```
Runtime error (InvalidOperationException): Unsupported param dictionary type: IronPython.Runtime.PythonDictionary
Traceback:
  line 44, in initpkg, "C:\Anaconda2\Lib\site-packages\py\_apipkg.py"
  line 21, in <module>, "C:\Anaconda2\Lib\site-packages\py\__init__.py"
  line 22, in <module>, "C:\Anaconda2\Lib\site-packages\eppy\modeleditor.py"
  line 7, in script
```

**Comment by santoshphilip** [comment]
Can you check which branch you are working with.
use the `develop` branch - it has the updates that @jamiebull1 made.
I think you are in the `master` branch

**Comment by yiyuan1840** [comment]
I was using develop branch. Here is when I do `import py`

```
Runtime error (InvalidOperationException): Unsupported param dictionary type: IronPython.Runtime.PythonDictionary
Traceback:
  line 44, in initpkg, "C:\Anaconda2\Lib\site-packages\py\_apipkg.py"
  line 21, in <module>, "C:\Anaconda2\Lib\site-packages\py\__init__.py"
  line 9, in script
```

**Comment by santoshphilip** [comment]
@yiyuan1840 ,
that does look like a problem.

eppy may still run - since eppy does not need py (pytest) to function.
But we will not be able to test it if pytest does not run. All our tests are written in pytest :-(

I did a google search and found this:

http://grokbase.com/t/python/ironpython-users/137a6pptxh/pytest-incompatible-unsupported-param-dictionary-type-ironpython-runtime-pythondictionary

So we are not the only people running into this.Although there does not seem to be a solution in that thread - and this problem has been around for a while.
Maybe, we should test with the latest version of IronPython in the hope that it is fixed there.

I also found 
https://bitbucket.org/dahlia/pytest-ironpython

**Comment by santoshphilip** [comment]
@yiyuan1840 ,
with the present set up, it may be difficult to run all the tests in IronPython.

Can you try running through part of the tutorial in IronPython
http://pythonhosted.org/eppy/Main_Tutorial.html

Let me know where things break.

**Comment by yiyuan1840** [comment]
@santoshphilip Line 22 in modeleditor.py calls `py`, which causes the issue:
`from py._log import warning`

Shall I comment these out and run the test?

**Comment by jamiebull1** [comment]
I thought that was already fixed? Let me take another look if that's what's
causing the problems.

**Comment by santoshphilip** [comment]
The `develop` branch line 22 in modeleditor.py is:  

    from six import iteritems

The `master` branch line 22 in modeleditor.py is:  

    from py._log import warning

@yiyuan1840 , are you sure you are on the `develop` branch. It is possible that you are still on the `master` branch.

Git can be maddeningly obscure when you use it for the first time. Ask for us help if **git** is giving you trouble or is misleading you

**Comment by yiyuan1840** [comment]
@santoshphilip @jamiebull1 My apology guys, it was a false alarm. 
I was on the master branch.
I will delete this issue and reopen to avoid future confusions. 

Sorry.

**Comment by santoshphilip** [comment]
Let us stay with this issue -**Testing for IronPython**
no need to close it, since we are still trying to test eppy on IronPython.

I don't think there will be any confusion.

It will be fine if we reopen this issue rather than start a new issue

**Comment by yiyuan1840** [comment]
@santoshphilip I'm OK with that.  
Am I understanding right that since the py is not compatible with eppy,
we can't use the py.test to test but rather to follow the tutorial?

**Comment by jamiebull1** [comment]
It looks like there's a [fork of pytest](https://bitbucket.org/dahlia/pytest-ironpython) for IronPython. You could try installing that and running the pytests as usual.

**Comment by santoshphilip** [comment]
good point about the fork.
If that works, that is the best. (we need no workarounds)

@yiyuan1840 , you may be doing all this for the first time. So do ask for help if you need it.

**Comment by yiyuan1840** [comment]
Guys @santoshphilip @jamiebull1, I might need your help to get this setup. 
So far I had tried to download the `pytest-ironpython` package and saved in the site-packages folder of IronPython `C:\Program Files (x86)\IronPython 2.7\Lib\site-packages`
and then I tried to import `pytest-ironpython` in the IronPython editor, it complain about the "-" sign.
how should I proceed from here?

On a different note.
I did succeed to run py.test (using the default python implementations) from cmd when cd into the tests folder of eppy, however, when I do `py.test C:\Anaconda2\Lib\site-packages\eppy\tests` , there's a failure reported.

**Comment by jamiebull1** [comment]
I'm not 100% sure but I would expect that you run `pytest-ironpython` in the same way as you run `pytest`. That's also what the [documentation](https://bitbucket.org/dahlia/pytest-ironpython) seems to say.

You should just be able to import it as `pytest`, or run it from the command line using `py.test test_module.py`.

**Comment by santoshphilip** [comment]
@yiyuan1840 ,
It makes sense to try things out with the regular python.

Regarding regular python

- I strongly recommend virtualenv (but it is not essential)
- I lets you isolate different enviorments
- take a look at 
    - https://virtualenv.pypa.io/en/stable/
    - http://python-guide-pt-br.readthedocs.io/en/latest/dev/virtualenvs/
- also look at
    - https://virtualenvwrapper.readthedocs.io/en/latest/
    
to run the tests, go to root folder for eppy. the folders under this would look like:
    
    --docs
        --generated
        --source
    --eppy
        --useful_scripts
        --tests
        --resources
        --runner
        
you can run all the test here by typing `py.test`. On my computer the output looks like this:

    (eppy)Santoshs-MacBook-Air:eppy santoshphilip$ py.test
    ============================= test session starts ==============================
    platform darwin -- Python 2.7.10, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
    rootdir: /Users/santoshphilip/Documents/coolshadow/github/eppy, inifile: 
    collected 167 items 

    eppy/tests/test_IDF.py ...
    eppy/tests/test_bunch_subclass.py .............
    eppy/tests/test_bunchhelpers.py ....
    eppy/tests/test_examples.py ....
    eppy/tests/test_hvacbuilder.py .................
    eppy/tests/test_iddgaps.py .
    eppy/tests/test_idfreader.py .
    eppy/tests/test_json_functions.py ..
    eppy/tests/test_loopdiagram.py ....s
    eppy/tests/test_modeleditor.py .....................
    eppy/tests/test_modeleditor1.py ............
    eppy/tests/test_readhtml.py ......
    eppy/tests/test_runner.py .......ssssssssssssssssssssss
    eppy/tests/test_simpleread.py ..
    eppy/tests/test_thermal_properties.py ......................
    eppy/tests/EPlusInterfaceFunctions_tests/test_iddgroups.py .......
    eppy/tests/EPlusInterfaceFunctions_tests/test_iddindex.py ...
    eppy/tests/EPlusInterfaceFunctions_tests/test_parse_idd.py ..
    eppy/tests/geometry_tests/test_area_zone.py .
    eppy/tests/geometry_tests/test_surface.py .....
    eppy/tests/geometry_tests/test_volume_zone.py .
    eppy/tests/integration/test_integration.py ssssss

    =================== 138 passed, 29 skipped in 10.56 seconds ====================


You can also run a single test by as follows:

  (eppy)Santoshs-MacBook-Air:eppy santoshphilip$ py.test eppy/tests/test_IDF.py 
  ============================= test session starts ==============================
  platform darwin -- Python 2.7.10, pytest-3.0.2, py-1.4.31, pluggy-0.3.1
  rootdir: /Users/santoshphilip/Documents/coolshadow/github/eppy, inifile: 
  collected 3 items 

  eppy/tests/test_IDF.py ...

  =========================== 3 passed in 1.68 seconds ===========================

**Comment by santoshphilip** [comment]
to test in IronPython

- remove the pytest install
- install pytest-ironpython

Then test the same way as you did in regular python by running `py.test`. Actually there are 3 possible ways to run it. Try all to see if it works

- `py.test`
- `pytest`
- `python -m pytest`

**Comment by yiyuan1840** [comment]
Thanks for the notes. I think I was managed to install pytest(for IronPython) after removed pytest.
And here's when I was trying to test eppy:
```
C:\Anaconda2\Lib\site-packages>cd eppy

C:\Anaconda2\Lib\site-packages\eppy>py.test
============================= test session starts =============================
platform win32 -- Python 2.7.13 -- py-1.4.32 -- pytest-2.6.0.dev1
collected 0 items / 23 errors

=================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_IDF.py ______________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
________________ ERROR collecting tests/test_bunch_subclass.py ________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_________________ ERROR collecting tests/test_bunchhelpers.py _________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___________________ ERROR collecting tests/test_examples.py ___________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_______________ ERROR collecting tests/test_function_helpers.py _______________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_________________ ERROR collecting tests/test_hvacbuilder.py __________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___________________ ERROR collecting tests/test_iddgaps.py ____________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
__________________ ERROR collecting tests/test_idfreader.py ___________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
________________ ERROR collecting tests/test_json_functions.py ________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_________________ ERROR collecting tests/test_loopdiagram.py __________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_________________ ERROR collecting tests/test_modeleditor.py __________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
_________________ ERROR collecting tests/test_modeleditor1.py _________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (string ref out of range)
___________________ ERROR collecting tests/test_readhtml.py ___________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
____________________ ERROR collecting tests/test_runner.py ____________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   TypeError: NULL object in marshal data for object
__________________ ERROR collecting tests/test_simpleread.py __________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
______________ ERROR collecting tests/test_thermal_properties.py ______________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___ ERROR collecting tests/EPlusInterfaceFunctions_tests/test_iddgroups.py ____
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
____ ERROR collecting tests/EPlusInterfaceFunctions_tests/test_iddindex.py ____
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___ ERROR collecting tests/EPlusInterfaceFunctions_tests/test_parse_idd.py ____
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___________ ERROR collecting tests/geometry_tests/test_area_zone.py ___________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
____________ ERROR collecting tests/geometry_tests/test_surface.py ____________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
__________ ERROR collecting tests/geometry_tests/test_volume_zone.py __________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
___________ ERROR collecting tests/integration/test_integration.py ____________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
========================== 23 error in 2.07 seconds ===========================
```

**Comment by santoshphilip** [comment]
quick question - can you get the tests to run in regular python with regular pytest ?

**Comment by yiyuan1840** [comment]
Yes, I did test the standard pytest before removing it. It works fine, only one failure (something related weather file path). 
I'm going to setup the virtualenv tool to test both.

**Comment by yiyuan1840** [comment]
While I did setup a separate python env for the test, using the `conda ` tool. 
Here again are some reported errors:

```
(testENV) C:\Anaconda2\envs\testENV\Lib\site-packages\eppy>py.test
============================= test session starts =============================
platform win32 -- Python 2.7.13 -- py-1.4.32 -- pytest-2.6.0.dev1
collected 0 items / 23 errors

=================================== ERRORS ====================================
_____________________ ERROR collecting tests/test_IDF.py ______________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
________________ ERROR collecting tests/test_bunch_subclass.py ________________
..\py\_path\local.py:662: in pyimport
    __import__(modname)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:134: in find_module
    co = _read_pyc(fn_pypath, pyc)
..\pytest-2.6.0.dev1-py2.7.egg\_pytest\assertion\rewrite.py:311: in _read_pyc
    co = marshal.load(fp)
E   ValueError: bad marshal data (unknown type code)
```

**Comment by santoshphilip** [comment]
I installed IronPython and started working with it.
I did not even get as far as you got.

I am having trouble even installing eppy :-(

**Comment by santoshphilip** [comment]
@yiyuan1840 I am distracted by some other deadlines, I'll get back to this soon.

**Comment by jamiebull1** [comment]
I just finished something so I can take a look again. It would be nice to get this working reliably.

**Comment by yiyuan1840** [comment]
@santoshphilip @jamiebull1 It would be great if you guys could help me figure out some of the errors, I will have some time on the weekend to look into it.

**Comment by jamiebull1** [comment]
@santoshphilip I can't get `eppy` installed under IronPython either. 

```
>>>ipy -X:Frames -m pip install .

Traceback (most recent call last):
  File "setup.py", line 2, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\setuptools\__init__.py", line 11, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\setuptools\extern\__init__.py", line 1, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\__init__.py", line 46, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\extern\__init__.py", line 42, in load_module
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 701, in <module>
  File "C:\Program Files (x86)\IronPython 2.7\Lib\site-packages\pkg_resources\_vendor\six.py", line 692, in exec_
AttributeError: 'module' object has no attribute '_getframe'
```

**Comment by santoshphilip** [comment]
@yiyuan1840 My understanding is that you installed eppy ? How did you do this ? Did you do it within Grasshopper

**Comment by yiyuan1840** [comment]
@santoshphilip No, I didn't install eppy in IronPython. I did use grasshopper to import eppy (as a python module), and it was successful. (I would need to set "[Frames Enabled](https://unmethours.com/question/23188/issues-when-importing-eppy-in-ghpython-editor-of-grasshopper/)" in Rhino though). 
So it seems your approach is to install eppy as an IronPython module and test it in IronPython env. I haven't tried that route. While if we can import python module in IronPython, do we need to install eppy in IronPython?

**Comment by santoshphilip** [comment]
We have failed to directly install Eppy in iron python. Your approach shows more promise.

**Comment by santoshphilip** [comment]
@yiyuan1840 , I think I'll have to install rhino and grasshopper and work on this. I don't have time for this right now, since I'll be traveling. Will get to this in mid-June. Will need your knowledge of grasshopper once I start on it.

I am leaving this issue open until we fix it.

**Comment by santoshphilip** [comment]
This has been resolved by avoiding IronPython altogether.
See issue #162
