### ISSUE TITLE
eppy idf.run() error

### ISSUE THREAD

**Issue by dahdo1m** [santoshphilip/eppy#155]
Hi!

I'm experiencing the following error whenever I'm trying to run an EnergyPlus simulation using eppy idf.run():

`
i=[0,1,2,3]

for i in i:

    OA.Economizer_Control_Type = ECT[i]

    idf1.saveas('C:/Users/mdahdolan/Dropbox/Work and Studies/Economizer Study/Python/1A_Small_Office.idf')

    print(OA.Economizer_Control_Type)

    idf1.run()
`

This is how the output looks:

NoEconomizer
---------------------------------------------------------------------------
FileNotFoundError                         Traceback (most recent call last)
<ipython-input-29-a6844a5ae308> in <module>()
      4     idf1.saveas('C:/Users/mdahdolan/Dropbox/Work and Studies/Economizer Study/Python/1A_Small_Office.idf')
      5     print(OA.Economizer_Control_Type)
----> 6     idf1.run()

C:\ProgramData\Anaconda3\lib\site-packages\eppy\modeleditor.py in run(self, **kwargs)
    999         self.saveas('in.idf')
   1000         # run EnergyPlus
-> 1001         run('in.idf', self.epw, **kwargs)
   1002         # remove in.idf
   1003         os.remove('in.idf')

C:\ProgramData\Anaconda3\lib\site-packages\eppy\runner\run_functions.py in run(idf, weather, output_directory, annual, design_day, idd, epmacro, expandobjects, readvars, output_prefix, output_suffix, version, verbose)
    207     try:
    208         if verbose == 'v':
--> 209             check_call(cmd)
    210         elif verbose == 'q':
    211             check_call(cmd, stdout=open(os.devnull, 'w'))

C:\ProgramData\Anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
    284     check_call(["ls", "-l"])
    285     """
--> 286     retcode = call(*popenargs, **kwargs)
    287     if retcode:
    288         cmd = kwargs.get("args")

C:\ProgramData\Anaconda3\lib\subprocess.py in call(timeout, *popenargs, **kwargs)
    265     retcode = call(["ls", "-l"])
    266     """
--> 267     with Popen(*popenargs, **kwargs) as p:
    268         try:
    269             return p.wait(timeout=timeout)

C:\ProgramData\Anaconda3\lib\subprocess.py in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags, restore_signals, start_new_session, pass_fds, encoding, errors)
    705                                 c2pread, c2pwrite,
    706                                 errread, errwrite,
--> 707                                 restore_signals, start_new_session)
    708         except:
    709             # Cleanup if the child failed starting.

C:\ProgramData\Anaconda3\lib\subprocess.py in _execute_child(self, args, executable, preexec_fn, close_fds, pass_fds, cwd, env, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite, unused_restore_signals, unused_start_new_session)
    988                                          env,
    989                                          cwd,
--> 990                                          startupinfo)
    991             finally:
    992                 # Child is launched. Close the parent's copy of those pipe

FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by dahdo1m** [comment]
Would you please help me using it?
@santoshphilip @jamiebull1 

Many Thanks,

**Comment by santoshphilip** [comment]
is this failing because of an error in the idf file ?

Can you try running `1A_Small_Office.idf` from EPLaunch to see if gives any errors.

Also, the start of your code is not making sense:

    i=[0,1,2,3]
    for i in i:

That may not be working the way you think it should. More likely it should be:

    lst = [0,1,2,3]
    for i in lst:

**Comment by dahdo1m** [comment]
The file works perfectly using EPLaunch, I don't think the loop part is the problem, I used idf.run() outside the loop and I received the same error.

**Comment by santoshphilip** [comment]
OK,
Can you post your code and the the idf file somewhere I can get at it.
Maybe at https://gist.github.com

Let me see what I find out. Right now it is not clear to me.
There is a chance we might need @jamiebull1 to look into this. He wrote a lot of this code.

**Comment by dahdo1m** [comment]
Is it possible to share with me an actual example of a simulation being run using eppy?

**Comment by dahdo1m** [comment]
Sure

**Comment by dahdo1m** [comment]
https://gist.github.com/dahdo1m/13db07c02c0bdbdaba51ca8182800732

**Comment by dahdo1m** [comment]
Is it also possible to share an actual example of a Jupyter Notebook used to simulate an IDF file?

**Comment by santoshphilip** [comment]
You can save the file in the notebook format and put it on gist. I can download and open it up. I think there are other ways, but don't know about them.

**Comment by santoshphilip** [comment]
Can you put the 1A_Small_Office.idf on gist.
I'll probably get to this late tonight.

**Comment by dahdo1m** [comment]
Absolutely

**Comment by santoshphilip** [comment]
I did a few quick tests:
 - idf.run() works with `EnergyPlus-8-1-0`
- idf.run() throws an error with `EnergyPlus-8-6-0`

So there is a bug in eppy, your code may be fine. I'll start to look into the bug. I hope it is an easy fix.

## Long term note:
- There are no tests that check if eppy works with each new version of EnergyPlus
- It may be wise to set up such tests and run them with each release of E+

**Comment by jamiebull1** [comment]
You mentioned this back [here](https://github.com/santoshphilip/eppy/issues/135), @santoshphilip

**Comment by dahdo1m** [comment]
Good Evening,

I downgraded to versions 8.1.0 and 8.0.0 and I still got the same error.

**Comment by santoshphilip** [comment]
Not working with 8.1 and 8.0 is unexpected. (I had tested with an example file)
Can you test with an example file just as a sanity check

**Comment by santoshphilip** [comment]
@jamiebull1 , Is your `oCo Carbon` email broken? I sent you a non-critical email some time back. I got a feeling you did not receive it, or it hit your spam filter. Should I resend to your gmail account

**Comment by jamiebull1** [comment]
@santoshphilip it's working as far as I know, but I've not seen anything from you that I recall. Try the gmail though, it's always the most reliable way to get me.

**Comment by dahdo1m** [comment]
![capture2](https://cloud.githubusercontent.com/assets/28791372/26332238/0541789e-3f1b-11e7-96e5-05254aa9417c.JPG)

**Comment by santoshphilip** [comment]
I have been able to successfully run that file with both 8.0 and 8.1 in ipython

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: from eppy import modeleditor

    In [2]: from eppy.modeleditor import IDF

    In [3]: iddfile = "/Applications/EnergyPlus-8-1-0/Energy+.idd"

    In [4]: idffile = "/Applications/EnergyPlus-8-1-0/ExampleFiles/BasicsFiles/Exercise1A.idf"

    In [5]: epwfile = "/Applications/EnergyPlus-8-1-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"

    In [6]: 

    In [6]: IDF.setiddname(iddfile)

    In [7]: idf = IDF(idffile, epwfile)

    In [8]: idf.run()
    EnergyPlus Starting
    EnergyPlus, Version 8.5.0-c87e61b44b, YMD=2017.05.22 17:03
    Processing Data Dictionary
    Processing Input File
    Initializing Simulation
    Reporting Surfaces
    Beginning Primary Simulation
    Initializing New Environment Parameters
    Warming up {1}
    Warming up {2}
    Warming up {3}
    Warming up {4}
    Warming up {5}
    Warming up {6}
    Starting Simulation at 07/21 for CHICAGO_IL_USA COOLING .4% CONDITIONS DB=>MWB
    Initializing New Environment Parameters
    Warming up {1}
    Warming up {2}
    Warming up {3}
    Warming up {4}
    Warming up {5}
    Warming up {6}
    Starting Simulation at 01/21 for CHICAGO_IL_USA HEATING 99.6% CONDITIONS
    Writing final SQL reports
    EnergyPlus Run Time=00hr 00min  0.23sec


and 

    (eppy_pypi)Santoshs-MacBook-Pro:temp santosh$ ipython
    WARNING: Attempting to work in a virtualenv. If you encounter problems, please install IPython inside the virtualenv.
    Python 2.7.10 (default, Feb  6 2017, 23:53:20) 
    Type "copyright", "credits" or "license" for more information.

    IPython 4.0.0 -- An enhanced Interactive Python.
    ?         -> Introduction and overview of IPython's features.
    %quickref -> Quick reference.
    help      -> Python's own help system.
    object?   -> Details about 'object', use 'object??' for extra details.

    In [1]: """testing idf.run()"""
    Out[1]: 'testing idf.run()'

    In [2]: 

    In [2]: from eppy import modeleditor

    In [3]: from eppy.modeleditor import IDF

    In [4]: # iddfile = "/Applications/EnergyPlus-8-1-0/Energy+.idd"

    In [5]: # idffile = "/Applications/EnergyPlus-8-1-0/ExampleFiles/BasicsFiles/Exercise1A.idf"

    In [6]: # epwfile = "/Applications/EnergyPlus-8-1-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"

    In [7]: 

    In [7]: iddfile = "/Applications/EnergyPlus-8-0-0/Energy+.idd"

    In [8]: idffile = "/Applications/EnergyPlus-8-0-0/ExampleFiles/BasicsFiles/Exercise1A.idf"

    In [9]: epwfile = "/Applications/EnergyPlus-8-0-0/WeatherData/USA_IL_Chicago-OHare.Intl.AP.725300_TMY3.epw"

    In [10]: 

    In [10]: IDF.setiddname(iddfile)

    In [11]: idf = IDF(idffile, epwfile)

    In [12]: idf.run()
    EnergyPlus Starting
    EnergyPlus, Version 8.5.0-c87e61b44b, YMD=2017.05.22 17:08
    Processing Data Dictionary
    Processing Input File
    Initializing Simulation
    Reporting Surfaces
    Beginning Primary Simulation
    Initializing New Environment Parameters
    Warming up {1}
    Warming up {2}
    Warming up {3}
    Warming up {4}
    Warming up {5}
    Warming up {6}
    Starting Simulation at 07/21 for CHICAGO_IL_USA COOLING .4% CONDITIONS DB=>MWB
    Initializing New Environment Parameters
    Warming up {1}
    Warming up {2}
    Warming up {3}
    Warming up {4}
    Warming up {5}
    Warming up {6}
    Starting Simulation at 01/21 for CHICAGO_IL_USA HEATING 99.6% CONDITIONS
    Writing final SQL reports
    EnergyPlus Run Time=00hr 00min  0.23sec

**Comment by santoshphilip** [comment]
Can you try your code with forward slash in the file names instead of the double-backslash

**Comment by santoshphilip** [comment]
I just reviewed the outputs and noticed that the runs above are in version 8.5
Ok ... let me dig into this.

**Comment by santoshphilip** [comment]
Looking into the code I see:

    try:
        VERSION = os.environ["ENERGYPLUS_INSTALL_VERSION"]  # used in CI files
    except KeyError:
        VERSION = '8-5-0'  # TODO: Get this from IDD, IDF/IMF, config file?

    if platform.system() == 'Windows':
        EPLUS_HOME = "C:/EnergyPlusV{VERSION}".format(**locals())
        EPLUS_EXE = os.path.join(EPLUS_HOME, 'energyplus.exe')
    elif platform.system() == "Linux":
        EPLUS_HOME = "/usr/local/EnergyPlus-{VERSION}".format(**locals())
        EPLUS_EXE = os.path.join(EPLUS_HOME, 'energyplus')
    else:
        EPLUS_HOME = "/Applications/EnergyPlus-{VERSION}".format(**locals())
        EPLUS_EXE = os.path.join(EPLUS_HOME, 'energyplus')

    EPLUS_WEATHER = os.path.join(EPLUS_HOME, 'WeatherData')
    THIS_DIR = os.path.abspath(os.path.dirname(__file__))

the version 8.5 is hard-coded at the moment.
Install E+ 8.5 and see if it runs.

**Comment by jamiebull1** [comment]
Yep, I just spotted that too. We have an outstanding issue somewhere about how best to deal with this.

**Comment by dahdo1m** [comment]
V8.5.0 Worked!

**Comment by santoshphilip** [comment]
OK ... So we know where the problem is.
May explain why 8.6 failed - although that needs to be confirmed.

**Comment by jamiebull1** [comment]
That's part of it, although I had issues trying to get things working with 8.6 as well. From memory it was just with setting up the test IDD though, so perhaps just running things would be fine.

**Comment by dahdo1m** [comment]
Question...
After I run it using the code, I can't see any output tables in the directory of the example file, am I supposed to add another line to save outputs in a CSV file?

**Comment by santoshphilip** [comment]
Look in the folder from where you ran your script.

**Comment by dahdo1m** [comment]
Found it, thanks.

**Comment by dahdo1m** [comment]
So this is the first time for me using python in my work wit E+, will it be OK if I refer to you whenever I face a dead end?

**Comment by santoshphilip** [comment]
You have three options for that:
- open an issue here - especially if you think eppy is doing something wrong.
- ask a question on https://unmethours.com
- ask a question on http://groups.yahoo.com/group/EnergyPlus_Support/

There are many knowledgeable python people on [unmethours](https://unmethours.com) . I'll see it there too. Also search to see if your question has been asked before.

**Comment by santoshphilip** [comment]
released r0.5.44 fixing above issues. Available at pypi for pip install
