### ISSUE TITLE
Finding correct version of EnergyPlus for `idf.run`

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#156]
This is an issue for thoughts on design for the `IDF.run()` function, which is currently hard-coded to EnergyPlus version 8.5.

There's a todo note I left for myself:

    VERSION = '8-5-0'  # TODO: Get this from IDD, IDF/IMF, config file?

These seem like the obvious options. I lean towards the IDD, since it's the one that's guaranteed to have a version.

It should probably be set as a variable on the `IDF` object when the IDD is read. This variable would then be available in `eppy.runner.run_functions.run()` and could used to set `EPLUS_HOME`, `EPLUS_EXE`, etc. instead of having them as module-level constants.

**Comment by santoshphilip** [comment]
I prefer the picking it up from the IDD. It makes logical sense, since you have to set the iddname before you do anything. I may be best positioned to write the code that will find the version from the IDD file. Let me take a stab at it.

**Comment by santoshphilip** [comment]
Made a branch `i156_eplusversion`
Working thru the tutorial you get:

    # if you have not done so, uncomment the following three lines
    import sys
    # pathnameto_eppy = 'c:/eppy'
    pathnameto_eppy = '../'
    sys.path.append(pathnameto_eppy)
    from eppy import modeleditor
    from eppy.modeleditor import IDF
    iddfile = "../eppy/resources/iddfiles/Energy+V7_2_0.idd"
    fname1 = "../eppy/resources/idffiles/V_7_2/smallfile.idf"
    IDF.setiddname(iddfile)
    idf1 = IDF(fname1)

I have added a new variable:

    print idf1.idd_version  # not sure if that is the best name
    (7, 2, 0, 6)

I was already reading the idd version as a **_tuple_** to be used internally by the IDD parser. It was in an inconvenient place. Added a few lines of code to get it out where it is handy

It is ready for you, if you want to have a go at updating the runner code.

**Comment by jamiebull1** [comment]
Ok, this is working relatively well now, thanks for digging out that feature. The only problem is that when I run the integration tests with the `8.5.0` IDD, the `IDF` object has already had the `8.0.0.008` from `iddcurrent` attached to it and I can't see why it's persisting between test runs. This was the same issue I ran into when trying to set up a simple way of running integration tests against the latest version of EnergyPlus, so solving it would be great!

I'll keep looking into this, but let me know if you have any insight, @santoshphilip .

**Comment by jamiebull1** [comment]
Ok, got it working. I needed to reload the `modeleditor` module in the first test called in the `test_runner` module.

**Comment by santoshphilip** [comment]
released r0.5.44 fixing above issues. Available at pypi for pip install
