### ISSUE TITLE
CSV output files with Eppy

### ISSUE THREAD

**Issue by rodrigokl** [santoshphilip/eppy#159]
Hi everyone, firstly, thank you for continuing to work on this project. I'm a student, and in my project I need to manipulate the .csv output files from E+. Does eppy offer some functionality for manipulating output data that is not in HTML format?
Thank you again!

**Comment by jamiebull1** [comment]
Hi @rodrigokl Does it have to be the CSV outputs? I usually use `esoreader` to read the `sqlite` output.

**Comment by rodrigokl** [comment]
Hi @jamiebull1, with the sqlite output I can get the results of the variables requested by the user in the output: variable? Thanks for your prompt response!

**Comment by jamiebull1** [comment]
Yes, exactly. You just need to specify the SQL output in your IDF.

    Output:SQLite, Simple;

**Comment by jamiebull1** [comment]
Sorry, I'm getting mixed up. As the name implies, it's the `.eso` file it parses, not the SQL. I'm muddling things up with jEPlus.

**Comment by rodrigokl** [comment]
Thanks a lot, I'll try to use the esoreader for my problem. Have a nice day @jamiebull1!

**Comment by rodrigokl** [comment]
Hello again, your help saved my day. Sorry, but I'll take this issue to ask one more thing.
Regarding the run() method, in cases with HVAC does it present problems? I ask this because all tests of ExempleFiles and this file with air conditioning in E+ 8.5 presented the following error:

EnergyPlus Starting
EnergyPlus, Version 8.5.0-c87e61b44b, YMD=2017.05.25 15:03
Processing Data Dictionary
Processing Input File
**FATAL:Program Terminates: The ExpandObjects program has not been run or is not in your EnergyPlus.exe folder.
EnergyPlus Run Time=00hr 00min  0.15sec
Traceback (most recent call last):
  File "run.py", line 14, in <module>
    idf.run()
  File "/usr/local/lib/python2.7/dist-packages/eppy-0.5.44-py2.7.egg/eppy/modeleditor.py", line 1004, in run
    run(self, self.epw, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/eppy-0.5.44-py2.7.egg/eppy/runner/run_functions.py", line 238, in run
    check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'/usr/local/EnergyPlus-8-5-0/energyplus', u'--output-directory', u'/home/rodrigo/Documentos/Test', u'--weather', '/usr/local/EnergyPlus-8-5-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw', u'/home/rodrigo/Documentos/Test/in.idf']' returned non-zero exit status 1
n both versions (2.7 and 3.5). I'm doing something wrong?
Ty!

**Comment by jamiebull1** [comment]
You need to tell Eppy to expand the objects, same as you would at the command line.

    run(idf, epw, expandobjects=True)

**Comment by rodrigokl** [comment]
Sure, it makes sense! hahaha. Thanks again and again @jamiebull1
