### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 3: ordinal not in range(128) on idf.save()

### ISSUE THREAD

**Issue by rodrigokl** [santoshphilip/eppy#160]
Hi guys,
I tried using `idf.save(encoding = 'utf-8')` to avoid this error, but it did not work. Any idea?

Traceback (most recent call last):
  File "fluxos_simula.py", line 42, in <module>
    idf.save(encoding='utf-8')
  File "/usr/local/lib/python2.7/dist-packages/eppy/modeleditor.py", line 920, in save
    s = self.idfstr()
  File "/usr/local/lib/python2.7/dist-packages/eppy/modeleditor.py", line 877, in idfstr
    astr = astr + obj.__repr__()
  File "/usr/local/lib/python2.7/dist-packages/eppy/bunch_subclass.py", line 345, in __repr__
    lines = [str(val) for val in self.obj]
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe2' in position 3: ordinal not in range(128)

Thanks!

**Comment by santoshphilip** [comment]
So how did this get fixed. 
I am traveling without my computer and cannot take a look.

**Comment by rodrigokl** [comment]
Hi @santoshphilip, 
Actually, I was trying to manipulate a template generated by Design Builder, and they usually give problem with my codes. To make sure the model was the problem, I tested other files with characters used in the Portuguese vocabulary (Brazil), and all saved without errors when I passed the `encoding=utf-8` parameter.
Thanks for listening!

**Comment by santoshphilip** [comment]
Ha. That is a coincidence. 
I am traveling in Brazil and you have an apparent Portuguese problem. 

Santosh.

**Comment by rodrigokl** [comment]
Haha. Cool! I'm from the south of the country, I hope you're enjoying the trip!
