### ISSUE TITLE
tests fail with pytest (3.2.1)

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#163]
- tests fail with pytest (3.2.1) - the latest pytest
- They used to pass with pytest (3.0.2)

Failure is in 
- eppy/tests/test_modeleditor.py:367: 
- failure is in:
    - def test_newidfobject_warning():
    - the warning is not raised

**Comment by santoshphilip** [comment]
- Created branch `i163_testfail` from `develop` 
- pushed to remote repository 
- test failure occurs on Travis CL, since it uses the latest pytest

**Comment by jamiebull1** [comment]
@santoshphilip I'll pick this up if you like?

**Comment by santoshphilip** [comment]
Yes please

**Comment by santoshphilip** [comment]
I have commented out the failing test in `develop`

**Comment by jamiebull1** [comment]
Sorry, missed you'd already started a branch

**Comment by santoshphilip** [comment]
@jamiebull1 's bug fix has been merged into develop
