### ISSUE TITLE
Test if Eppy can be frozen to a stand alone application

### ISSUE THREAD

**Issue by JasonGlazer** [santoshphilip/eppy#165]
Test if eppy can be "frozen" to be a standalone exe using py2exe or cx_Freeze or pyinstaller. It would have to be able to widely distribute utilities based on eppy and not require typical uses to follow the installation process currently required for eppy.

**Comment by santoshphilip** [comment]
I found 
http://docs.python-guide.org/en/latest/shipping/freezing/

- Tested out pyinstaller on the mac.
- made a short script with the following code:

        from eppy import modeleditor
        from eppy.modeleditor import IDF
        iddfile = "/Applications/EnergyPlus-8-7-0/Energy+.idd"
        IDF.setiddname(iddfile)
        fname1 = "/Applications/EnergyPlus-8-7-0/ExampleFiles/4ZoneWithShading_Simple_1.idf"
        idf1 = IDF(fname1)
        idf1.printidf()

- froze it using pyinstaller
- worked like a charm (the executable is inside the dist folder that is generated by pyinstaller)
- Try it on a PC. It should be straightforward.

**Comment by jamiebull1** [comment]
That deserves a wow! I've had so much trouble trying to do this so I'm really surprised it was so smooth.

**Comment by santoshphilip** [comment]
Aha ! If @JasonGlazer thinks it is easy, he is likely to go off and build some amazing software for the rest of us :-)

My recollection is that freezing can be tricky at times. Usually problems are triggered by imported packages (like Numpy or imaging packages) and is dependent on the environment you are working in how those packages are installed on your machine.

Once you successfully freeze, the package seems to work with no further problems.

from what I see, you can:
- send command line args to the exe
- build a GUI and deploy.
- I have tested on PC and Mac. Linux should not be a problem

it is worth exploring the the different freeze packages. Some of them seem to generate more files than others and may not as clean to package.

@JasonGlazer , I am going to close this issue. If any problems crop up, open a new issue and we will take it from there. If you find the "One Way" to do this, we can add it to the docs for others to follow, so they don't have rediscover it.

**Comment by JasonGlazer** [comment]
Thanks @santoshphilip, that is great news.
