### ISSUE TITLE
MemoryError

### ISSUE THREAD

**Issue by mLazicic** [santoshphilip/eppy#168]
Hi,
i’am trying to make some changes on an IDF file (file size over 40MB) and would like to save it as new IDF file, but i get following error:

```
Traceback (most recent call last):
  File "IDF_Surfaces_change_v01.py", line 42, in <module>
    idf1.saveas(idf_OUT)
  File "C:\Users\mlazicic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eppy\modeleditor.py", line 967, in saveas
    self.save(filename, lineendings, encoding)
  File "C:\Users\mlazicic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eppy\modeleditor.py", line 923, in save
    s = self.idfstr()
  File "C:\Users\mlazicic\AppData\Local\Programs\Python\Python36-32\lib\site-packages\eppy\modeleditor.py", line 880, in idfstr
    astr = astr + obj.__repr__()
MemoryError
```

Python script:
```
from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = "Energy+.idd"
idffile = "test01.idf"
n = idffile.split(".")
idf_OUT = str(n[0] + "_OUT." + n[1])

IDF.setiddname(iddfile)
idf1 = IDF(idffile)

#idf1.printidf()

srf = idf1.idfobjects['BuildingSurface:Detailed'.upper()]

for s in srf:
	#print(s)
	name = s.Name
	constr = s.Construction_Name
	type = s.Surface_Type
	zone_name = s.Zone_Name
	outside = s.Outside_Boundary_Condition
	obj = s.Outside_Boundary_Condition_Object
	#print (outside)
	# check Surface Type: Wall, Roof, Ceiling, Floor
	if "Wall" in type:
		# check Outside Boundary: Outdoors, Surface
		if outside == "Outdoors":
			# check construction name
			if "IW" in constr:
				outside = "Surface"
				obj = name
				print ("\n" + obj)
			else:
				pass
		else:
			pass
	else:
		pass


idf1.saveas(idf_OUT)
```

With smaller files it works without problems. Is there any problem with IDF file size and memory?
Python 3.6.1
IDD Version 8.5.0

best regards, milorad

**Comment by santoshphilip** [comment]
There should be no limitation on file size. So I am not sure why it failed. I need to look into this.

Is there a way to get the large file to me. (does github have some mechanism to do so ?)
Try attaching it to your next comment - it might work.

If you have changed the idd file, I'll need that too.

**Comment by mLazicic** [comment]
The IDF is on google drive now: https://drive.google.com/drive/folders/0B4YKYm74MyCFT20tRldDQ3ZvMUk?usp=sharing

I didn't make any changes to the IDD.
when I split the file, then I get the new file without errors.

**Comment by santoshphilip** [comment]
Wow ! I could not open it in the idfeditor, since even that ran out of memory.
This is an impressive file :-)

**Comment by santoshphilip** [comment]
I renamed one of the objects:
gbXML Wärmedämmung: 015 [m] - aim103098_015
as
gbXML Warmedammung: 015 [m] - aim103098_015

eppy could not write it since it had non latin-1 characters.

Your script ran with no errors.

The script ended with:


    saving new file
    ('\n', '/Users/santosh/Dropbox/coolshadow/eppy/shared_files/test02_OUT.idf', '...saved')
    (eppy)Santoshs-MacBook-Pro:eppy santosh$ 


I ran it with python2 and it took forever to save :-(

I'll also test with python3 soon

**Comment by santoshphilip** [comment]
tested it with python3 (I also put a timer in it, to see how long it runs)
The script ends with:

    saving new file

     /Users/santosh/Dropbox/coolshadow/eppy/shared_files/test02_OUT.idf ...saved
    111.95428013801575 seconds
    1.8659046689669292 minutes

with python2, the script ends with:

    saving new file
    ('\n', '/Users/santosh/Dropbox/coolshadow/eppy/shared_files/test02_OUT.idf', '...saved')
    1604.92783093 seconds
    26.7487971822 minutes

python2 takes a lot longer to run. 

I am not able to recreate your memory error. 

I was running on the following hardware:

Hardware Overview:

    Model Name:	iMac
    Model Identifier:	iMac17,1
    Processor Name:	Intel Core i7
    Processor Speed:	4 GHz
    Number of Processors:	1
    Total Number of Cores:	4
    L2 Cache (per Core):	256 KB
    L3 Cache:	8 MB
    Memory:	16 GB
    Boot ROM Version:	IM171.0105.B26
    SMC Version (system):	2.34f2

What kind off memory does your machine have ?

**Comment by mLazicic** [comment]
I don’t thinks that there is any hardware limitations, the machine has i7-5500U CPU @2.40GHz (4 cores) processor and 16 GB RAM (only approximately 50% used by script)

The script runs on Ubuntu on the same machine without problems (with German letter “ä” in Wärmedämmung too), but on the Windows I get the same error without “ä” in material name. 
I have tried to change the regional setting on Windows to USA (now is a German version with regional setting Germany (Austria)), but it didn’t worked – the same error. It seems to be some problem related to the Windows - you tried it on a Mac and it runs without errors too. 

The solution for me is to run the scripts on Ubuntu, then to change the line endings from Linux to Windows and run simulation in EnergyPlus on Windows.
Thanks a lot for your investigations and tests.

The eppy is great work and make the interaction with IDF a lot easier.
Cheers, Milorad

**Comment by santoshphilip** [comment]
The German letter “ä” is a separate problem. I'll need to fix (or not fix) it as a separate issue.

You can run all the simulations on Ubuntu if you want to.  @jamiebull1  has written an excellent E+ runner for eppy. See <http://pythonhosted.org/eppy/runningeplus.html>

I am not sure why it is giving trouble in windows. I'll wait for someone to really needs it and then take steps to fix. it seems like a rarely occurring bug. 

I don't  hear about people using eppy. I am curious about how you are using it. Is there any functionality you would like eppy to have that it doesn't ?

**Comment by santoshphilip** [comment]
This issue is not a deal-breaker for anyone yet. It works on Linux and Mac. Gives trouble on Windows.  Will not fix now. Will fix if opened again

**Comment by mLazicic** [comment]
Hi Philip,
we are making the whole building simulations and have over 800 zones in one model (as you can see in that idf file). The models are built in Revit, than transferred via gbXML into DesignBuilder, than exported as idf and simulated in E+.

Use 01:
We have to input the whole interior gain for all zones – then the eppy and python comes into play. All interior gains for respective zones will be transfered from XLS file into idf file. 

Use 02: 
the surfaces in this transferred model must be checked and repaired – some of them are defined as the outside surfaces, but in reality those are inside (adiabatic) surfaces. In this case we use the eppy too. 

In our firm, the Windows is running on the simulations machines – the idf must be transferred to windows file (line endings)  

I deal with eppy for about few weeks, and find it very good solution for the editing of the idf files.  Now I got to polish my scripts and make the flowing workflow.

The next things are the automated filtering and  graphical representation of the results – on the one side the analysis of the .eso file and on the other analysis of the html file.
Maybe then I will get some ideas about the new functions for the eppy.

What is the idea of making the eppy? Are you dealing with energy simulations?

Best regards, Milorad
