### ISSUE TITLE
outputs reading html not working

### ISSUE THREAD

**Issue by spencerdutton** [santoshphilip/eppy#169]
I followed the tutorial. 

http://pythonhosted.org/eppy/Outputs_Tutorial.html

and I could not get it to run. It says.. 

from eppy.results import readhtml # the eppy module with functions to read the html
ImportError: No module named 'eppy.results'

**Comment by santoshphilip** [comment]
thanks @spencerdutton 
This is the result of a bug in the setup.py script. The results folder was not getting installed when using pip (which uses setup.py). I'll fix this in the develop branch.

**Comment by santoshphilip** [comment]
I have made two branches for this from the `develop` branch
1. `i169_readhtml` -> I am exploring how to test the installs before the release of master. Our present tests test check the code, and do not test the install
2. `i169_readhtml1` -> the setup.py is corrected here. If you install with `pip install https://github.com/santoshphilip/eppy/archive/i169_readhtml1.zip`, all will be well

**Comment by santoshphilip** [comment]
comment on unmethours says that this still does not work. 

https://unmethours.com/question/27980/python-eppy-readhtml-table/?answer=27987#post-id-27987

I will follow up here

**Comment by giorgiolupato** [comment]
I just realised I did not uninstall the 'eppy standard version' before installing 'i169_readhtml1.zip'. 
So: I unistalled eppy with
 `pip uninstall eppy` and then installed it again with pip install `pip install https://github.com/santoshphilip/eppy/archive/i169_readhtml1.zip`.
I think it works fine now! Thank you!

**Comment by santoshphilip** [comment]
got it.
Once make a new release in the master branch, this problem will go away.

**Comment by santoshphilip** [comment]
`i169_readhtml1 `has been merged into develop

**Comment by santoshphilip** [comment]
merged into master and released on pypi as version r0.5.45
