### ISSUE TITLE
geomeppy does not accept idf file

### ISSUE THREAD

**Issue by orcunkoraliseri** [santoshphilip/eppy#173]
i was trying to modify idf file with eppy but the code does not accept.

`# import eppy to run energyplus
import geomeppy
from geomeppy import IDF
from eppy.results import readhtml 
import random as rd
import pprint

#import idd / idf / epw file to run simulation
IDF.setiddname("C:/EnergyPlusV8-8-0/Energy+.idd")
#idfname =  "C:/Users/orcun/Desktop/eppy/energy_model_for_eppy/EnergyPlus/energy_model_for_eppy.idf"
idfname =  "C:/EnergyPlusV8-8-0/ExampleFiles/AdvancedOutput/ExerciseOutput1.idf"
epwfile = "C:/Users/orcun/Desktop/eppy/TUR_Izmir_Izmir_TurTMY.epw"
idf = IDF(idfname, epwfile)`

and i am taking this error meassage

`TypeError: missingkeys_nonstandard() takes at least 4 arguments (3 given)`

**Comment by santoshphilip** [comment]
Can you check what version of eppy are you using ?

My guess is that geomeppy was designed with an older version of eppy.
The author of geomeppy is @jamiebull1 (he is also an eppy developer)

He may be able to get at the issue quicker.
Or he can tell me what needs to be done in eppy.

I'll wait for his response

**Comment by orcunkoraliseri** [comment]
I am currently using latest verison of eppy. Probably i will upload older version and try it. Thank you for your answer.

**Comment by jamiebull1** [comment]
@orcunkoraliseri Actually, it seems like I need to update some more things to match with the current version of Eppy. I'll try and take a look in the next few days.

**Comment by jamiebull1** [comment]
@orcunkoraliseri try reinstalling from pip now. The problem should be fixed as of geomeppy v0.2.19

**Comment by orcunkoraliseri** [comment]
Thank you so much returning that fast. It worked well.
