### ISSUE TITLE
Speed up continuous integration

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#177]
This issue discusses ways we can speed up continuous integration by being a bit selective about what we include. This seems like it would particularly useful for @santoshphilip while developing the `py90dot1` project, as well as for any other contributors. Continuous integration is great, but when it's slow it becomes a lot less useful as immediate feedback.

My suggestions:

1. Remove the OSX builds from continuous integration entirely

They can take a couple of hours to run on Travis, while the Linux builds there are done in under five minutes. Windows on Appveyor comes in just under 30 minutes. Since @santoshphilip and I both develop on OSX, this is also the least likely place for us to miss a platform-specific issue.

2. Only test the most recent release version of Python 2 and Python 3, and of EnergyPlus

We currently cover 2.7, 3.5 and 3.6 for EnergyPlus versions 8.6, 8.7 and 8.8 (just 8.7 and 8.8 on Appveyor). Removing specific support for Python 3.5, and EnergyPlus 8.5 and 8.6 would reduce the Appveyor testing time in particular since jobs run one after another on that platform. By only testing the most recent versions, we could expect to get the time down from 30 minutes to around 10.

3. Run comprehensive tests for releases

We can make a way to only run OSX builds and builds for older versions of Python and EnergyPlus when merging into `master`. Then the only time we'd need to wait for hours on CI would be when preparing to merge `develop` into `master` for a release, or for any hotfixes that may need to go straight to `master`.

**Comment by santoshphilip** [comment]
@jamiebull1 , this is a good testing design. I have merged into `develop` and `master`
