### ISSUE TITLE
Multiprocessing or multithreading of idf file?

### ISSUE THREAD

**Issue by orcunkoraliseri** [santoshphilip/eppy#181]
While trying to execute batch process with multithreading by using idf, there is this problem occured. Main object of processing was sensitivity analysis of parameters for the defined output. Could you offer a solution for multiprocessing or multithreading?

To explain better the issue, we divide the process with two thread and while first thread executing the idf, second thread did not start.  

> Exception in thread Thread-2:
Traceback (most recent call last):
  File "D:\Program Files (x86)\Pythons\python 3\Lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "D:\Program Files (x86)\Pythons\python 3\Lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "C:/Users/orcun/PycharmProjects/thesis/Salib_01.py", line 52, in param_2
    idf2.run()
  File "C:\Users\orcun\venv\thesis\lib\site-packages\eppy\modeleditor.py", line 1004, in run
    run(self, self.epw, **kwargs)
  File "C:\Users\orcun\venv\thesis\lib\site-packages\eppy\runner\run_functions.py", line 238, in run
    check_call(cmd)
  File "D:\Program Files (x86)\Pythons\python 3\Lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:/EnergyPlusV8-8-0\\energyplus.exe', '--output-directory', 'C:\\Users\\orcun\\AppData\\Local\\Temp\\tmpbhm_7lzh', '--weather', 'C:\\Users\\orcun\\Desktop\\eppy\\E_eppy02_WWR\\OpenStudio\\E_eppy02_WWR\\ModelToIdf\\TUR_Izmir_Izmir_TurTMY.epw', 'C:\\Users\\orcun\\AppData\\Local\\Temp\\tmpbhm_7lzh\\in.idf']' returned non-zero exit status 1.

**Comment by jamiebull1** [comment]
Have a look at the `runIDFs` function in `eppy.runner.run_functions`. It uses the `multiprocessing` module.

**Comment by jamiebull1** [comment]
@orcunkoraliseri did this help at all?

**Comment by orcunkoraliseri** [comment]
This is the first time i am using multirunner and there an issue about job list? Are we dividing each idf object and parameters separately?

Is it possible to share a small example?

**Comment by jamiebull1** [comment]
Sure. This is based on the example in the eppy test suite.

        runs = []
       
        for fname in [list of IDF files]:
            runs.append([modeleditor.IDF(open(fname, 'r'), '/path/to/weatherfile.epw'),
                         {'output_directory': 'results_%i' % i,
                          'ep_version': '8-8-0'}])
        num_CPUs = 2
        runIDFs(runs, num_CPUs)

**Comment by orcunkoraliseri** [comment]
Thank you for your quick answer.

**Comment by orcunkoraliseri** [comment]
Hi again,

I'm working on Windows and trying to invoke the `runIDFs` with the below code. Nonetheless I am facing an error that states 'RuntimeError: An attempt has been made to start a new process before the current process has finished its bootstrapping phase.' Is this related with the library or Windows (i.e. multithreading issue on Windows).

Thanks in advance.

```python
for i in range(len(x1)):
    tmp = copy.copy(idf)
    tf.set_u_value_insulation(tmp,u_value_insulation=x4[i])
    tmp.saveas('idf_%i.idf' % i)
    tmp2 = modeleditor.IDF(open('idf_%i.idf' % i, 'r'), epwfile)
    job_list.append([tmp2, {'output_directory': 'results_%i' % i,
                  'ep_version': '8-8-0'}])

rr.runIDFs(job_list,processors=1)
```

**Comment by jamiebull1** [comment]
You need to have an `if __name__ == '__main__': block when using multiprocessing on windows.

https://stackoverflow.com/a/18205006/1706564

**Comment by orcunkoraliseri** [comment]
Thanks for the quick response again here's another thing where should I write this block? In the beginning of my script?

**Comment by jamiebull1** [comment]
Usually it goes at the bottom, with your script moved into a `main()` method.
