### ISSUE TITLE
Docstring does not reflect new arg run_functions.run()

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#183]
`run_functions.run()` has a new arg `iddname`. It needs to be added to the docstring with a description

**Comment by jamiebull1** [comment]
Looking at this I have no idea why I didn't use the existing `idd` parameter. I've made a couple of very small changes, so now we don't need the new parameter, and so don't need to change the documentation.

**Comment by santoshphilip** [comment]
I'll merge once you give me the OK

**Comment by santoshphilip** [comment]
Ignore my previous comment. I just saw your pull request

**Comment by santoshphilip** [comment]
merged
