### ISSUE TITLE
Memory Error with 'runIDFs'

### ISSUE THREAD

**Issue by orcunkoraliseri** [santoshphilip/eppy#185]
Hi, i am currently working with eppy to apply batch simulations of EnergyPlus. The reason that i am choosing the batch simulation technique, to use sensitivity analysis for the physical building parameters impacts on annual energy demand, such as WWR, orientation of the unit. Actually, these are the methods that belong to 'geomeppy' but currently i am doing simulations with runIDFs method so i thought that it is related with eppy.

My main problem happened because of the memory error. It can not handle more than 1000idfs on memory, but i am planning to work more than that to extract sensitivty indices. 

I am working on Windows and my computer specifications are Intel i7-6700HQ CPU @2.60GHz (4 cores), 16GB RAM (only 40% used). 

Is there any solution you can offer to me? Thanks for attention. 

> Traceback (most recent call last):
  File "C:/Users/orcun/PycharmProjects/thesis/morris_analyze02.py", line 46, in <module>
    idf.saveas('idf_%i.idf' % i)
  File "C:\Users\orcun\venv\thesis\lib\site-packages\eppy\modeleditor.py", line 967, in saveas
    self.save(filename, lineendings, encoding)
  File "C:\Users\orcun\venv\thesis\lib\site-packages\eppy\modeleditor.py", line 923, in save
    s = self.idfstr()
  File "C:\Users\orcun\venv\thesis\lib\site-packages\eppy\modeleditor.py", line 880, in idfstr
    astr = astr + obj.__repr__()
MemoryError

>

**Comment by jamiebull1** [comment]
Try using a generator?

**Comment by orcunkoraliseri** [comment]
Thank you for your quick answer. That is worked. 

I want to ask another question but i am not sure do i have to open an another issue?

Can we arrange EnergyPlus outputs?  
For instance, a simulation produce several type of files but just '.html' is enough to read out objective, such as heating demand.

**Comment by jamiebull1** [comment]
Yes, there are a lot of results produced. I'd suggest using the `output_directory` keyword arg, copying out the file or files you want to keep (the error file is often handy), then deleting the output directory.

**Comment by orcunkoraliseri** [comment]
That is right. I am doing it, thank you. You could close that issue.
