### ISSUE TITLE
WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM object not returning expected values

### ISSUE THREAD

**Issue by adChong** [santoshphilip/eppy#191]
Hi,

I was trying to add a WindowMaterial:SimpleGlazingSystem object to an EPlus file and wasn't able to do it because it the object seems to be missing the fields. Just a guess that the field "U-Factor" might be giving problems in the code but I might be wrong. 
```
> idf1 = IDF(StringIO(""))
> idf1.newidfobject('WindowMaterial:SimpleGlazingSystem'.upper())
```
gives
`WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM,;`

when according to the idd it should be
```
WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM,
    ,                         !- Name
    ,                         !- U-Factor
    ,                         !- Solar Heat Gain Coefficient
    ;                         !- Visible Transmittance
```

If I am doing something wrong, would also appreciate it if anyone could point me in the right direction

**Comment by santoshphilip** [comment]
try this:

    w = idf.newidfobject('WindowMaterial:SimpleGlazingSystem'.upper(), Name="gumby", UFactor=0.2)
    print w
    w.Solar_Heat_Gain_Coefficient = 0.3
    print w
    
    # also try:
    w1 = idf.newidfobject('WindowMaterial:SimpleGlazingSystem'.upper(), Visible_Transmittance=0.9)
    print w1



I looked at the IDD file. The fields do not have default values, so eppy does not know what to put in, if you do not give a value

If you just want to see the field names do:

    print w.fieldnames

**Comment by adChong** [comment]
Thank you for the tip! That solved my problem. I was trying to change the "UFactor" using the key "U-Factor"

**Comment by santoshphilip** [comment]
yup.  You cannot use U-Factor because python thinks the 'dash' is a negative sign. There are other fields the have these "illegal" characters. IdfObject.filenames will tell you what eppy is using for the field
