### ISSUE TITLE
No module named 'munch'

### ISSUE THREAD

**Issue by zhenglaishen** [santoshphilip/eppy#195]
I am trying to follow the tutorial of Eppy and when I run 'from eppy import modeleditor' in the Jupyter Notebook, it ended in ModuleNotFoundError: No module named 'munch'.

Does anyone know how to fix this problem? I tried different computers and this problem is still there.

Thank you,

**Comment by santoshphilip** [comment]
I need more information to understand what is going on

how did you install `eppy`
did you do `pip install eppy`

OR

did you do `pip install -r requirements.txt` ?

Are you in a virtualenv ?

**Comment by zhenglaishen** [comment]
I used pip install eppy.

**Comment by santoshphilip** [comment]
very mystifying.
I did the same thing and everything works on my end.

somehow `munch` is not getting installed on you machine.
Let me try a few things and get back to you on this.

Are you using a virtualenv ?
Do you know what that is ?

**Comment by santoshphilip** [comment]
Can you do `pip install munch`
and try again ?

**Comment by zhenglaishen** [comment]
Thanks for your kindly help. I am trying. I do not know what is virtualenv. Could you please explain how I can fix it?

I just installed the ANACONDA Python 3.6 version to substitute my previous ANACONDA Python 2.7.

**Comment by zhenglaishen** [comment]
It already works right now and that problem was fixed. Thanks for your great help!
Right now, I have another question in setting the idd file directory.  I put the download eppy file and the ipython code in the same folder and I guess this is what required.

However, when I run this script "IDF.setiddname(iddfile)", it ends in "No such file or directory: '../eppy/resources/iddfiles/Energy+V7_2_0.idd'".

Again, thanks for you help!

**Comment by santoshphilip** [comment]
use the IDD of your installed EnergyPlus. It may be at `c:/EnergyplusV8-9-0/E+.idd` or something like that.

**Comment by zhenglaishen** [comment]
Yes, it works. Thanks!!!
