### ISSUE TITLE
Readvars does not produce hourly CSV outputs

### ISSUE THREAD

**Issue by eloneill** [santoshphilip/eppy#196]
When running a simulation and setting readvars=True, ReadVarsESO does not seem to process the eplusout.eso file into a CSV.

**Comment by santoshphilip** [comment]
I am unfamiliar with eplusout.eso being converted into a csv file.
Can do you do this with EpLaunch ?
Can you point me to the documentation on this.

@ncbrown , are you familiar with this ?

I might have to experiment a bit to figure this our.

**Comment by eloneill** [comment]
When you run EPLaunch, this is done automatically. To be honest, I'm not even sure I see readvars=True doing anything in run_functions.py, but I'm far from an expert on the coding side of things. Could the problem be that that argument isn't running RunVarsESO at all?

https://bigladdersoftware.com/epx/docs/8-0/input-output-reference/page-090.html

**Comment by santoshphilip** [comment]
- idf.run() is a python wrapper around the EnergyPlus command line interface
- so in principle it should be able to do anything that the command line does. (and cannot do something that the command line cannot do)

In any case, I am a little curious now and will look into this.

**Comment by santoshphilip** [comment]
I found two issues related to this
- https://github.com/NREL/EnergyPlus/issues/5058
- https://github.com/NREL/EnergyPlus/issues/5898

I tested it with `idf.run(readvars=True)` with `EnergyPlus-8-9-0` and `ReadVarsESO` is running on that version
From the above issues, it seems like the earlier versions (need to check which versions) are not running `ReadVarsESO`

I'll update the documentation to reflect this.

**Comment by santoshphilip** [comment]
Ok I tested `idf.run(readvars=True)` with 

- EnergyPlus-8-3-0 - DOES NOT make CSV
- EnergyPlus-8-4-0 - makes CSV
- EnergyPlus-8-5-0 - makes CSV
- EnergyPlus-8-6-0 - makes CSV
- EnergyPlus-8-7-0 - makes CSV
- EnergyPlus-8-8-0 - makes CSV
- EnergyPlus-8-9-0 - makes CSV

**Comment by santoshphilip** [comment]
I'll update the documentation in eppy to reflect this and then close this issue

**Comment by santoshphilip** [comment]
documentation has been updated in the `develop` branch
