### ISSUE TITLE
Error in modifying RunPeriod

### ISSUE THREAD

**Issue by hydrangea009** [santoshphilip/eppy#199]
Hi~ I have a question as the following. Thank you very much.
1.	I tried to change the values of elements in the object named RunPeriod.
For example, I changed the element named Start Month, when I printed the whole object, it didn’t show the change, but when I printed only this element, it changed. I saved this file as another copy file and opened this copy, it didn’t show the changes(shown in the following snapshot).
![1](https://user-images.githubusercontent.com/38921798/39542621-ad92eb74-4e0e-11e8-8851-018d30074019.png)

**Comment by hydrangea009** [comment]
# manage E+ file
import sys
# pathnameto_eppy = 'c:/eppy'
pathnameto_eppy = '../'
sys.path.append(pathnameto_eppy) 
#
from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = "../eppy/resources/iddfiles/Energy+V8_5_0.idd"# for revision

try:
    IDF.setiddname(iddfile)
except modeleditor.IDDAlreadySetError as e:# ?
    pass

fname1 = "../eppy/resources/idffiles/V8_5/tr1.idf"# for revision
idf1 = IDF(fname1)
idf1.printidf()
runtime=idf1.idfobjects['RUNPERIOD']
print runtime
j=2
runtime.Begin_Month=j
print runtime
print runtime.Begin_Month
###############
And some content of the idf file is as the following:
RunPeriod,
    Untitled (01-01:31-12),    !- Name
    1,                        !- Begin Month
    1,                        !- Begin Day of Month
    12,                       !- End Month
    31,                       !- End Day of Month
    UseWeatherFile,           !- Day of Week for Start Day
    No,                       !- Use Weather File Holidays and Special Days
    No,                       !- Use Weather File Daylight Saving Period
    Yes,                      !- Apply Weekend Holiday Rule
    Yes,                      !- Use Weather File Rain Indicators
    Yes,                      !- Use Weather File Snow Indicators
    1;                        !- Number of Times Runperiod to be Repeated

**Comment by hydrangea009** [comment]
Do I need to provide more？ Thank you very much.

**Comment by santoshphilip** [comment]
I made some changes to your code (I have marked it with `# *****CHANGE*****`)


    pathnameto_eppy = '../'
    sys.path.append(pathnameto_eppy)

    from eppy import modeleditor
    from eppy.modeleditor import IDF

    iddfile = "../eppy/resources/iddfiles/Energy+V8_5_0.idd"# for revision

    IDF.setiddname(iddfile)

    fname1 = "../eppy/resources/idffiles/V8_5/tr1.idf"# for revision
    idf1 = IDF(fname1)
    idf1.printidf()
    runtimes = idf1.idfobjects['RUNPERIOD'] # *****CHANGE*****
    print runtimes
    runtime = runtime[0] # *****CHANGE*****
    j=2
    runtime.Begin_Month=j
    print runtime
    print runtime.Begin_Month





idfobjects will get all the objects with that keyword. For instance you can have multiple ZONE idfobjects.
eppy thinks that you will always have multiple idfobjects. Although at times you will have only one, such as in `VERSION` OR `BUILDING`


    runtimes = idf1.idfobjects['RUNPERIOD']
    
Is all the runtimes in a list (only one in this case). To get the first item in the list you do

    runtime = runtime[0]
    
everything should work from there.

*Note:* All that I have typed above is untested code. May have typos.


If everything works out and you understand what is going on, go ahead and close this issue

**Comment by hydrangea009** [comment]
It worked. Thank you very much.
