### ISSUE TITLE
import eppy error

### ISSUE THREAD

**Issue by hydrangea009** [santoshphilip/eppy#201]
Hi~ I have a question as the following. Thank you very much.
I cannot import eppy shown in the following picture.
![q1](https://user-images.githubusercontent.com/38921798/40095178-37a0b02c-5890-11e8-8bb8-5ed4c4c5fd19.JPG)

**Comment by santoshphilip** [comment]
How did you install eppy
- did you do `pip install eppy`
- OR
- did you clone or download the repository 
- something else ?

**Comment by hydrangea009** [comment]
I used pip instal eppy.

**Comment by ZixiaoShi** [comment]
Are you using Anaconda? You need to install eppy inside your anaconda environment.

________________________________

**Comment by hydrangea009** [comment]
Yes, I did inside  anaconda environment. But it didnot work.

**Comment by hydrangea009** [comment]
Is there any other method that I can use to install eppy and import it in ipython?

**Comment by hydrangea009** [comment]
I used Anaconda 3.6 and python 3.6.5.

**Comment by santoshphilip** [comment]
@hydrangea009 , Is this issue the same as  same #201 ?
I have posted a response in #201, that may get your code to work.

Although if you do `pip install eppy` you should be able to successfully `import eppy` without using `sys.path.append( ... )`. Meaning, you should be able to import eppy from any folder. 

I am unfamiliar with the anaconda environment, so I can't advice you on that. @ZixiaoShi comments on it make sense

**Comment by hydrangea009** [comment]
issue #201 was a problem in another computer which had succesfully run the code. For this issue, I just try to import eppy by ipython but it did not work. I will check whether I installed pip properly. Thank you.

**Comment by santoshphilip** [comment]
Did you get it to work ?
Can I close this issue

**Comment by santoshphilip** [comment]
In line 10 of your code, I see  a double slash `espy-master//eppy`. That typo may be causing a problem. Replace it with a single slash and see if it works.

**Comment by hydrangea009** [comment]
I changed that. I can run the previous steps but I cannot run the last step(shown in the following picture).
![q6](https://user-images.githubusercontent.com/38921798/40430167-20c1b61e-5e6a-11e8-98c7-d5093523c5a9.JPG)

**Comment by hydrangea009** [comment]
I change the working directory and move it to directory of eppy and it worked.  Thank you very much.

**Comment by santoshphilip** [comment]
I still think something is wrong here. It should work from any directory.

- you have given the full path name to the iddfile. 
- `iddfile = c:/Users/user/De .....Energy+V8_5_0.idf`
- the error message has the partial pathname `../eppy/res.......Energy+V8_5_0.idf`
- The error message should give the full pathname `c:/Users/users .......Energy+V8_5_0.idf`

I don't know why that is happening and I can't recreate it here on my machine (my setup is different)

Since it is working now, I am going to close the issue.
