### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by hydrangea009** [santoshphilip/eppy#202]
Hi~ I have a question as the following. Thank you very much.
I have used this code succesfully before, but now it shows error. as shown in the piture.
![q2](https://user-images.githubusercontent.com/38921798/40141975-05547058-591d-11e8-84ad-d71581381ab2.jpg)

**Comment by santoshphilip** [comment]
Try

    pathnameto_eppy = "C:/Users/shens/Desktop/eppy-master/"

see it it works

**Comment by santoshphilip** [comment]
this is clearly an eppy installation issue
If eppy had been installed, `munch` have been installed.

see @ZixiaoShi 's comment in #201 on installing eppy with Anaconda

Another alternative you can try is 
- `pip install -r requirements.txt`. munch is in requrements.txt and it will get installed

**Comment by santoshphilip** [comment]
Any luck on this.
Can I close this issue ?
