### ISSUE TITLE
Unable to run idf with HVACTemplate

### ISSUE THREAD

**Issue by adChong** [santoshphilip/eppy#203]
Hi,

I am trying to run an EnergyPlus idf file that contains the HVACTemplate objects in EnergyPlus. The file runs when using EP-launch but when I tried running it with eppy with `idf.run()`, I got the following error message.

`FATAL:Program Terminates: The ExpandObjects program has not been run or is not in your EnergyPlus.exe folder.`

Therefore, I was wondering if anyone has encountered similar problems and could provide suggestions as to how this could be resolved.

Thank you in advance.

**Comment by lymereJ** [comment]
Are you using the `expandobjects` parameter?
http://eppy.readthedocs.io/en/latest/runningeplus.html

**Comment by adChong** [comment]
Works now! Thank you
