### ISSUE TITLE
Problem with idf.run() 

### ISSUE THREAD

**Issue by hydrangea009** [santoshphilip/eppy#205]
Hi~ I have a question as the following. Thank you very much.
When I use idf.run(), it showed that "The system could not find the specified file".
I used the newest version 8.9.0 for E+. 
![q7](https://user-images.githubusercontent.com/38921798/41621878-8e1f9450-73d3-11e8-8617-459df8875265.png)

**Comment by jamiebull1** [comment]
Have you added the files in the locations you're passing? It looks like you're looking in the `eppy.resources` directory rather than the EnergyPlus install directory.

**Comment by hydrangea009** [comment]
Yes, I put the file in the directory that I typed in.

**Comment by jamiebull1** [comment]
Can you run using those files from the command line, or by using EP-launch?

**Comment by hydrangea009** [comment]
I can run the file by using EP-launch.

**Comment by jamiebull1** [comment]
How about from the command line?

`C:/EnergyPlusV8-9-0/energyplus.exe --weather C:/Python36/Lib/site-packages/eppy/resources/weatherfiles/USA_CA_Los.Angeles.Intl.AP.722950_TMY3.epw C:/Python36/Lib/site-packages/eppy/resources/idffiles/V8_9/tr1.idf`

**Comment by hydrangea009** [comment]
The command line did not work. I tried the command **idf.run()** again and it seemed that the function cannot obtain **cmd** correctly (shown in the following picture).
And there were a slash and backslash in one line (shown in the following picture): “'C:/EnergyPlusV8-9-0\\energyplus.exe'
![0715-1](https://user-images.githubusercontent.com/38921798/42739531-9c09f214-885e-11e8-80ec-5966711e46b4.JPG)

**Comment by jamiebull1** [comment]
>The command line did not work

In what way didn't it work?

**Comment by hydrangea009** [comment]
I changed the idf file and close all the antivirus programs. Now I can run the code successfully in ipython and command line（shown in the following picture for the records） But I did not find the results or any output file in my computer. Could you tell me the default path for the output files? Thank you very much.
The record for ipython:
![0716-1](https://user-images.githubusercontent.com/38921798/42772646-b06ed8e0-88f0-11e8-82b3-a414748ba6a5.png)
![0716-2](https://user-images.githubusercontent.com/38921798/42772715-dfc8d99c-88f0-11e8-9b3c-a1494143a144.png)
The record for the command:
![0716-3](https://user-images.githubusercontent.com/38921798/42772729-eb0f6212-88f0-11e8-88be-35d8331b5b2a.png)

**Comment by hydrangea009** [comment]
I have fixed it. Thank you very much. Sorry for that I forgot to close the issue.
