### ISSUE TITLE
inlet and outlet branches for condenser loop not put on branchlist

### ISSUE THREAD

**Issue by JasonGlazer** [santoshphilip/eppy#21]
When running the example from the documentation for forming a condenser loop, the inlet and outlet branches are not included in the branchlist.

    loopname = "c_loop"
    sloop = ['sb0', ['sb1', 'sb2', 'sb3'], 'sb4'] # supply side
    dloop = ['db0', ['db1', 'db2', 'db3'], 'db4'] # demand side
    theloop = hvacbuilder.makecondenserloop(theIdf, loopname, sloop, dloop)

The branchlists formed are:

BRANCHLIST,               
    c_loop Cond_Supply Branchs,    !- Name
    sb1,                      !- Branch 1 Name
    sb2,                      !- Branch 2 Name
    sb3;                      !- Branch 3 Name

BRANCHLIST,               
    c_loop Condenser Demand Branchs,    !- Name
    db1,                      !- Branch 1 Name
    db2,                      !- Branch 2 Name
    db3;                      !- Branch 3 Name
 
which is missing sb0, sb4, db0, db4.

**Comment by santoshphilip** [comment]
Looks like it works. 
Closing this issue
