### ISSUE TITLE
"CalledProcessError: returned non-zero exit status 1." when runing EnergyPlus from python 

### ISSUE THREAD

**Issue by zhengzhuang3** [santoshphilip/eppy#215]
Dear santoshphilip,
An error is thrown when I ran EnergyPlus from python. ("CalledProcessError: returned non-zero exit status 1." )
The strange thing is that it succeeds when I run idf file with no hvac system assigned.
However, when I assign VRF hvac system to above idf file through IDF editor or through eppy, the error is always given when using idf.run(). ("CalledProcessError: returned non-zero exit status 1."
And I checked that when I run the same idf files in EnergyPlus directly by clicking buttons, it succeeds. So strange!

**Comment by santoshphilip** [comment]
@jamiebull1 , I am in the innards of epJSON trying to make it work with eppy (epJSON being the new file format for idf and idd files)
Also working with functions for building up plants and systems (I have some experienced people helping on this)

I don't have the band width to look at this issue.

If you have the time, can you take a look ?

**Comment by zhengzhuang3** [comment]
Thank you so much. And I attached the two idf files below for your convenience. 
 The two files can both be simulated by EP_luanch directly. However, the idf file named "single_block_withhvac" cannot be simulated through idf.run() while the other can. The only difference is that the "single_block_withhvac" idf is assigned a VRF hvac system. 

[single_block.txt](https://github.com/santoshphilip/eppy/files/2462890/single_block.txt)
[single_block_withhvac.txt](https://github.com/santoshphilip/eppy/files/2462891/single_block_withhvac.txt)
I changed the ".idf" into ".txt" for uploading

**Comment by zhengzhuang3** [comment]
I tried to simulate two .idf files  above in EnergyPlus from the command line. 
But "single_block.idf" completed successfully while "single_block_withhvac.idf" thrown a mistake "EnergyPlus Terminated--Error(s) detected".  
Then, I simulated the two files manually by clicking buttons in EP-launch. They both gave several warnings but they completed successfully. 
Is it because that I assigned the VRF system in a wrong way?  But I made it through EP-Launch... 
Can anyone help me out, please?

**Comment by jamiebull1** [comment]
@santoshphilip sure, I'll take a look

**Comment by jamiebull1** [comment]
@zhengzhuang3 The file contains HVAC templates so you need to call `idf.run` with `expandobjects=True`.
