### ISSUE TITLE
Add more helpful error messages when IDF.run fails

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#217]
At the moment, error messages are not returned to the python process when an exception occurs. This makes it difficult for users to debug problems.

It would be useful to add:
- contents of std out
- contents (or summary) of the `.err` file
- path to the `.err` file

**Comment by santoshphilip** [comment]
reviewing now

**Comment by santoshphilip** [comment]
@jamiebull1 I have merged your pull request into `develop` branch. 

Can you make add a section to ./docs/runningeplus.rst, on debugging the run function when things go wrong and where to find the error information. 

This will make it more likely for users to include the error information when they report a run() issue
