### ISSUE TITLE
Why does idf.idfobjects['WINDOW'] have no area attribute?

### ISSUE THREAD

**Issue by nheeren** [santoshphilip/eppy#230]
OK. This is probably a total noob question which is due to a lack in knowledge in energyplus and eppy, but why does `idf.idfobjects['BuildingSurface:Detailed'.upper()][0].area` return a value and `idf.idfobjects['Window'.upper()][0].area` cause an error?

    eppy.bunch_subclass.BadEPFieldError: unable to find field area

Thank you very much for any pointers.

**Comment by jamiebull1** [comment]
The reason is that only these fields have the `area` property added by Eppy.

        "BuildingSurface:Detailed",
        "Wall:Detailed",
        "RoofCeiling:Detailed",
        "Floor:Detailed",
        "FenestrationSurface:Detailed",
        "Shading:Site:Detailed",
        "Shading:Building:Detailed",
        "Shading:Zone:Detailed"

I think this is because the way we calculate area for surfaces with a full set of coordinates doesn't work for simplified elements like `Window`. However they do have length and height fields so you can use:

    window = idf.idfobjects['Window'.upper()][0]
    window_area = window.length * window.height

**Comment by nheeren** [comment]
Dear Jamie. This question / issue actually goes back to an [answer of yours on UnmetHours](https://unmethours.com/question/15574/how-to-list-and-measure-area-surfaces/?answer=15604#post-id-15604). Thank you for the help. I will multiplying height times width.

**Comment by nheeren** [comment]
Unfortunately, this did not work, because there are no length and height attributes. I had to use something like this:

```python
window = idf.idfobjects['Window'.upper()][0]
length = window.obj[-2]  # The second but last item is !- Length {m}
height = window.obj[-1]  # The last item is !- Height {m} 
area = length * height
```

Maybe eppy should have some way to make this easier in the future. Please close the issue as you see fit.

**Comment by santoshphilip** [comment]
Niko,    I suspect that did not work because `Length` and `Height` need to start with caps.
Try this

    window = idf.idfobjects['Window'.upper()][0]
    window_area = window.Length * window.Height

**Comment by santoshphilip** [comment]
Niko,    It should be fairly easy to add the `area` function to `WINDOW` object. Would you like to take a stab at doing that? If you need any help doing that, I'll be happy to assist.

If you make a pull request after coding it. I'll merge it in to `eppy`

**Comment by jamiebull1** [comment]
> Niko, I suspect that did not work because `Length` and `Height` need to start with caps.

Sorry about that!

**Comment by santoshphilip** [comment]
to get the correct field names do this:

    window = idf.idfobjects['Window'.upper()][0]
    window.fieldnames

you will get:

    [u'key',
     u'Name',
     u'Construction_Name',
     u'Building_Surface_Name',
     u'Frame_and_Divider_Name',
     u'Multiplier',
     u'Starting_X_Coordinate',
     u'Starting_Z_Coordinate',
     u'Length',
     u'Height']

**Comment by santoshphilip** [comment]
I was having a hard time testing the code before posting comments here.
So I opened a new issue to make it easier to open a idf file or create a new one. it is  issue in #231

**Comment by nheeren** [comment]
> Niko, I suspect that did not work because `Length` and `Height` need to start with caps.

Oops - you are absolutely right! Thank you very much for tuning into this.

> I was having a hard time testing the code before posting comments here.
> So I opened a new issue to make it easier to open a idf file or create a new one. it is issue in #231

Sorry, I am not sure why you mention this here.

> If you make a pull request after coding it. I'll merge it in to `eppy`

I'll look into it.

**Comment by santoshphilip** [comment]
python does give you a way to introspect the attributes of a class

    window = idf.idfobjects['Window'.upper()][0]
    print dir(window)
    
will give you the attributes. 

Having said that, eppy overrides a some of the built-in fuctionality of python. So it may not always behave the ways in which standard python code behaves. Although it should be fine for this example.


Ignore my comment on issue #231. 

Do look into writing an area function for WINDOW.

**Comment by santoshphilip** [comment]
Niko,
    I'll let you close this issue, if you are done with it.

**Comment by santoshphilip** [comment]
dammit, my finger slipped and I closed it again :-(
