### ISSUE TITLE
eppy documentation on parallel processing missing?

### ISSUE THREAD

**Issue by nheeren** [santoshphilip/eppy#233]
In the eppy [documentation on parallel processing](https://eppy.readthedocs.io/en/latest/runningeplus.html#running-in-parallel-processes) it says: 

> The example here just creates 4 identical jobs apart from the output_directory the results are saved in, but you would obviously want to make each job different.

Am I missing something very obvious here or is the example somehow missing? Would this be easy to fix? 

Also the link to "View on Github" is dead. Is the documentation on readthedocs not being maintained anymore?

**Comment by santoshphilip** [comment]
@nheeren , I totally agree with your that the documentation is not up to snuff. Reading it right now, even I could not understand what it was saying. 
Take a look at the (closed) issue #210. Look towards the end of the comnent stream. See if that helps you to get started on runIDFs(). Post any comments here that can lead to improving the documentation.

I am not understanding what you mean when you say

> Also the link to "View on Github" is dead. Is the documentation on readthedocs not being maintained anymore?

On which page is this link "View on Github" ?

**Comment by nheeren** [comment]
Ok. Will have a closer look in that issue. Thank you!

Sorry for not being more precise before. Here a screenshot that should explain it:

![Screenshot 2019-04-01 at 22 10 37](https://user-images.githubusercontent.com/5136954/55356507-28233100-54cb-11e9-8bb5-abefaea1e8e8.png)

**Comment by santoshphilip** [comment]
That link "View" is:

        https://github.com/santoshphilip/eppy/blob/develop/home/docs/checkouts/readthedocs.org/user_builds/eppy/checkouts/latest/docs/source/conf.py/index.rst

something in readthedocs is generating that link. I am not sure how or what that is. I am considering it low priority at the moment.

Regarding the runIDF, also take a look the test code in https://github.com/santoshphilip/eppy/blob/develop/eppy/tests/test_runner.py

look at tests:

    def test_multiprocess_run_IDF(self):
    def test_multiprocess_run_IDF_from_generator(self):

This may give you a lead on how to get it working.

**Comment by santoshphilip** [comment]
updated documentation on how to run multprocess runs:

https://eppy.readthedocs.io/en/latest/runningeplus.html#Running-in-parallel-processes
