### ISSUE TITLE
List.extend() vs list comprehension

### ISSUE THREAD

**Issue by lymereJ** [santoshphilip/eppy#234]
Why does `type([idf_file.idfobjects[rule_type] for rule_type in ["GLOBALGEOMETRYRULES"]][0])` returns `eppy.idf_msequence.Idf_MSequence` but 
```
rule = []
for rule_type in ['GLOBALGEOMETRYRULES']:
    rule.extend(idf_file.idfobjects[rule_type])
print(type(rule[0]))
```
returns `geomeppy.patches.EpBunch`
The two methods seems similar, I don't understand why the type of object changes. What am I missing? I came across [this page](https://github.com/santoshphilip/eppy/blob/c04db34eec35fefc8c32d6336f2d4b42a87b9c94/docs/source/dev_docs/idf_msequence.rst) which was really helpful to understand the difference between the two types but I'm not sure why the type changes whether a  `.extend` or a list comprehension is used. What am I missing? Thanks!

**Comment by santoshphilip** [comment]
I'll take a look. 
It's been a while since I worked on that part of the code, but I think I know what is going on

**Comment by santoshphilip** [comment]
@lymereJ , Take a look at the code snippets I have pasted below 
If I have understood your question corrrectly, this should explain what is happening
I am copying and pasting from my ipython console. So you can see the outputs too.


Start

    In [2]: %paste
    idf = idf_file
    rule_type = 'GLOBALGEOMETRYRULES'
    ## -- End pasted text --


grules and grule are different types

    In [3]: %paste
    ggrules = (idf.idfobjects[rule_type])
    ggrule = idf.idfobjects[rule_type][0]
    print type(ggrules)
    print type(ggrule)
    ## -- End pasted text --
    <class 'eppy.idf_msequence.Idf_MSequence'>
    <class 'eppy.bunch_subclass.EpBunch'>

With extend

    In [4]: %paste
    rule = []
    ggrules = (idf.idfobjects[rule_type])
    ggrule = idf.idfobjects[rule_type][0]
    rule.extend(ggrules)
    print type(rule[0])
    ## -- End pasted text --
    <class 'eppy.bunch_subclass.EpBunch'>

With append

    In [5]: %paste
    rule = []
    ggrules = (idf.idfobjects[rule_type])
    ggrule = idf.idfobjects[rule_type][0]
    rule.append(ggrules)
    print type(rule[0])
    ## -- End pasted text --
    <class 'eppy.idf_msequence.Idf_MSequence'>


difference between extend and append illustrated in a simple list

    In [6]: %paste
    l = []
    l
    l.extend([1,2,3])
    print l
    l = []
    l.append([1,2,3])
    print l
    ## -- End pasted text --
    [1, 2, 3]
    [[1, 2, 3]]


(I am using python2, so it is the old print statement.)

**Comment by lymereJ** [comment]
That makes a lot of sense, thank you!
