### ISSUE TITLE
Dropping legacy Python

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#240]
Given that Python 2 end of life is only 7 months away, we should probably consider dropping official support for legacy Python versions. Not saying we should actually do it, but certainly consider it.

Pros:
- speed up CI by reducing the number of versions to test against
- allow us to use newer features like f-strings, type hints, and `Pathlib`
- remove ugly compatibility workarounds with `six`

Cons:
- some users may be stuck using legacy Python

I think you can see which way I'm leaning, but maybe I'm missing some other cons.

**Comment by santoshphilip** [comment]
I am comfortable moving to python3. 
This is an odd thing to say, but one of the issues with eppy is that, "It simply works". So we don't hear back from people who are using it. 

It would be good to hear back from other users (stake holders) see if we are missing anything. I see a couple of ways of doing that:

- bldg-sim@lists.onebuilding.org
- EnergyPlus_Support@yahoogroups.com
- unmethours - seems like the wrong forum to raise this question
- a twitter poll

We could phrase this as a question or as an announcement and look for feedback. 
as a bonus, we'll get a sense of who is using eppy

Alternatively we  simply move to python3 without putting too much thought into it :-). The justification for this is the end of life of python2

**Comment by santoshphilip** [comment]
I am inclined to do the following:

- make an announcement that we are moving to python3 on future versions of eppy on:
    - bldg-sim@lists.onebuilding.org
    - EnergyPlus_Support@yahoogroups.com

Ask for feedback

Most likely we'll move to python3 at this point.

flagging @jasonglazer for any input

**Comment by jamiebull1** [comment]
Agreed that an announcement/request for comments would be a good idea, and in the spirit of keeping the community involved. Also agree that this isn't really an UnmetHours type of question.

Half-way house option would be to continue to support a cross-platform version (bugfixes, responding to issues), but only add new features, changes for new EnergyPlus version compatibility) to the py3 version. Seems like that would be the worst of both worlds from a developer's point of view, but it may be what users want/need.

**Comment by santoshphilip** [comment]
closing this issue and reopening it in #287 

Maintaining python2 has become hard. Time to fully go to python3
