### ISSUE TITLE
Allow mixed case for specifying objects

### ISSUE THREAD

**Issue by JasonGlazer** [santoshphilip/eppy#242]
Currently getting objects requires using the form:

        objs = idf.idfobjects['ElectricEquipment'.upper()]

It would be convenient to just allow this form to work

        objs = idf.idfobjects['ElectricEquipment']

And apply this to all other functions that take an argument of the name of an object.

It looks like case insensitive dictionaries are described here:

https://stackoverflow.com/questions/2082152/case-insensitive-dictionary

**Comment by jamiebull1** [comment]
+1 from me. I've had this on my todo list for ages, right down to that StackOverflow post, but not got around to it!

**Comment by santoshphilip** [comment]
I am reluctant to change the default behavior of dict.
Having subclassed EpBunch from Munch (which is subclassed from dict), I have experienced how difficult it can be

When you have a bug, dict stops working and debugging was a nightmare, since it would start failing in mysterious ways
people will use EpBunch in ways we don't expect, meaning idf.idfobjects['ElectricEquipment'] is not the only thing the will do. 

For example they would do::

    # python 3 code
    if 'ElectricEquipment' in idf.idfobjects: 
        dosomething 

    # unlikely logic, but perfectly legal 
 
We have to make sure all use cases will work. I see sample code in that link that seems to cover all the cases, but I am not sure

I suggest a different strategy by adding syntactic sugar::

    objs = idf.friendly_idfobjects('ElectricEquipment') # of course we need a good name :-)

Here it is a function and we are not directly using a dict

**Comment by jamiebull1** [comment]
I've done some testing on this and added the best-looking implementation from that StackOverflow answer, along with a set of tests for the get, set, in, and del operations. It actually only needed swapping in in one place, `makebunches_alter`. Well, two if we count `makebunches` which we don't actually use in the codebase.

Nothing in the test suite breaks, but that's not exactly comprehensive. If either of you have any other ideas for weird and wonderful uses of dict then we can add tests for them too.

**Comment by santoshphilip** [comment]
I was just writing some code snippets for @JasonGlazer 
I have this line

    idf.newidfobject("BranchList".upper(), Name='Branchlist1')


would this line work with your updates (i see your pull request)


    idf.newidfobject("BranchList", Name='Branchlist2')

I think it would work. Now we have a key that is "BranchList", an older key that is "BRANCHLIST"
Is my understanding correct ?

**Comment by santoshphilip** [comment]
I did some tests with it.
My previous comment is incorrect

It does work correctly. The keys are always in caps.

**Comment by jamiebull1** [comment]
Yes, keys are all normalised to caps. Doesn't have to be that way. It's also possible to have them keep the case they were passed in with. There's an implementation of that in `requests` that we could replicate, but I lean towards keeping it simple, and all caps is the way it's been in `eppy` up to now.

**Comment by santoshphilip** [comment]
I agree about caps and keeping it simple

**Comment by santoshphilip** [comment]
I removed all the .upper() in the tests 
(most of the .upper() - some are needed for other reasons)

All test pass without the uppers()
I'll merge soon

**Comment by JasonGlazer** [comment]
Thanks @jamiebull1 and @santoshphilip! This has always been an annoyance.

**Comment by santoshphilip** [comment]
more thanks to @jamiebull1 
He did the heavy lifting

**Comment by santoshphilip** [comment]
this change has been merged into master.
I'll do a new release when I get a moment
