### ISSUE TITLE
Precision issue when using eppy on a Linux machine

### ISSUE THREAD

**Issue by lymereJ** [santoshphilip/eppy#246]
If I open an IDF file with `eppy` on a Linux machine and save it, some of the numeric fields get rounded up. I don't have this issue on Windows. Is this a Linux, `Python` or `eppy` issue?

Here's an example, the original content is:
```
People,
  FullServiceRestaurant Dining People,
  FullServiceRestaurant Dining,       
  RestaurantSitDown BLDG_OCC_SCH,     
  People/Area,                        
  ,                                   
  0.753473729169681,                  
  ,                                   
  0.3,                                
  ,                                   
  RestaurantSitDown ACTIVITY_SCH,     
  ,                                   
  ,                                   
  ,                                   
  ,                                   
  Work Efficiency Schedule,           
  ,                                   
  ,                                   
  Clothing Schedule,                  
  Air Velocity Schedule;              
```

Here's the content after being saved using `eppy` on Linux:
```
People,
  FullServiceRestaurant Dining People,
  FullServiceRestaurant Dining,
  RestaurantSitDown BLDG_OCC_SCH,
  People/Area,             
  ,                        
  0.75347372917,           
  ,                        
  0.3,                     
  ,                        
  RestaurantSitDown ACTIVITY_SCH,   
  ,                         
  ,                         
  ,                         
  ,                         
  Work Efficiency Schedule, 
  ,                         
  ,                         
  Clothing Schedule,        
  Air Velocity Schedule;    
```

`0.753473729169681` got changed to `0.75347372917`.

Any help would be greatly appreciated!

**Comment by santoshphilip** [comment]
@lymereJ , this may be coming from how computers handle floating point numbers. There is always a lack of precision there. (there are many answers in https://stackoverflow.com that speak about this). For example see https://stackoverflow.com/questions/21079282/increasing-floating-point-precision-in-python

It is also possible that the difference is coming form how eppy formats the output. I will have to look into the source code to be sure.


the difference between the two numbers is very small

    3.1896707497480747e-13

Too small to make a practical difference.

Having said that there are times it makes a difference. For instance if you are comparing two text (idf) files, they will show a difference on that line. 

It sounds like you have run into some such issue. Can you describe what that is ? There are ways to get greater precession with python such as using the Decimal type. We have not had the reason to do it so far

**Comment by jamiebull1** [comment]
This actually checks out as an issue. I wrote this test which passes on my machine but not anywhere else.
```
@pytest.mark.parametrize(["people"], [["0.753473729169681"], [0.753473729169681]])
def test_linux_rounding(base_idf, people):
    assert str(people) == "0.753473729169681"
    obj = base_idf.newidfobject(
        "People",
        Name="Test People",
        Number_of_People_Calculation_Method="People/Area",
        People_per_Zone_Floor_Area=people,
    )
    assert obj.People_per_Zone_Floor_Area == people
    idf = IDF()
    idf.initreadtxt(base_idf.idfstr())
    assert idf.idfstr() == base_idf.idfstr()
```

It looks like the only configurations that handle it without changing anything is py3.7 on mac or windows (my machine - there's something up with the CI for windows and 3.7 by the looks of it). Everything else either reduces the precision before even starting to touch eppy, or when writing the idfstr.

However, further to @santoshphilip 's comment about the negligible impact on calculations, I have a feeling I've read somewhere that EnergyPlus itself only reads the first x digits after the decimal point. Can't remember where I saw that though.

**Comment by lymereJ** [comment]
@santoshphilip, @jamiebull1 - thanks for getting back to me!

Here's a little bit more background. I have two IDF files that are identical except for a tiny difference (~1E-10) in equipment power density, it doesn't make any difference when running annual simulations but I am interested in Sizing Period simulations (winter and summer design days). There's pretty big differences in results for the winter design day: in the case where the EPD is approximated, the heat exchanger is bypassed thus reducing the heating energy use. This is really strange and I suspect that something is not right in EnergyPlus (checked all my inputs and AFAIK the only reason for the heat exchanger to be bypassed would be to have the air-side economizer on, which is not the case). The simulation results from these files are only used for comparison purposed, what really matters is that they be somewhat similar.

I tried using Python 3 as Jamie suggested and it fixed the problem.

**Comment by jamiebull1** [comment]
@lymereJ Seems like a big effect for a tiny difference. Since the issue doesn't arise in Python 3, and since Python 2 has less than 6 months till end-of-life, I'd suggest we call this one a `won't-fix`. Thoughts, @santoshphilip?

**Comment by santoshphilip** [comment]
I agree with @jamiebull1
