### ISSUE TITLE
error in parallel running

### ISSUE THREAD

**Issue by polinasali** [santoshphilip/eppy#253]
Hi,
I am new to python and eppy. I am trying to run files in parallel as an example before, but get an error, what is the format structure ? Can you please help?
`from eppy import modeleditor
from eppy.modeleditor import IDF
from eppy.runner import run_functions
modeleditor.IDF.setiddname('C:\EnergyPlusV8-9-0\Energy+.idd')
idfsourceFolder1 = "C:\Users\SALI5786\OneDrive Corp\OneDrive - Atkins Ltd\Desktop\energyplus\collection\output_idf1\Iteration-001"
idfname1 = "\2019-07-31_Change1.idf"
idfsourceFolder2 = "C:\Users\SALI5786\OneDrive Corp\OneDrive - Atkins Ltd\Desktop\energyplus\collection\output_idf1\Iteration-002"
idfname2 = "\2019-07-31_Change2.idf"
epwfile = full_path
jobs = []
for i in range(1):
jobs.append(
[
modeleditor.IDF(fname1.format(i), epwfile.format(i)),
modeleditor.IDF(fname2.format(i), epwfile.format(i))
{'output_directory': 'C:/Users/SALI5786/OneDrive Corp/OneDrive - Atkins Ltd/Desktop/energyplus'.format(i), 'ep_version': '8-9-0'}
]
)
run_functions.runIDFs(jobs, 1)`

error as syntax error on ep_version....:
 File "<ipython-input-102-567c3c7f12a6>", line 36
    {'output_directory': 'C:/Users/SALI5786/OneDrive Corp/OneDrive - Atkins Ltd/Desktop/energyplus'.format(i), **ep_version: 8-9-0}**
    ^
SyntaxError: invalid syntax

Thank you

**Comment by jamiebull1** [comment]
Hi @polinasali 

Thanks for opening this here. Looking at your code, there are a few issues to take care of. I've made changes and left comments where I've changed things. Let me  know if there are any things which are unclear, or if you hit any more errors.

```
import os

from eppy.modeleditor import IDF
from eppy.runner import run_functions

# here and below I removed `modeleditor` since it's not imported, and you already imported `IDF`
IDF.setiddname('C:/EnergyPlusV8-9-0/Energy+.idd')  # changed all \ to / to avoid character escaping problems
# define the parts of the file path
energyplus_folder = "C:/Users/SALI5786/OneDrive Corp/OneDrive - Atkins Ltd/Desktop/energyplus"
idf_source_folder = "collection/output_idf1"
name_template = "Iteration-00{i}/2019-07-31_Change{i}.idf"  # the `{i}`s are substituted by `idfname.format(i=i)` later
# then join the parts together
idfname = os.path.join(
    energyplus_folder,
    idf_source_folder,
    name_template
)
# need to provide an .epw file path, for example
epwfile = "C:/EnergyPlusV8-9-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"
jobs = []
for i in range(1):
    # each time around the loop, we add a new job to the list of jobs
    jobs.append(
        [
            IDF(idfname.format(i=i), epwfile),  # substitution happens here
            # I removed the second IDF from here - we can only add one at a time
            {'output_directory': energyplus_folder, 'ep_version': '8-9-0'}
        ]
    )
# then finally we run the list of jobs, and the results come out in the energyplus_folder directory
run_functions.runIDFs(jobs, 1)
```

**Comment by polinasali** [comment]
Thanks you!
However i'm still getting an error
`from eppy.modeleditor import IDF
from eppy.runner import run_functions

IDF.setiddname('C:/EnergyPlusV8-9-0/Energy+.idd')
#ep folder
epf_folder = "C:/Users/SALI5786/OneDrive Corp/OneDrive - Atkins Ltd/Desktop/energyplus"
idf_source_folder = "collection/output_idf1"
of_folder = "Iteration-00{i}"
name_template = "2019-07-31_Change{i}.idf"

out_folder = os.path.join(
    epf_folder,
    idf_source_folder,
    of_folder,
    name_template
)

idfname = os.path.join(
    epf_folder,
    idf_source_folder,
    of_folder
)

epwfile = full_path

jobs = []
for i in range(1,4):
    jobs.append(
        [
            IDF(idfname.format(i=i), epwfile),
            {'output_directory': out_folder, 'ep_version': '8-9-0'}
        ]
    )
run_functions.runIDFs(jobs, 3)`

can you please look at this?
![image](https://user-images.githubusercontent.com/53047942/62612266-f8fc5080-b8fe-11e9-8b99-34b33747ccfa.png)
can you see the image with an error?

**Comment by polinasali** [comment]
thank you!
I changed it a bit, as I need results to be stored in the file host folder
there is no error, however the code doesn't seem to do what I thought it would
it creates a folder 00i with some results
![image](https://user-images.githubusercontent.com/53047942/62613390-45e12680-b901-11e9-8ec9-720057f3ff19.png)
the aim is to run a file from each folder and store results in  a corresponding folder
`from eppy.modeleditor import IDF
from eppy.runner import run_functions

IDF.setiddname('C:\\EnergyPlusV8-9-0\\Energy+.idd')

epf_folder = "C:\\Users\\SALI5786\\OneDrive Corp\\OneDrive - Atkins Ltd\\Desktop\\energyplus"
idf_source_folder = "collection\\output_idf1"
of_folder = "Iteration-00{i}"
name_template = "2019-07-31_Change{i}.idf"

out_folder = os.path.join(
    epf_folder,
    idf_source_folder,
    of_folder,
    
)

idfname = os.path.join(
    epf_folder,
    idf_source_folder,
    of_folder,
    name_template
)

epwfile = full_path

jobs = []
for i in range(1,5):
    jobs.append(
        [
            IDF(idfname.format(i=i), epwfile),
            {'output_directory': out_folder, 'ep_version': '8-9-0'}
        ]
    )
run_functions.runIDFs(jobs, 5)`

can you please have look
Regards,
Polina

**Comment by jamiebull1** [comment]
You also need to use `format` on the output directory in the loop:

    {'output_directory': out_folder.format(i=i), 'ep_version': '8-9-0'}

**Comment by polinasali** [comment]
oh yeah, it worked! Thank you very much for your help and such a quick reply!

**Comment by jamiebull1** [comment]
Glad to help. All the best with python and eppy, and we're here if you need help.
