### ISSUE TITLE
running sim loop with idf.run() 

### ISSUE THREAD

**Issue by MaheshJayachander** [santoshphilip/eppy#255]
Hi @santoshphilip , I have a small issue with running loops for `idf.run() `and formatting the output file  .
I have attached code for example, 

`from eppy import modeleditor

from eppy.modeleditor import IDF

IDF.setiddname('C:\EnergyPlusV9-1-0\Energy+.idd')

epwfile = r"C:\EnergyPlusV9-1-0\WeatherData\USA_FL_Tampa.Intl.AP.722110_TMY3.epw"

idf01 = IDF(r'C:\Users\Mahesh Jayachander\Documents\Python Scripts\eppy\jupyter output_2\test01.idf', epwfile)

glazing_conductivity = [0.5, 0.6, 0.7, 0.8, 0.9]

glazing_names = ['0.5cond', '0.6cond', '0.7cond', '0.8cond', '0.9cond']

for i in glazing_conductivity:
        idf01.idfobjects['windowmaterial:glazing'][0].Conductivity = i
	for n in glazing_names :
		idf01.saveas(n + '.idf')
	idf01.run()`

Now my output is saved as one singular file under the name of eplusout.audit etc etc, rather than multiple files under the name of (n +'idf'), 
please help me out here with this silly one.
Thanks.

**Comment by jamiebull1** [comment]
@MaheshJayachander you can pass a different `output_directory` parameter to `idf.run()` each time around the loop which will then save the outputs to a directory. It might also be causing problems having dots in the file path, so maybe replace them with underscores.

Something like:

```
glazing_conductivity = [0.5, 0.6, 0.7, 0.8, 0.9]
glazing_names = ['0_5cond', '0_6cond', '0_7cond', '0_8cond', '0_9cond']
for cond, name in zip(glazing_conductivity, glazing_names):
        idf01.idfobjects['windowmaterial:glazing'][0].Conductivity = cond
	idf01.saveas(name + '.idf')
	idf01.run(output_directory=name)
```

**Comment by MaheshJayachander** [comment]
Perfect . Thank you soo much @jamiebull1 .
