### ISSUE TITLE
IDD file EnergyPlus v9-1-0

### ISSUE THREAD

**Issue by fabiamiorelli** [santoshphilip/eppy#259]
I am trying to run EnergyPlus v9-1-0 from Spyder (3.3.6) using eppy. When running a simulation I am getting a FileNotFoundError which I assume is due to a wrong version of the IDD file (Energy+V9_0_1.idd). Is there a v9-1-0 IDD file available? Is yes, where can I find it?
Thank you for any help you can provide!

**Comment by santoshphilip** [comment]
In general the IDD file will be found in the install folder of Energyplus. Usually the file  is called Energy+.idd.
On my Mac it is located at
`/Applications/EnergyPlus-9-1-0/Energy+.idd`


If it still does not work, post your code snippet where you open the file. It will help to debug your script.

**Comment by fabiamiorelli** [comment]
I was looking for the IDD in the eppy package resources folder, instead of the EnergyPlus folder. Now it works perfectly!
Thank you very much for your help!
