### ISSUE TITLE
Regarding parametric run

### ISSUE THREAD

**Issue by MaheshJayachander** [santoshphilip/eppy#266]
Hi @santoshphilip , I have been trying to run a paramteric sim with varying shgc values , but ending up with errors, coudnt solve this issue, please help me out here.

I have attached the code

[issue_santhoshphilip.txt](https://github.com/santoshphilip/eppy/files/3717914/issue_santhoshphilip.txt)

the below is the error I am facing

C:\EnergyPlusV9-1-0\energyplus.exe --weather C:\Users\Mahesh Jayachander\Documents\MBEP\WBD\sims and energy model\eppy parametric sims\IND_Mumbai.430030_ISHRAE.epw --output-directory C:\Users\Mahesh Jayachander\Documents\MBEP\WBD\sims and energy model\eppy parametric sims --idd C:\EnergyPlusV9-1-0\Energy+.idd C:\Users\Mahesh Jayachander\Documents\MBEP\WBD\sims and energy model\eppy parametric sims\in.idf

---------------------------------------------------------------------------
CalledProcessError                        Traceback (most recent call last)
C:\ProgramData\Anaconda3\lib\site-packages\eppy\runner\run_functions.py in run(idf, weather, output_directory, annual, design_day, idd, epmacro, expandobjects, readvars, output_prefix, output_suffix, version, verbose, ep_version)
    325             print("\r\n" + " ".join(cmd) + "\r\n")
--> 326             check_call(cmd)
    327         elif verbose == 'q':

C:\ProgramData\Anaconda3\lib\subprocess.py in check_call(*popenargs, **kwargs)
    346             cmd = popenargs[0]
--> 347         raise CalledProcessError(retcode, cmd)
    348     return 0

CalledProcessError: Command '['C:\\EnergyPlusV9-1-0\\energyplus.exe', '--weather', 'C:\\Users\\Mahesh Jayachander\\Documents\\MBEP\\WBD\\sims and energy model\\eppy parametric sims\\IND_Mumbai.430030_ISHRAE.epw', '--output-directory', 'C:\\Users\\Mahesh Jayachander\\Documents\\MBEP\\WBD\\sims and energy model\\eppy parametric sims', '--idd', 'C:\\EnergyPlusV9-1-0\\Energy+.idd', 'C:\\Users\\Mahesh Jayachander\\Documents\\MBEP\\WBD\\sims and energy model\\eppy parametric sims\\in.idf']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

UnsupportedOperation                      Traceback (most recent call last)
<ipython-input-146-86f63d03ca86> in <module>
      3     idf1.saveas(str(i) + 'SHGC.idf')
      4     fname = str(i) + 'SHGC.idf'
----> 5     idf1.run()

C:\ProgramData\Anaconda3\lib\site-packages\eppy\modeleditor.py in run(self, **kwargs)
   1012         epw = kwargs.pop('weather', self.epw)
   1013         try:
-> 1014             run(self, weather=epw, idd=idd, **kwargs)
   1015         finally:
   1016             os.remove('in.idf')

C:\ProgramData\Anaconda3\lib\site-packages\eppy\runner\run_functions.py in run(idf, weather, output_directory, annual, design_day, idd, epmacro, expandobjects, readvars, output_prefix, output_suffix, version, verbose, ep_version)
    328             check_call(cmd, stdout=open(os.devnull, 'w'))
    329     except CalledProcessError:
--> 330         message = parse_error(output_dir)
    331         raise EnergyPlusRunError(message)
    332     finally:

C:\ProgramData\Anaconda3\lib\site-packages\eppy\runner\run_functions.py in parse_error(output_dir)
    341     :return: str
    342     """
--> 343     sys.stderr.seek(0)
    344     std_err = sys.stderr.read().decode('utf-8')
    345     err_file = os.path.join(output_dir, "eplusout.err")

UnsupportedOperation: seek

**Comment by jamiebull1** [comment]
Hi @MaheshJayachander . This is fixed in #264 which has been merged to `develop` but not yet released.

**Comment by santoshphilip** [comment]
@MaheshJayachander see if you can install from the develop branch (google to see how to do that with pip or other means).
It will take me a few days to do a new release

**Comment by MaheshJayachander** [comment]
sure @santoshphilip , I guess il wait for the update.
Thanks

**Comment by santoshphilip** [comment]
version r0.5.52 has been released

**Comment by MaheshJayachander** [comment]
Thanks a ton, @santoshphilip and @jamiebull1 . 
Got it running
