### ISSUE TITLE
Regarding setting up parametric run

### ISSUE THREAD

**Issue by MaheshJayachander** [santoshphilip/eppy#267]
Hi @jamiebull1 and @santoshphilip , I am currently trying to set up an parametric run with 4 different wall construction, 4 roof construction and 4 SHGC glazing variations. While setting up the parametrics from the sourced IDF where I have already made the construction and material in IDF editor. 
But when I try to loop the parameters int the BuildingSurface:Detailed & FenestrationSurface:Detailed , The loop does not assign the construction names into the IDF's .
It would be of great pleasure if you can help me out with this issue.

I have attached the code below.

[construction parametrics@jamiebull&@santhoshphilip.txt](https://github.com/santoshphilip/eppy/files/3788064/construction.parametrics%40jamiebull.%40santhoshphilip.txt)

**Comment by santoshphilip** [comment]
In your code you are mixing tabs and spaces for your indent.
this may be breading your code
in python, you should use either tabs or spaces, not both.

best practice is to use 4 spaces for an indent

**Comment by santoshphilip** [comment]
@MaheshJayachander did you get the code working ? I think it will work if you fix the tab and space  problem.

**Comment by MaheshJayachander** [comment]
Apologies for a late response.
ya i did @santoshphilip , the code has been running, but the changes I indent to make is not been achieved successfully.
That is for eg, I wanted to change the construction name of all the wall assemblies in BuildingSurface:Detailed to particular names of construction I had made, instead the code runs, but the IDF is not created properly according to my need. 
The parametric is 
4 wall assembly * 4 roof assembly * 4 shgc assembly 
If it is possible , can u run the code and see if the IDF's are being formed in the correct format, since I have not been able to achieve it so far.
Thanks a lot for your extended support.

**Comment by santoshphilip** [comment]
Can you post the code and a sample idf file 
You can use [github gist](https://gist.github.com) to do so

would be easier for me to check and respond

**Comment by MaheshJayachander** [comment]
Hi @santoshphilip , I have posted the code 
link for code - [https://gist.github.com/MaheshJayachander/e11e2c3e4f2f91f0e4c56f45939d68d4](url) 

zip of the idf file - [parametric run idf.zip](https://github.com/santoshphilip/eppy/files/3800166/parametric.run.idf.zip)

**Comment by santoshphilip** [comment]
found a quick error in the tail end of your code.
Have not checked for other issues:

your code is :

    for s, wn in zip(srf, wallnames):
        if s.Outside_Boundary_Condition == 'Outdoors':
            if s.Surface_Type == 'Wall':
                s.Construction_Name = wn
            
                for sr, rn in zip(srf, roofnames):
                    if sr.Outside_Boundary_Condition == 'Outdoors':
                        if sr.Surface_Type == 'Roof':
                            sr.Construction_Name = rn                      
                        
                            for gs, gn in zip(gsrf, glazingnames):
                                gs.Construction_Name = gn
                            
                                idf01.saveas(wn + rn + gn + '.idf')
                            
it should be:

    for s, wn in zip(srf, wallnames):
        if s.Outside_Boundary_Condition == 'Outdoors':
            if s.Surface_Type == 'Wall':
                s.Construction_Name = wn
            
        for sr, rn in zip(srf, roofnames):
            if sr.Outside_Boundary_Condition == 'Outdoors':
                if sr.Surface_Type == 'Roof':
                    sr.Construction_Name = rn                      
                
            for gs, gn in zip(gsrf, glazingnames):
                gs.Construction_Name = gn
            
                idf01.saveas(wn + rn + gn + '.idf')
                print("saving", wn + rn + gn + '.idf')
