### ISSUE TITLE
idf.run() error when changing idf file

### ISSUE THREAD

**Issue by fabiamiorelli** [santoshphilip/eppy#271]
I am trying to run EnergyPlus v9-1-0 from Spyder (3.3.6) using eppy. After opening my Python script, the first E+ simulation I run through eppy works properly. After I modify any E+ fields (such as constructions) in the same IDF file or try to run a different IDF file than the first one I ran, I keep getting the results of the very first simulation run. If I save a new IDF through idf.saveas() and then open it directly in E+ and run it from there everything works properly and all changes I made to the IDF file are there. It seems as if the first IDF that is imported through eppy is kept in memory.
Any suggestions as to what could cause this? 
Thank you in advance for any help you can provide!

**Comment by santoshphilip** [comment]
I think I understand what you are saying. The behavior you are describing is unexpected. 

Can you restate the issue with some example code snippets - illustrating with code that worked and code did not work. I may able to see what is going wrong.

**Comment by fabiamiorelli** [comment]
@santoshphilip, thank you very much for your prompt answer!
The code is always running without throwing errors, but it looks as if the results (I am interested in heating and cooling demand from the eplusout table and meters) were not updated when I change input IDF file to a simulation run, I keep seeing the same results as the first IDF that is run. The same thing happens when keeping the same IDF file and changing u values in the construction objects, whereas I would expect heating and cooling demand to change. I created a function to change the u values, verify there are not duplicate objects that would cause severe errors, run the E+ simulation and store results in a df. I attach the python code I am using for you to see if it is obvious what the issue is.
Thank you for your help!
[github_code_issue_eppy.zip](https://github.com/santoshphilip/eppy/files/4103228/github_code_issue_eppy.zip)

**Comment by fabiamiorelli** [comment]
Is there maybe a way to clear the idf after a simulation run? Or maybe the issue is assigning and running the idf within a function?

**Comment by santoshphilip** [comment]
I am going to update the documentation with examples of doing the runs.
I'll use the issue here as a way to shape the documentation 

If there is a bug in eppy, I'll run into it while testing the demo scripts. Then I'll fix it. 
Sorry this is taking longer than anticipated.

**Comment by santoshphilip** [comment]
I wrote a quick script where I change the run period.

- first run is from Jan-Dec
- second run is only for Jan

The outputs change for each run. See the script below


    # python3 code
    import eppy

    idfname = "1ZoneEvapCooler.idf" # from example folder
    epwname = "USA_CO_Denver-Stapleton.724690_TMY.epw" # downloaded from E+ site
    idf = eppy.openidf(idfname, epw=epwname) # easy way to open an idf
    idf.run()

    from eppy.results import readhtml
    htmfile = "eplustbl.htm"
    filehandle = open(htmfile, 'r').read() # get a file handle to the html file


    htables = readhtml.titletable(filehandle) # reads the tables with their titles
    gjoules1 = htables[0][1][1][1] 

    runperiod = idf.idfobjects["runperiod"][0]
    runperiod.End_Month = 1 # run period for only January.
    idf.run()

    htmfile = "eplustbl.htm"
    filehandle = open(htmfile, 'r').read() # get a file handle to the html file
    htables = readhtml.titletable(filehandle) # reads the tables with their titles
    gjoules2 = htables[0][1][1][1] 
    assert gjoules1 != gjoules2
    print('**************************************************')
    print(f'total energy from 1st run = {gjoules1} GigaJoules')
    print(f'total energy from 2nd run = {gjoules2} GigaJoules')
    print('**************************************************')


output is 

    **************************************************
    total energy from 1st run = 42.85 GigaJoules
    total energy from 2nd run = 8.47 GigaJoules
    **************************************************

I have not looked at your code in detail
Can you see why it is not working as expected ?

**Comment by fabiamiorelli** [comment]
Thanks for your help on this, I really appreciate it! 
I looked into it but unfortunately I am not able to identify where the issue comes from exactly. Something else I noticed was that if I modify IDF fields and then save the new/updated IDF and run it directly from E+ everything works fine and the results are updated/change accordingly to the changes I made to the IDF. But if I run the same IDFs one after the other in a for loop in a Python script the results both in Python and in the .mtr or .tbl files in the directory always reflect the results of the first simulation that is run and, to be able to get different results, I need to close my Python console and start it again. Basically, if I ran the IDFs individually it works but I still need to close Spyder in between and when I place them in a for loop to run different IDFs (or the same IDF while changing some objects in it) it does not work.

That’s why I had the impression that it is as if the first idf that is read/run (not sure which of the two options makes the difference in this case) is somehow kept in memory. I am trying to see if a forced quit of E+ from Python might prevent this from happening. I cannot understand whether the problem is that a change in the IDF is not possible once an IDF is read without closing my Python interpreter or maybe that the results are simply not updated for some reason.

**Comment by jamiebull1** [comment]
I've noticed similar behaviour before and not managed to get to the root of
it. I seem to recall my workaround was to create a new directory for each
run, though I can't guarantee that will work.

@santoshphilip I'm afraid I have no time at all for helping out with this
at the moment, but maybe the workaround above might point you in a useful
direction?

**Comment by santoshphilip** [comment]
@fabiamiorelli , Can you try and run the script I used [above](https://github.com/santoshphilip/eppy/issues/271#issuecomment-579935752). Make any changes needed to get it to run in your environment.

Let me know how it succeeds or fails. It may give us some insight into what is going on.

@jamiebull1 , good to hear your comment that you may have run into this problem. Let me see what I can find out.

**Comment by santoshphilip** [comment]
fixed issue #302 
Now we have documentation on the doing multi-runs
