### ISSUE TITLE
Simultaneous runs broken under windows

### ISSUE THREAD

**Issue by mwilsoncea** [santoshphilip/eppy#273]
I'm trying to run multiple runs within eppy as discussed[ here](https://unmethours.com/question/38548/simultaneously-run-a-number-of-independent-energyplus-simulations-on-multiple-cores-on-linux-via-a-script/?answer=38572#post-id-38572):

I've tried the test units code in the link, stripped down, and I'm still getting an error message that throws Windows under the bus. Is this a Linux only feature? 

Code:

import sys
import os
pathnameto_eppy = '../'
sys.path.append(pathnameto_eppy)
from eppy import modeleditor
from eppy.modeleditor import IDF
from eppy.runner.run_functions import runIDFs
iddfile = "../eppy/resources/Energy+.idd"
fname1 = "../eppy/resources/Example1.idf"
epwfile = r"C:\EnergyPlusV9-1-0\WeatherData\USA_UT_Salt.Lake.City.Intl.AP.725720_TMY3.epw"
num_CPUs = 2
IDF.setiddname(iddfile)
#trying to run multiple idf files at a time
#idfsToRun = [fname1, r"C:\testoutput"]
idfsToRun = (
            (modeleditor.IDF(open(fname1, 'r'), epwfile),
             {'output_directory': 'results_%i' % i, 'ep_version': ep_version})
            for i in range(4)
        )
runIDFs(idfsToRun, num_CPUs)

Which produces the error:
'RuntimeError:
            Attempt to start a new process before the current process
            has finished its bootstrapping phase.

            This probably means that you are on Windows and you have
            forgotten to use the proper idiom in the main module:

                if __name__ == '__main__':
                    freeze_support()
                    ...

            The "freeze_support()" line can be omitted if the program
            is not going to be frozen to produce a Windows executable.

**Comment by jamiebull1** [comment]
You have no main method, like the error message says.

Details here https://stackoverflow.com/a/419185/1706564

Edit your code to be set up like this:

    # your imports here

    def main():
         # your script code here
         ...

    if __name__ == '__main__':
        main()

**Comment by mwilsoncea** [comment]
Ah, my bad then. Thanks a bunch for the help. Here is the working code for posterity:
```
import sys
import os

pathnameto_eppy = '../'
sys.path.append(pathnameto_eppy)

from eppy import modeleditor
from eppy.modeleditor import IDF
from eppy.runner.run_functions import runIDFs

def main():
        iddfile = "../eppy/resources/Energy+.idd"
        fname1 = "../eppy/resources/Example1.idf"
        TEST_EPW = r"C:\EnergyPlusV9-1-0\WeatherData\USA_UT_Salt.Lake.City.Intl.AP.725720_TMY3.epw"
        modeleditor.IDF.setiddname(iddfile)
        ep_version = "9-1-0"
        runs = []
        for i in range(2):
            runs.append(
                [
                    modeleditor.IDF(open(fname1, "r"), TEST_EPW),
                    {"output_directory": "results_%i" % i, "ep_version": ep_version},
                ]
            )
        num_CPUs = 2
        print(*runs)
        runIDFs(runs, num_CPUs)
if __name__ == '__main__':
    main()```
