### ISSUE TITLE
Do I have ways to directly get outputs from python instead of reading from html files?

### ISSUE THREAD

**Issue by 906476903** [santoshphilip/eppy#279]
Do I have ways to directly get outputs from python instead of reading from html files? Because read from file is relatively slow and can we get the outputs just like the returned value of idf.run()? (for example through the socket?)

Thanks.

**Comment by santoshphilip** [comment]
You still have to read the output from the disk. If you don't read the html file, you have to read something else. What file are you thinking of reading. The E+ simulation writes all outputs to the disk. You can send the output thru a socket once you read it, but you still have to read it

I agree that the html file read is really slow on large files. I wrote some functions that read it faster. Let me see if I can dig it up and add it to eppy. I think it is on my office machine. It may be hard to get to it during this lockdown.

**Comment by santoshphilip** [comment]
couple of developments:

- I have tracked down the code that does the fast read of the html file. I'll include it in eppy (I'll open a new issue on this)
- I am developing and experimental function `runandget(idf, result_selector)` which will run a simulation on idf file and return selected results. This is being developed for use in [zeppy](https://github.com/pyenergyplus/zeppy). This is issue #317 

I am going to close this issue and follow up in the other issues
