### ISSUE TITLE
problem running idfdiff.py

### ISSUE THREAD

**Issue by milagrossanz** [santoshphilip/eppy#280]
Hello! I've been working with eppy for a couple of months now but it seems I'm doing something wrong while trying to use the script "idfdiff". I opened the file in Jupyter Notebook and changed the path to file1, file2 and idd, but I still get the following error:

```
usage: ipykernel_launcher.py [-h] [--idd IDD] (--csv | --html) file1 file2
ipykernel_launcher.py: error: the following arguments are required: file2

An exception has occurred, use %tb to see the full traceback.

SystemExit: 2

C:\Users\Milagros\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3334: UserWarning: To exit: use 'exit', 'quit', or Ctrl-D.
  warn("To exit: use 'exit', 'quit', or Ctrl-D.", stacklevel=1)
```

Any idea what I'm doing wrong?
Thank you so much in advance.

**Comment by santoshphilip** [comment]
Let me take a look.
I have never tried it within Jupyter notebook. So I am not sure what is going on yet.

**Comment by santoshphilip** [comment]
Can you show me the actual line you ran
that gave those error messages

**Comment by milagrossanz** [comment]
I actually copied the code from the file idfdiff.py in useful_scripts folder and worked on it. But the problem seems to be from this point on: 

```
if __name__ == "__main__":
    # do the argparse stuff
    parser = argparse.ArgumentParser(usage=None, description=__doc__)
    parser.add_argument(
        "file1",
        action="store",
        help="C:/Users/Milagros/Documents/eppy-0.5.52/eppy-master/eppy/resources/idffiles/V_7_2/constructions.idf",
    )
    parser.add_argument(
        "file2",
        action="store",
        help="C:/Users/Milagros/Documents/eppy-0.5.52/eppy-master/eppy/resources/idffiles/V_7_2/constructions_diff.idf",
    )
    parser.add_argument(
        "--idd",
        action="store",
        help="C:/Users/Milagros/Documents/eppy-0.5.52/eppy-master/eppy/resources/iddfiles/Energy+V7_2_0.idd",
    )
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--csv", action="store_true")
    group.add_argument("--html", action="store_true")
    nspace = parser.parse_args()
    fname1 = nspace.file1
    fname2 = nspace.file2
    iddfile = nspace.idd
    IDF.setiddname(iddfile)
    idf1 = IDF(fname1)
    idf2 = IDF(fname2)
    dtls = idf1.model.dtls  # undocumented variable
    thediffs = idfdiffs(idf1, idf2)
    csvdiffs = makecsvdiffs(thediffs, dtls, idf1.idfname, idf2.idfname)
    if nspace.csv:
        printcsv(csvdiffs)
    elif nspace.html:
        printhtml(csvdiffs)

```

The previous lines run perfectly.

**Comment by santoshphilip** [comment]
I made a new branch `i280_idfdiff`
I made some changes to `idfdiff.py` in that branch

Switch to that branch and run the following code in `jupyter notebook`. 

- the pathnames in the code assume that you are in eppy root directory
- It also assumes that you have E+ 7.2 installed 
- You can try with some other files for whatever E+ version you have installed
- the code will display the html table in your `jupyter notebook` window

Code tested in python3::

    import eppy
    from eppy.useful_scripts import idfdiff
    fname1 = './eppy/resources/idffiles/V_7_2/constr.idf'
    fname2 = './eppy/resources/idffiles/V_7_2/constr_diff.idf'
    idf1 = eppy.openidf(fname1)
    idf2 = eppy.openidf(fname2)

    # --- the diff stuff happens below
    thediffs = idfdiff.idfdiffs(idf1, idf2)
    csvdiffs = idfdiff.makecsvdiffs(thediffs, idf1, idf2)
    csvtxt = idfdiff.makecsv(csvdiffs)
    print(csvtxt)
    soup = idfdiff.makehtmlsoup(csvdiffs)
    print(soup)
    idfdiff.htmlinnotebook(soup)

Let me know how it goes. If it looks good, I'll merge into the main branch and release at some point. (this may also call for an update in the idfdiff documentation)

**Comment by santoshphilip** [comment]
aargh .... unit tests are failing :-(

the code I have written above should still work.

**Comment by milagrossanz** [comment]
wow, thank you so much for the quick reply @santoshphilip. 
I've tried running the code you posted, but now the error is:

`TypeError                                 Traceback (most recent call last)
<ipython-input-4-be0df9434931> in <module>
      8 # --- the diff stuff happens below
      9 thediffs = idfdiff.idfdiffs(idf1, idf2)
---> 10 csvdiffs = idfdiff.makecsvdiffs(thediffs, idf1, idf2)
     11 csvtxt = idfdiff.makecsv(csvdiffs)
     12 print(csvtxt)

TypeError: makecsvdiffs() missing 1 required positional argument: 'n2'`

well, actually the argument that is missing is 'dtls' since makecsvdiffs(thediffs, dtls, n1, n2), right?

**Comment by milagrossanz** [comment]
wow, thank you so much for your help and quick response @santoshphilip ! it worked perfectly now!! 

I'm a little curious why this error occurred, though. what would you recommend that I use instead of Jupyter Notebook to avoid future errors when reading the scripts? work directly in the python interpreter?

thanks again for your help!

**Comment by santoshphilip** [comment]
I changed the code so that `makecsvdiffs` is different and takes only 3 args (does not need  `dtls`). This is in branch `i280_idfdiff`.

You need to switch to that branch. (now you need to figure out how to use a different branch. See if you can google a bit and figure it out)

I just noticed that you said it 'did not work' and then you said 'it worked'. So 'did it ?'

Regarding your question on `jupyter notebook`. You should continue using notebooks. It is a superb environment to experiment and figure out things. Almost everything should work in it. In fact most of the tutorial is written using notebook.

**Comment by milagrossanz** [comment]
I'm sorry, I thought I didn't send the first message, so I deleted it so others don't get confused. it did work! 

and I'll continue working with notebooks, then. thanks!
