### ISSUE TITLE
pytest are failing in master branch

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#281]
Something has changed .... try rolling back to find a non-failing release

**Comment by jamiebull1** [comment]
Issues:

`pyparsing` version needs pinning for py2 installation

>As of pyparsing 2.0.0, Python 2 is no longer supported, so we need to set an upper limit for the range of versions installable by pip.

https://github.com/matplotlib/matplotlib/pull/1794

`black` needs running on the changed files.
```
6.35s$ black --check --exclude venv .
would reformat /home/travis/build/santoshphilip/eppy/docs/Outputs_Tutorial.py
would reformat /home/travis/build/santoshphilip/eppy/docs/Main_Tutorial.py
would reformat /home/travis/build/santoshphilip/eppy/eppy/useful_scripts/idfdiff.py
Oh no! 💥 💔 💥
3 files would be reformatted, 105 files would be left unchanged.
The command "black --check --exclude venv ." exited with 1.
```

**Comment by santoshphilip** [comment]
good catch.
I'll follow up and fix it.

I should have listened to you when you suggested depreciating python 2 version of eppy back in December

**Comment by santoshphilip** [comment]
It is failing with pyparsing 1.5 in python2
It is failing in python3

The problem is somewhere else. Some observations
- fails on Travis when pushed to GitHub
- fails on my laptop in python2 and python3
- failure may be due to some setting in virtualenv or on the computer (OS has been updated)

Possible directions for investigation
- try and find a machine on which this still passes
- track it back from the failure message and see if you can fix it

**Comment by santoshphilip** [comment]
Continuing investigation

Found a machine on which eppy passes tests
- passes tests on office desktop
- pip freeze from office desktop
    - install pip freeze output on laptop in a new virtualenv
- fails on laptop in new virtualenv
- try it on home desktop that has an older OS
    - install pip freeze output from "office desktop" on "home desktop" in a new virtualenv
- fails on "home desktop" in new virtualenv

**Comment by jamiebull1** [comment]
Have you tried in conda? I had a look yesterday, and the errors on CI are related to pyparsing versions, but I couldn't find a version that satisfied everything

**Comment by santoshphilip** [comment]
Ok ... I think I untangled the web of dependencies and got it to pass
This is in branch `i281_failtest_alter`

See Travis-cl at
https://travis-ci.org/github/santoshphilip/eppy/builds/695746292

fixing the dependencies took me 7 hours grrr ... 


There was a test that was failing. Took me a while to track it and fix (with 2 lines of code :-(

**Comment by santoshphilip** [comment]
now merged into develop
