### ISSUE TITLE
azimuth calculation considering building orientation

### ISSUE THREAD

**Issue by airallergy** [santoshphilip/eppy#282]
It seems that the current calculation of the surface azimuth does not consider the **North Axis** field in the **Building** Object, wouldn't it be more reasonable to take the user-defined orientation into account?

**Comment by santoshphilip** [comment]
you are right. Unfortunately when it was written (long ago), we didn't think about it..
I don't want to change that function, since it might break code that people have written, and are depending on.

It would be best to write another function, that would work as you described. If you write it, I'll include it in eppy.

**Comment by santoshphilip** [comment]
Let me know if you can write it. I'll tell you where to put it.

**Comment by airallergy** [comment]
Yes, I can certainly try, please do show me. Also, if there's anything else, like variable naming preferences etc., kindly let me know.

**Comment by santoshphilip** [comment]
I need to re-frame the issue so that you don't have to deal with some of the innards of eppy. Give me a couple of days to do that.

**Comment by airallergy** [comment]
Sure thing, take your time, and let me know when you are done.

**Comment by santoshphilip** [comment]
to recap

Surface.azimuth = gives the azimuth of the surface based on it's coordinates only

We need another function

surface.true_azimuth = gives the azimuth based on surface.azimuth and building.North_Axis. There may be other factors to take into account, but we will ignore them for now

to do this we need a function

true_azimuth(building_north_axis, surface_azimuth)

I have opened a new issue #283 for this function and assigned it to @airallergy. The details are in that issue  at #283
