### ISSUE TITLE
surface.azimuth does not take into account the building.North_Axis

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#283]
problem: surface.azimuth does not take into account the building.North_Axis

As a step to resolving this issue, we need a function

    def true_azimuth(building_north_axis, surface_azimuth)
        # return "the azimuth based on surface.azimuth and building.North_Axis"

The location of this function should be 

- eppy
    - geometry
        - surface.true_azimuth
        
The unit tests should be in

- eppy
    - tests
        - test_surface.py

This issue is assigned to @airallergy

@airallergy, see https://github.com/santoshphilip/eppy/blob/master/CONTRIBUTING.md and use the second method where you fork the repository and then do a pull request

**Comment by santoshphilip** [comment]
This issue has been opened to resolve issue #282

**Comment by santoshphilip** [comment]
@airallergy, I don't know how experienced you are with contributing code. If you are unfamiliar with any of the steps like `forking, pull request or testing (using pytest)`, post you question here and I'll help out.

**Comment by airallergy** [comment]
will do if I have queries, cheers @santoshphilip

**Comment by airallergy** [comment]
@santoshphilip, I wonder if I need to write only the two functions you mentioned above?

if this is the case, I wonder if the two inputs (building_north_axis, surface_azimuth) are both numbers? Do I need to do something to check if there is a given building north axis otherwise set default to 0?

**Comment by santoshphilip** [comment]
@airallergy,  did you post and delete a comment ?I see it in my email, but not on GitHub.
Just checking.

**Comment by airallergy** [comment]
@santoshphilip, yes I did delete a comment which is no long my questions. sorry about the confusion.

I think I have done the changes to address the issue now, could you walk me through how I should pull request? I forked, created a new branch from develop, did changes, committed locally. Then I try to publish changes to upstream which is denied, I assume I need to pulish to my forked repo first, then do the pull request somehow?

**Comment by santoshphilip** [comment]
go to your forked copy on github at 
https://github.com/airallergy/eppy

- click on the tab "Pull Request" (it is on the top part of the page)
- once you are in that tab
    - click on the button "New pull request"
- from there it may be apparent how to do it 

If it does not come out right, we can delete it and do a new one

**Comment by santoshphilip** [comment]
This fixes the problem of `building.North_Axis`
But `true_azimuth` should also take into account `zone.Direction_of_Relative_North`

@airallergy , do you want to open it as a new issue ?

**Comment by airallergy** [comment]
@santoshphilip what's on your mind? I'm ok with either new issue/pull request, or just changes in the current one.

**Comment by santoshphilip** [comment]
It should be a new issue. This issue has been resolved and the pull request has been accepted

Reasoning behind opening it as a new issue:
- small incremental changes are easier in open source development. (we are strangers scattered across the planet contributing code)
- It makes it easier for you to contribute
- Equally important, it makes it easier for the maintainer (me) to accept
    - Maintainer will accept contribution (within 24-48 hours) if:
        1. Contribution resolves the issue as opened and discussed
        2. All tests pass
            - contribution is tested
            - does not break anything else
        3. code style meets PEP 8
 
If there are any further issues with the contribution, it will be opened as a new issue

**Comment by airallergy** [comment]
Thanks so much for the detailed explanation.
