### ISSUE TITLE
surface.true_azimuth does not take into account the zone.Direction_of_Relative_North

### ISSUE THREAD

**Issue by airallergy** [santoshphilip/eppy#285]
This issue has been opened to further address the issue of `surface.true_azimuth` discussed in #282 and #283, where `zone.Direction_of_Relative_North` has yet to be included in the calculation.

**Comment by airallergy** [comment]
A few thoughts:

1. I see some efforts have been made concerning the data type conversion during idf reading based on idd (#107 & #188), but there seems no conversion when inputting via eppy, say if I do
```python
idf.idfobjects['Building'][0].North_Axis = '20'
```
the value of the building north axis stays string.

2. Another issue would be the validity of numeric data. I took a look into the data conversion codes
```python
class ConvInIDD(object):
    ...

    def integer(self, x, y):
        try:
            return int(x)
        except ValueError as e:
            return x

    def real(self, x, y):
        try:
            return float(x)
        except ValueError as e:
            return x
```
I assume the original string is returned if cannot be converted to int or float is for the case when the data is optional and not given? but this would also allow something like `'20a'` to exist. The idf editor of ep refuses the input of such data (at least in v9.3.0, don't remember about previous versions), this validation could be an additional function of eppy in the future.

Users' judgement is highly relied on in terms of these two situations, either of which can cause the failure of `surface.true_azimuth`. Currently the true azimuth calculation only check if the data is empty string (meaning not given by users), because I think the data validation would be part of the data parsing component in eppy, if there should be one.

**Comment by santoshphilip** [comment]
`eppy` is not a user interface, but a scripting language for E+
In EP editor, the user can easily make a typo. It is less likely to happen in a scripting language

- I am not comfortable doing an error check as soon as the field is input (like EP editor does) for a number of reasons:
    - the code get's complicated where it doesn't need to.
    - it will slow eppy, because checks are done every time you change a field

I can see a use case for the following:
- check the entire idf file for field errors
- check an idfobject for field errors

That may be worth writing and maybe straightforward

**Comment by santoshphilip** [comment]
@airallergy , the code for this issue was nicely written. I learnt a few things from it. 
I liked how you used the `if` statement

    0 if building_north_axis == "" else building_north_axis

and your use of the `%` operator

    return (
        building_north_axis + zone_direction_of_relative_north + surface_azimuth
    ) % 360

I had to google to find out what `%` was doing. It was just the right operator for the situation.

I may make some minor changes to the code you wrote. I want to make the variable names slightly smaller, so that the lines format more easily and it is a little easier to read.  I'll put a comment here when I do that

**Comment by santoshphilip** [comment]
I just did the minor changes. You can see what I did if you compare commits

    3a74d119b8df40dfb708038fe85d8a3c978a6b55

and

    38cd9a7c58d61c66490f3c539582618746652d5e

**Comment by airallergy** [comment]
@santoshphilip, I do agree with your concerns about the performance if implementing value checks at every input, and this is not something urgent to be addressed as far as I understand the main purpose of `eppy`. I brought this up mainly in the intention to leave it as a reference in case anyone might encounter with such issues, given that many of the `eppy` users are not expected to have much programming knowledge.

Actually, since `IDF.run` will save an intermediate idf file before calling ep, inputs like `"20"` probably won't be an error for ep, but only affect built-in functions like `azimuth`; those like `"20a"` are more of an ep's responsibility to check during its running to my understanding. In all, value checks might be a bonus, but definitely not an essential.

And also, thanks for the simplification of variable names.

**Comment by santoshphilip** [comment]
On a different note, the field names in the following object may affect `true_azimuth`.

        GlobalGeometryRules,
            UpperLeftCorner,         !- Starting Vertex Position
            CounterClockWise,        !- Vertex Entry Direction
            World;                   !- Coordinate System

Especially the line `World;                   !- Coordinate System`. 
Can you look into the documentation and see if this has an impact ? Open a new issue if needed

**Comment by airallergy** [comment]
Well spotted! I will look into it and run some tests in a few days.
