### ISSUE TITLE
GlobalGeometryRules for the surface azimuth calculation

### ISSUE THREAD

**Issue by airallergy** [santoshphilip/eppy#292]
This is an issue initiated by @santoshphilip in #285 

Five fields in `GlobalGeometryRules`: `Starting Vertex Position`, `Vertex Entry Direction`, `Coordinate System`, `Daylighting Reference Point Coordinate System`, `Rectangular Surface Coordinate System`.

`Starting Vertex Position` actually relates to `surface.azimuth` instead of `surface.true_azimuth`. This field seems not to matter too much as long as the surface vertices order matches `Vertex Entry Direction` in EP. I am not quite familiar with the azimuth calculation algorithm in `eppy`, but intuitively, it is the chirality rather than the starting position that determines the azimuth calculation. @santoshphilip please clarify this bit algorithm.

`Vertex Entry Direction` also relates to `surface.azimuth`, and an unmatched value with the surface vertices chirality will give an exactly opposite azimuth output. But I think this is something beyond the scope of the azimuth calculation. This is a surface definition problem.

`Coordinate System` indeed impacts `surface.true_azimuth` and needs to be addressed.

The last two seems not relevant to my understanding.

**Comment by santoshphilip** [comment]
I had to google the word `chirality`. :-)

Yes. As you said `Vertex Entry Direction` also relates to` surface.azimuth`
`surface.azimuth` does not take that into account.  This is my understanding from a quick look at the code
Let us treat that as a separate issue and ignore it here in this issue.

You are tight about `Daylighting Reference Point Coordinate System, Rectangular Surface Coordinate System` not being relevant to this issue either.

You are on the right track

**Comment by santoshphilip** [comment]
I have reorganized the folder structure in the `develop` branch. The `tests` folder is not in `eppy` folder. It is outside the `eppy` folder. 

so the folder structure looks like::

    - tests
        - test_*.py
    - eppy
        - *.py
        - geometry
            - *.py
            

There are some changes to the `docs` folder too, that are not relevant to what you are working on

I am using https://github.com/cookiecutter/cookiecutter to make development easier. You will have to to run `pip install -r requirements_dev.txt` again to get the full functionality

Once you do the pip install, type `make` at the terminal and hit enter. You will get::

     clean                remove all build, test, coverage and Python artifacts
     clean-build          remove build artifacts
     clean-pyc            remove Python file artifacts
     clean-test           remove test and coverage artifacts
     lint                 check style with flake8
     test                 run tests quickly with the default Python
     test-all             run tests on every Python version with tox
     coverage             check code coverage quickly with the default Python
     docs                 generate Sphinx HTML documentation, including API docs
     servedocs            compile the docs watching for changes
     release              package and upload a release
     dist                 builds source and wheel package
     install              install the package to the active Python's site-packages
     
typing `make test` to run the tests.
You can also play with other commands
I find it most useful when doing new releases - updating the version number and releasing to pypi.org

None of this impacts what you are doing now, except for the location of the test files

**Comment by airallergy** [comment]
I do have noticed those relevant new commits, but thx for such detailed clarification.

**Comment by airallergy** [comment]
Another thing occurs to me that currently only the detailed type of surface objects are accounted, other rectangular ones are not, like `Wall:Exterior`. These have their own `Azimuth Angle` field, and getting either their `azimuth` or `true_azimuth` seems a bit different process. I will look into it to see if there is a compatible and elegant way of implementation at some point, but won't be too soon. I have never seen anyone using these objects, so it might not be an urgent issue to address, I might be totally biased though. Feel free to share any thoughts on this.

Apart from this, the `true_azimuth` issue should have been fully addressed according to the input & output document.

**Comment by santoshphilip** [comment]
Lets hold off on the `Wall:Exterior` for now.
Since you opened this issue, you get to close it if the result is satisfactory.
