### ISSUE TITLE
simplify test_true_azimuth() in test_function_helpers.py

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#294]
**Problem:** test_true_azimuth is more complicated than it needs to be
**Solution:** simplify and parametrize the test using @pytest.mark.parametrize 

@airallergy, I opened another issue to make some explanations.
Opening an issue and modifying was easier than explaining using comments in a discussion

I have made two changes in response to this issue

### First change

unit tests have more than one use.
1. actually test the function
2. act as an example of how the function works
    - so someone contributing code can quickly see what is going on
    - this could be you, a couple of months later

The test should be kept as simple as possible. I had to read your test a couple of times to understand how it was doing the testing. It made total sense once I understood it. Ideally it should be clear in the first reading

Do all your smart coding in the function, not in the test

I separated the exception testing into a separate test.

### Second change

I have used @pytest.mark.parametrize in the test.
The original test is still there commented out and with explanatory comments
I would like to start using @pytest.mark.parametrize in all the new test

**Comment by santoshphilip** [comment]
@airallergy, this issue is addressed in branch `i294_parametrize`.
Please check to see if it meets the intent of the tests as you wrote them.
(I made the changes pretty quickly - so it needs a review)

If it looks OK, let me know and I'll merge into the `develop` branch

**Comment by airallergy** [comment]
@santoshphilip, that makes a lot of sense about the idea of unit tests, thanks for the detailed explanation.

I have not seen these changes in `i294_parametrize`, are they still in progress?

**Comment by santoshphilip** [comment]
`i294_parametrize` should be there now

**Comment by santoshphilip** [comment]
hold on ... I forgot to commit

**Comment by santoshphilip** [comment]
OK ... I have pushed it to GitHub. 
give it a few minutes for the automated testing (Travis) to run

**Comment by airallergy** [comment]
All look good to me
