### ISSUE TITLE
removeidfobject removes every other object in a for loop

### ISSUE THREAD

**Issue by mwilsoncea** [santoshphilip/eppy#295]
I have an idf file with several of the same object, say Schedule:Year or FenestrationSurface:Detailed and I want to remove them all. So I use the code:
`fenestrations = idf1.idfobjects['FenestrationSurface:Detailed']
syears = idf1.idfobjects['Schedule:Year']

for f in fenestrations:
    print('removing ' +f.Name)
    idf1.removeidfobject(f)
for s in syears:
    print('removing ' +s.Name)
    idf1.removeidfobject(s)`

Which removes every other FenestrationSurface:Detailed and Schedule:Year. Sample code and idf file to reproduce are attached.
[issue.zip](https://github.com/santoshphilip/eppy/files/4992757/issue.zip)

**Comment by santoshphilip** [comment]
Some quick comments

You are trying go through a loop while removing items from it. This is inherently problematic
Let me illustrate with a simple python loop.

    l = [1,2,3,4,5]
    print(l)
    for i in l:
        l.remove(i)
    print(l)

will print out:

    [1, 2, 3, 4, 5]
    [2, 4]

As you see it does not remove all the items.
You are in a similar situation with your code.

**Comment by mwilsoncea** [comment]
Ah, I had no idea. Thank you. Apparently making a copy of the list, then iterating the copy to remove from the original works well:
`for i in list(fenestrations):
    print('removing ' +i.Name)
    idf1.removeidfobject(i)`
