### ISSUE TITLE
difference between eppy and EnergyPlus Python API 0.1 

### ISSUE THREAD

**Issue by Lantonshen** [santoshphilip/eppy#299]
I have used eppy for 6 months. And it provided me great helps for my research and still.  Not long time ago, the new version of EnergyPlus issued with Python API 0.1. What do you guys think about it? Up till now, I did not touch it yet. Can anyone compare the differences between them? What can we do for eppy in the future? 
Yang

**Comment by santoshphilip** [comment]
Can you close this if it is done

**Comment by Lantonshen** [comment]
sure.
