### ISSUE TITLE
when I ran eppy, eplusout.csv is missing, but HTML is there. [No such file or directory: 'C:/Users/shenyang1991/annual dynamic simpleglazing/parameter simulation/eplusout.csv']

### ISSUE THREAD

**Issue by Lantonshen** [santoshphilip/eppy#301]
1. I ran the same IDF by E+ Launch, it can have csv file. 
2. The IDF outputs include two parts, one is Output:variables; the other is Output:Table:monthly and Output:Table:yearly. When I did through E+ Launch. I can get both. (I set column separator of  table as HTML)
3. I also tried expidf as the input file. It also had the same problem.
4. Should I upgrade eppy?

Thanks

**Comment by Lantonshen** [comment]
![Capture](https://user-images.githubusercontent.com/49128765/91399591-d7b91b80-e803-11ea-9178-58bcd31a4b3e.PNG)

**Comment by santoshphilip** [comment]
similar issue in #296 
See proposed solution. there is a chance it may apply.

**Comment by santoshphilip** [comment]
any luck with this ?
I think it happens when the version number in the IDF and IDD don't match. (but ia ma not sure)
Can you send me the code snippet from IDD and IDF

**Comment by Lantonshen** [comment]
Thanks for taking care the questions. IDF and IDD are the same version. I always run my codes in the local disk. When I move it to DropBox, it had this problem. It is strange. So I moved it back. And now it can work. 
Thanks.

**Comment by santoshphilip** [comment]
Do you want to close this

**Comment by Lantonshen** [comment]
sure.
