### ISSUE TITLE
eppy does not produce eplusout.csv

### ISSUE THREAD

**Issue by yahyasheikhnejad** [santoshphilip/eppy#307]
I am using EP 9.1, Python 3.6.4., eppy (0.5.46).
I have the Output:Variable objects in my IDF file, the eplusout.eso file is generated well and contains all the predefined variables;
The file of "eplusout.eso" is attached:
[eplusout.zip](https://github.com/santoshphilip/eppy/files/5234993/eplusout.zip)

I used the following line to run IDF file: (attached the IDF file)
[IDF file.txt](https://github.com/santoshphilip/eppy/files/5234950/IDF.file.txt)

IDF_file_name="IDF file.idf";	
EPW_file_name="USA_VA_Sterling-Washington.Dulles.epw";
Output_Var_Dir='C:/Yahya/EP/YahyaModel2/FinalFormat'
iddfile = "Energy+.idd";	
IDF.setiddname(iddfile);
idf = IDF(IDF_file_name, EPW_file_name);
idf.run(expandobjects=True, output_directory=Output_Var_Dir, readvars=True, output_suffix="L")

I received these messages as well:
Writing tabular output file results using comma format.
Writing tabular output file results using tab format.
Writing tabular output file results using text format.
Writing tabular output file results using HTML format.
Writing tabular output file results using XML format.
Writing final SQL reports
ReadVarsESO program starting.
ReadVars Run Time=00hr 00min 0.05sec
ReadVarsESO program completed successfully.
ReadVarsESO program starting.
ReadVars Run Time=00hr 00min 0.03sec
ReadVarsESO program completed successfully.
EnergyPlus Run Time=00hr 00min 1.30sec
EnergyPlus Completed Successfully.
file=open("eplusout.csv", newline="")
FileNotFoundError: [Errno 2] No such file or directory: 'eplusout.csv'

except 'eplusout.csv' all "eplusout" files are well generated...!!
[all eplusout files.zip](https://github.com/santoshphilip/eppy/files/5235066/all.eplusout.files.zip)

![Capture](https://user-images.githubusercontent.com/36997932/93393670-dc08af80-f86a-11ea-8968-db39461e0be5.JPG)

Also, I checked out the "eplusout.err" as well and there is nothing important there! (eplusout.err file is attached)
[eplusout.err.txt](https://github.com/santoshphilip/eppy/files/5234942/eplusout.err.txt)

to me, it is very weird!
would you please do me favor and let me know how could I overcome this problem?
I will be available for providing more information and data.

**Comment by santoshphilip** [comment]
I am working on this issue and on #306 
Let us see what we find out

**Comment by santoshphilip** [comment]
I may have fixed #306

**Comment by santoshphilip** [comment]
I am little mystified why you are not getting the csv file

I ran the following code (your code modified to run on my machine)

    """fixing the issue #307"""

    import eppy
    from eppy import modeleditor
    from eppy.modeleditor import IDF


    IDF_file_name="./store/sample.idf" # this is your input file with no changes
    EPW_file_name='/Applications/EnergyPlus-8-5-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw'
    Output_Var_Dir='./out_folder'
    iddfile = "/Applications/EnergyPlus-9-1-0/Energy+.idd"
    IDF.setiddname(iddfile);
    idf = IDF(IDF_file_name, EPW_file_name);
    idf.run(expandobjects=True, output_directory=Output_Var_Dir, readvars=True, output_suffix="L")

It produced the following output files:

    eplusmtr.csv
    eplusout.audit
    eplusout.bnd
    eplusout.csv
    eplusout.dxf
    eplusout.eio
    eplusout.end
    eplusout.err
    eplusout.eso
    eplusout.expidf
    eplusout.mdd
    eplusout.mtd
    eplusout.mtr
    eplusout.rdd
    eplusout.rvaudit
    eplusout.shd
    eplustbl.csv
    eplustbl.htm
    eplustbl.tab
    eplustbl.txt
    eplustbl.xml
    epluszsz.csv
    sqlite.err

I am getting the `eplusout.csv`  file. I opened it and it looked good.
I don't know why you are not getting it.
Any ideas ?

I did this test on a mac. I need to get access to a windows machine to see if it works there

**Comment by yahyasheikhnejad** [comment]
Dear @santoshphilip 
Long story short, by many try and errors, I have found that for running IDF file, I must add "expandobjects=True" within the command line of idf.run(). then I noticed that the changes that I made in IDF file cannot applied on IDF file (or changes in IDF file are not saved in IDF file) and consequently running EP via eppy results in the same results. Then again by try and error and also by reviewing "eplusout.err", I noticed that adding "expandobjects=True" will generate another file: "eplusout.expidf". Again, by many trials and errors, I found that as long as this file is in that directory from the previous run, no changes will be applied to the IDF file. hence, before running the IDF file I added this line:
`if (os.path.isfile("eplusout.expidf")==True): os.remove("eplusout.expidf")`
finally, I solved my problem in this way!! (it seems ridiculous! I know!)
I just guessed that maybe this time also there is a similar problem that can be solved similarly...!
I deleted all generated files by EP via eppy, and run the code again, and surprisingly I got no error this time and "eplusout.csv" was generated without any problem. 
I must be enough wise to just cut those files and paste it elsewhere to check out which file is responsible for this mess, but unfortunately I wasn't and I deleted them!
Those try and errors take a huge amount of time from me, and somehow, honestly they killed me...!
Dear @santoshphilip , I believe "eppy" required to be revised such that the existence of any file cannot interrupt it and avoid such unreasonable stupid errors. I must express my deep appreciation for your responsibility as well as your help and support.

**Comment by santoshphilip** [comment]
I agree about making an update to eppy, although I am not fully understanding what you say in your comment.

If you can articulate it with another example, I'll understand how to update eppy to fix this problem.
One thing I noticed is that
- You have to save the idf file in eppy before doing idf.run() -> better if eppy did it on it's own before a run. This is a potential update I can make.

other comments:
- In the latest eppy "expandobjects=True" is automatically added it needed
- I don't think the `.expidf` need to be deleted by the user. E+ will simply overwrite it. (I should test this)

Can you help me recreate the problem as you had it. Then I'll be able to see how to update eppy

thanks.

**Comment by yahyasheikhnejad** [comment]
for sure I will do my best. 
I must add that after any changes in the IDF file I saved IDF file, but the abovementioned problem was still there!
I had to delete ".expidf" so that new changes could be implemented. (I do not know why!)
I hope I could soon come back with more useful information and data...
Thanks once more for your help and support Mr. Santosh Philip.

**Comment by santoshphilip** [comment]
Problem: idf.run() will run the file on disk. What if you make changes and don't save. It will run the file before changes
Solution: idf.save_run() and idf.saveas_run() along with an unchanged idf.run()

**Comment by santoshphilip** [comment]
the problem mentioned in the previous comment does not happen.

And I am unable to recreate any of the problems @yahyasheikhnejad has mentioned here.
I should look through it carefully again and see if I am missing something.

**Comment by santoshphilip** [comment]
OK ... it has to do with the expanded file.
try to do some tests were the expidf should get changed.

**Comment by santoshphilip** [comment]
I have tried everything. I am unable to recreate this problem.
I give up.
I am going to close this issue
