### ISSUE TITLE
Changing idf objects fields in a loop

### ISSUE THREAD

**Issue by fracarl** [santoshphilip/eppy#313]
Hi, I was trying to modify idf objects inside a loop in order to repeat the same function changing the name of the object field in every run of the loop. 
I would like to create a counter i that helps me repeat the compilation of different fields. I have to fill different transmittance fields of the same idf objects, and I was thinking of creating a while loop where each field is automathically filled. I have tried with this code but it cannot read the content of the text variable to find the right field in the idf object.  

    i=0
    while i<n:
    text1 = 'Transmittance_' + str(i)
    Obj_Sp = idf.idfobjects['xxxxxxxxxxxxxx'][0]
    Obj_Sp.text1 = T_i
    i+=1

Substantially, I am trying to avoid repeating for the same object n times    
 
    Obj_Sp.Transmittance_1 = T_1          
    Obj_Sp.Transmittance_2 = T_2     
    Obj_Sp.Transmittance_3 = T_3
    ... 

Thanks!

**Comment by santoshphilip** [comment]
from the tutorial


    building = idf1.idfobjects['BUILDING'][0]
    print(building.Name)
    
    # you can do the same by
    print(building['Name'])
    

builidng is a dictionary.
Name is key in the dictionary

Does this help to solve your problem

**Comment by fracarl** [comment]
Yes you're right thank you very much!
