### ISSUE TITLE
Idf.save() is not working correctly in a loop

### ISSUE THREAD

**Issue by fracarl** [santoshphilip/eppy#315]
Good morning, 
I am trying to create a loop to change some fields of the idf but I am facing few problems. In particular, the same code runs correctly if I use it alone a couple of times in a dedicated cell but if I use it in a while loop it does not change the idf (but however the simulation results are correct and updated).
This is the code: 

    Tground = idf.idfobjects['Site:GroundTemperature:BuildingSurface'][0]
    Tground.January_Ground_Temperature = Jan       
    Tground.February_Ground_Temperature = Feb
    Tground.March_Ground_Temperature = Mar 
    Tground.April_Ground_Temperature = Apr
    Tground.May_Ground_Temperature = May
    Tground.June_Ground_Temperature = Jun 
    Tground.July_Ground_Temperature = Jul
    Tground.August_Ground_Temperature = Aug
    Tground.September_Ground_Temperature = Sep
    Tground.October_Ground_Temperature = Oct
    Tground.November_Ground_Temperature = Nov
    Tground.December_Ground_Temperature = Dec
    idf.save()

If I use it alone it changes the idf and opening the file in E+ I can find the updated temperature of the ground. 
If I run this in a loop, the simulation results are updated but opening the idf the temperature fields are not updated.

Do you have any solution to update the fields?

Thank you for your time.

**Comment by santoshphilip** [comment]
Can you show me the loop code.

**Comment by fracarl** [comment]
Yes of course:

    while i<10:                    

    output = pd.read_csv(os.path.join(folderpath,"Output","eplusout.csv"))
    
    bottom = output.filter(regex='BOT') 
      
    Jan = round(sum(bottom.loc[0])/len(bottom.loc[0]),2)
    Feb = round(sum(bottom.loc[1])/len(bottom.loc[1]),2)
    Mar = round(sum(bottom.loc[2])/len(bottom.loc[2]),2)
    Apr = round(sum(bottom.loc[3])/len(bottom.loc[3]),2)
    May = round(sum(bottom.loc[4])/len(bottom.loc[4]),2)
    Jun = round(sum(bottom.loc[5])/len(bottom.loc[5]),2)
    Jul = round(sum(bottom.loc[6])/len(bottom.loc[6]),2)
    Aug = round(sum(bottom.loc[7])/len(bottom.loc[7]),2)
    Sep = round(sum(bottom.loc[8])/len(bottom.loc[8]),2)
    Oct = round(sum(bottom.loc[9])/len(bottom.loc[9]),2)
    Nov = round(sum(bottom.loc[10])/len(bottom.loc[10]),2)
    Dec = round(sum(bottom.loc[11])/len(bottom.loc[11]),2)
      
    Tground = idf.idfobjects['Site:GroundTemperature:BuildingSurface'][0]
    Tground.January_Ground_Temperature = Jan-2       
    Tground.February_Ground_Temperature = Feb-2 
    Tground.March_Ground_Temperature = Mar-2 
    Tground.April_Ground_Temperature = Apr-2
    Tground.May_Ground_Temperature = May-2
    Tground.June_Ground_Temperature = Jun-2  
    Tground.July_Ground_Temperature = Jul-2
    Tground.August_Ground_Temperature = Aug-2
    Tground.September_Ground_Temperature = Sep-2 
    Tground.October_Ground_Temperature = Oct-2 
    Tground.November_Ground_Temperature = Nov-2
    Tground.December_Ground_Temperature = Dec-2  

    idf.save()
    
    i+=1
    
    shutil.rmtree(os.path.join(folderpath,"Output")) 

    idf.run(readvars=True, expandobjects=True, output_directory=os.path.join(folderpath,"Output"))
    
At the end of the loop I can see that the output files have been changed therefore the new input data have been considered in the simulation but if I open it in E+ i find the starting ground temperature and not the new ones.

**Comment by santoshphilip** [comment]
Can you run your script again and try the following as CASE1

    idf.save()
    # add this line
    idf.saveas(f'idf_savedas_{i}')
    
    
Then try this as CASE2
    
    idf.save()
    # add this line
    idf.savecopy(f'idf_copy_{i}')    
    
let me know what the inputs and outputs look like  

By the way, I am not seeing the indent within the while loop.
Your code should look like:

      while i<10:                    

          output = pd.read_csv(os.path.join(folderpath,"Output","eplusout.csv"))

          bottom = output.filter(regex='BOT') 
          # more code below
          
Why does it look like this:

    while i<10:                    

    output = pd.read_csv(os.path.join(folderpath,"Output","eplusout.csv"))

    bottom = output.filter(regex='BOT')

**Comment by santoshphilip** [comment]
There is a possibility that the save can save in the wrong place if
- you change the directory after opening the file
- save after the directory change.

I'll test this out in this issue

**Comment by santoshphilip** [comment]
The above comment is correct. idf.save will perform incorrectly if you change the directory.
I am going to fix that in this issue

**Comment by santoshphilip** [comment]
fixed issue # 315

:Problem: idf.save uses relative path. if the dir is changed, it can save in the wrong place
:Solution: use absolute path in idf.save
