### ISSUE TITLE
More "functional" model editor

### ISSUE THREAD

**Issue by souliane** [santoshphilip/eppy#318]
It would be great if the general usage could be more "functional" instead of "imperative".

For instance, instead of doing:
```
objs = idf.idfobjects["Whatever"]
idf.copyidfobject(objs[0])
objs[-1].Name = "new object name"
```
One could do:
```
new_obj = idf.copyidfobject(idf.idfobjects["Whatever"][0])
new_obj.Name = "new object name"
```
Or even:
```
new_obj = idf.idfobjects["Whatever"].get().copy()
new_obj.Name = "new object name"
```
Here I imagine a new method Idf_MSequence.get() that returns the single element or raise an exception if there's no or more than 1 element (similarly, we could have Idf_MSequence.first() and Idf_MSequence.last()) + EpBunch.copy().

**Comment by santoshphilip** [comment]
I have been staring at your comment for some time.
I am unfamiliar with functional programming (I have just started learning Haskell for a different project)

So I am not quite able to plan out how to proceed on this.
I am not very clear on how to use this.

Many of the other users of eppy would have the same reaction :-(

The real question is - Can eppy be made more powerful by including functional programming into it.

Is functional programming something you are good at. 
Would you be interested in following up on this. 
- It needs some kind of a use case (or examples) to illustrate it use
- We can flag the new functions as experimental (Meaning that the API may change)

**Comment by souliane** [comment]
Please don't bother too much about it, it was just an idea... and to be honest my experience with real functional programming is very limited.

I was just thinking that some methods could be slightly modified, for example copyidfobject() could return the created object because after creating it, I probably want to set some attribute values.

Also it is usually safer (against programming errors) to not let any method directly modify an object that is passed in the arguments... but sometimes you still want to do it, the pandas library allows for example to call DataFrame.sort() with inplace=True (which in this case is maybe more for performance purpose... anyway).

I don't know if this is true for other eppy users (and I just started with it), but for my usage I would not really need to access the IDF.idfobjects myself if there were some methods like get_object(obj_type, attribute, value), delete_object(obj_type, attribute, value), create_object(obj_type, attributes) to do the filtering in IDF.idfobjects for me.

So I am not talking about making it functional, just to hide a bit the mechanism that keeps a copy of the whole IDF in memory and provide users some higher level methods so that they don't have to deal with dict and list indexes themselves. I have wrote such methods for my personal usage but they are too specific for my personal usecase and can't be shared like that. Maybe I find some time to clean it and write some test, then I can submit a merge request.

For now if you are OK with it, let's close this ticket?

**Comment by souliane** [comment]
I just realized that I can pass attributes to initialize the object with when calling IDF.newidfobject() and that there's a method IDF.getobject() already existing. Those are typically the kind of stuff I was talking about! Sorry for having not looked in details :-p

**Comment by santoshphilip** [comment]
I take that as an indication that the documentation is lacking.
The documentation is long overdue for an update. 
I keep throwing any new functionality into https://eppy.readthedocs.io/en/latest/newfunctions.html
Not everyone looks there. Maybe I should mention it in the README and in the tutorials.

**Comment by souliane** [comment]
I missed it indeed. What about providing an auto-generated documentation as a complement to the current one?
You can for example use pdoc, it's as simple as that:

pip3 install pdoc3
pdoc --html --skip-errors eppy

And you get for free something like that: https://pdoc3.github.io/pdoc/doc/pdoc/#pdoc.Class
This way people could get a quick listing at the public methods and their signatures - which you can also read directly from the source code, but it requires more time and/or skills :-)

**Comment by santoshphilip** [comment]
sphinx does auto documentation.
I somehow broke it. Haven't got around to fixing it.
