### ISSUE TITLE
hvacbuilder.makeplantloop BadEPFieldError 

### ISSUE THREAD

**Issue by TfedUD** [santoshphilip/eppy#321]
using eppy 5.53:  
    following eppy HVAC loop tutorial:
        hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)    # BadEPFieldError as follows: # perhaps problem in chair not equipment:

`BadEPFieldError                           Traceback (most recent call last)
<ipython-input-3-7ea5dd7ab977> in <module>
      3 sloop = ['sb0', ['sb1', 'sb2', 'sb3'], 'sb4'] # supply side of the loop
      4 dloop = ['db0', ['db1', 'db2', 'db3'], 'db4'] # demand side of the loop
----> 5 hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)
      6 idf.saveas("hhh1.idf")

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\eppy\hvacbuilder.py in makeplantloop(idf, loopname, sloop, dloop, testing)
    679     sbranchs = []
    680     for bname in sbranchnames:
--> 681         branch = makepipebranch(idf, bname)
    682         sbranchs.append(branch)
    683     # -------- <testing ---------

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\eppy\hvacbuilder.py in makepipebranch(idf, bname)
    107     abranch.Component_1_Inlet_Node_Name = apipe.Inlet_Node_Name
    108     abranch.Component_1_Outlet_Node_Name = apipe.Outlet_Node_Name
--> 109     abranch.Component_1_Branch_Control_Type = "Bypass"
    110     return abranch
    111 

~\AppData\Local\Programs\Python\Python38-32\lib\site-packages\eppy\bunch_subclass.py in __setattr__(self, name, value)
    296         else:
    297             astr = "unable to find field %s" % (name,)
--> 298             raise BadEPFieldError(astr)  # TODO: could raise AttributeError
    299 
    300     def __getattr__(self, name):

BadEPFieldError: unable to find field Component_1_Branch_Control_Type`

**Comment by TfedUD** [comment]
..... setting pathnameto_eppy = 'localGitRepOfEppy' and idd to V7_0_0_036.idd in resources.. like in tutorial:  fixed issue.  Problem in chair, not equipment.

**Comment by santoshphilip** [comment]
I thought I replied to this. My reply seems to have vanished.

It works unto Energyplus version 7.0
It fails for the later versions.
This need to be fixed

Did you also open and close an issue in unmethours.com
I saw the same  question this morning, and now i can't find it.

**Comment by TfedUD** [comment]
Yeah I was having some issues; I tried to answer my own question with a
'yeah so I setup my env correctly and properly followed the tutorial and it
works now'; but answers nor comments for some reason were showing up when I
tried to 'hey guys I just wasn't paying enough attention'.

I'm a Navy aircraft mechanic, got CPHC Certified this year; and have only
been doing things in the matrix for about 1-1.5yrs.
Got my ass kicked today; was trying to setup cuda compute stuff to %path%
and then all of a sudden pip wasn't working and;.   Have been feeling the
self taughtitus recently lol.

Once I figured out how to properly setup the workspace; and used the
correct xxx.idd ect: smooth sailing. Awesome stuff. I'm still learning
python; with a relatively niche scope; I make a good few noob should have
had a v8 moments.

Thanks for reaching out! I hope to at some point start a .py package
project that's a bit of a 'use eppy but also populates the PHPP.xlsx'.
Apologise for the chaos.
-trevor

**Comment by santoshphilip** [comment]
Wow ! how did you wind up using eppy.
It is such a specific and narrow niche. Do you use EnergyPlus in your work

I am completely self taught from before there was an internet :-)
There is so much more resources now. Some pointers below , if you need them.


Good resources for python are

https://www.reddit.com/r/Python/
and
https://www.reddit.com/r/learnpython/
See the side barin https://www.reddit.com/r/Python/ for more resources.

A good thing to find an open source project you can contribute to. My coding improved significantly once I started writing open source code. It will also look good on your resume.

You can also go to Meetups - most of them are online. I attend
https://www.meetup.com/BayPIGgies/ 

Good luck

**Comment by TfedUD** [comment]
Thank you!
Rhino/Grasshopper via ladybug.tools was the into into energy plus; and as the rabbit hole goes deeper the path led to eppy.
