### ISSUE TITLE
Trouble extracting envelope summary report post-simulation

### ISSUE THREAD

**Issue by oisindoherty3** [santoshphilip/eppy#322]
Good morning,

I'm running a simulation on a terraced house idf file, which I seek to extract the U-Values for the exterior walls and windows, along with the roof and floor post-sim, as I am building period-built archetypes and wish for these values to be representative. 

which runs perfectly on v8.9.0 on both eppy and EP-Launch, however when I try to access the output tables I'm unable to use Pandas to open the csv file due to encoding errors that I can't seem to overcome, and when I use esoreader I'm unable still to access the tables. 

Pandas allows me to access the "eplusout.csv" file however it is the "eplustbl.csv" I seek. More specifically the "Glass U-Factor [W/m2-K]" column of the "Exterior Fenestration" tab of the Envelope Summary report when I open the "Tables" csv from within EP-Launch.

If anyone has any assistance on this that would be great. I'm only new to Energy Modelling so this could be an obvious fix so feel free to ask any questions for further elaboration!

Thanks again.

**Comment by oisindoherty3** [comment]
I was able to access the tables using Pandas to read the "eplustbl.htm" file, I will close this issue as result. Regards, Oisin

**Comment by santoshphilip** [comment]
@oisindoherty3 , just FYI, https://unmethours.com/questions/ is good place to post such questions too.
