### ISSUE TITLE
Error running eppy.results.fasthtml 

### ISSUE THREAD

**Issue by milagrossanz** [santoshphilip/eppy#323]
I'm trying to use the eppy.results.readhtlm since I'm working with a large E+ model, but I'm running into the following error:

```
import sys

pathnameto_eppy = 'C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy'
sys.path.append(pathnameto_eppy)
from eppy.modeleditor import IDF
iddfile = "C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0.idd"
IDF.setiddname(iddfile)


from eppy.results import fasthtml

fname = f"C:/Users/milag/Desktop/Ane/simulaciones/P0S1.0tbl.htm"
filehandle = open(fname, 'r').read()

namedtable = fasthtml.tablebyname(filehandle, "Site and Source Energy")
---------------------------------------------------------------------------

AttributeError                            Traceback (most recent call last)

<ipython-input-1-9184ba1b9628> in <module>
     13 filehandle = open(fname, 'r').read()
     14 
---> 15 namedtable = fasthtml.tablebyname(filehandle, "Site and Source Energy")
     16 

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\results\fasthtml.py in tablebyname(filehandle, header)
     97     htmlheader = f"<b>{header}</b><br><br>"
     98 
---> 99     with filehandle:
    100         for line in filehandle:
    101             line = _decodeline(line)

AttributeError: __enter__
```

The same error occurs if I try using `fasthtml.tablebyindex()` instead. 
As this is a new function, there are no reported problems related to this and I couldn't find the answer to my question.
I appreciate any help on this matter!

**Comment by santoshphilip** [comment]
change your code in the following way

    fname = f"C:/Users/milag/Desktop/Ane/simulaciones/P0S1.0tbl.htm"
    filehandle = open(fname, 'r') # removed .read()

    namedtable = fasthtml.tablebyname(filehandle, "Site and Source Energy")

remove the read()
the read is happening inside `fasthtml.tablebyname`

**Comment by milagrossanz** [comment]
thank you, @santoshphilip! it worked perfectly.

now I have a problem running the `readhtml` function, trying to read the same large htlm file. I will take this opportunity to ask this here since its in the same "results" cathegory. 

I have to use this function because I want to read tables that are named the same, but have different data for different zones. (Report: ZoneHeatingSummaryMonthly). I have used `readhtlm` before, but never with such a large file and this is the fist time this type of error occurs:

```
import sys

pathnameto_eppy = 'C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy'
sys.path.append(pathnameto_eppy)
from eppy.modeleditor import IDF
iddfile = "C:/Users/milag/PycharmProjects/pythonProject/venv/Lib/site-packages/eppy/resources/iddfiles/Energy+V8_9_0.idd"
IDF.setiddname(iddfile)

from eppy.results import fasthtml
from eppy.results import readhtml

fname = f"C:/Users/milag/Desktop/Ane/simulaciones/P0S1.0tbl.htm"
filehandle = open(fname, 'r')
html = open(fname, 'r').read()

end_uses= fasthtml.tablebyname(filehandle,"End Uses")
ltables = readhtml.lines_table(html)
---------------------------------------------------------------------------

NotSimpleTable                            Traceback (most recent call last)

<ipython-input-1-65e99224242e> in <module>
     14 
     15 end_uses= fasthtml.tablebyname(filehandle,"End Uses")
---> 16 ltables = readhtml.lines_table(html)

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\results\readhtml.py in lines_table(html_doc, tofloat)
    164             function_selector = {True: table2val_matrix, False: table2matrix}
    165             function = function_selector[tofloat]
--> 166             tabletup.append(function(element))
    167         if tabletup:
    168             linestables.append(tabletup)

c:\users\milag\pycharmprojects\pythonproject\venv\lib\site-packages\eppy\results\readhtml.py in table2val_matrix(table)
     72     Converts numbers to float"""
     73     if not is_simpletable(table):
---> 74         raise NotSimpleTable("Not able read a cell in the table as a string")
     75     rows = []
     76     for tr in table("tr"):

NotSimpleTable: Not able read a cell in the table as a string
```

I found a similar problem reported in #152, but from the answers I read I couldn't find a solution to my problem.

**Comment by santoshphilip** [comment]
I think this a bug. 
Something has changed in the table file and the function is not able to read one of the cells.

If your file is not sensitive, can you upload it.
that would be the quickest way to debug it

**Comment by milagrossanz** [comment]
of course! thanks for the help 

[html.zip](https://github.com/santoshphilip/eppy/files/5970547/html.zip)

**Comment by milagrossanz** [comment]
of course, here is the file.
thanks for the help!

[html.zip](https://github.com/santoshphilip/eppy/files/5970565/html.zip)

**Comment by santoshphilip** [comment]
I think I see where it tripped up.

You have two names in your IDF file that are turning up in the HTML file

    SAINT-GOBAIN GLASS SGG DIAMANT 6MM <DIAMANT 6MM.SGG>
    SAINT-GOBAIN GLASS SGG STADIP SILENCE CLEAR 44-1 <STADIP SILENCE CLEAR 44-1.SGG>

Part of the name looks like an HTML tag `<DIAMANT 6MM.SGG>`.
Eppy gets confused. Even my browser gets confused. My browser thinks it is:

    SAINT-GOBAIN GLASS SGG DIAMANT 6MM

See if you can rename those objects in the IDF and run the file again. Eppy should be able to read the new HTML.
Check if you have other IDF objects that have problematic names.

Tell me if this works.

**Comment by santoshphilip** [comment]
This is actually a bug in Energyplus

**Problem**

- The EnergyPlus objects can have legal names in the following format `Special glass <thickness is 3mm>`
-  Energyplus itself has no problems with such names
- This name turns up in the HTML output file.
    - In the HTML file the part name`<thickness is 3mm>` looks like an HTML tag.
    - The browser tries to make sense of it and fix it so that something can be displayed
    - This results in a mangled name in the HTML file as viewed in the browser

**Solution**

- The solution has to be implemented in EnergyPlus
- Before the name goes into the HTML file, it has to be modified in the following manner
    - `Special glass <thickness is 3mm>` should become `Special glass &lt;thickness is 3mm&gt;`
    - `&lt;` becomes `<` in the browser and `&gt;` becomes `>` in the browser

**Comment by santoshphilip** [comment]
There is now easy way to fix this name in `eppy`
I'll update eppy so that it does not crash when it runs into this issue.
eppy will mangle the offending name, just like the browser does.

A quick fix for you file will be to use names that don't have the `<` and `>` symbols

**Comment by santoshphilip** [comment]
I am going to open a new issue that describes this problem.
(since it is different from what this issue was opened for)

**Comment by santoshphilip** [comment]
I made a new release of eppy.
Your file should work with that release.

If it works, go ahead and close this issue

**Comment by milagrossanz** [comment]
thank you @santoshphilip! it works perfectly now.

**Comment by santoshphilip** [comment]
This error has been opened as an issue in NREL/EnergyPlus/issues/8542

**Comment by santoshphilip** [comment]
the issue [NREL/EnergyPlus/issues/8542](https://github.com/NREL/EnergyPlus/issues/8542) has been fixed and closed
