### ISSUE TITLE
U-factor hyphen raised issue in python

### ISSUE THREAD

**Issue by intelligent-222** [santoshphilip/eppy#327]
Hi Santoshphilip,

Hope you are doing well. I am trying to update U-factor value in my python code and because of hyphen "-" in the variable name, python raised issue which make sense. I went through your Eppy document and found that it is possible to access ufactor through eppy classes and objects. I was wondering if I can replace the following line with eppy address to solve the issue. 

I use the following code you change U factor within my notebook python code:

    Windowmaterial = idf.idfobjects['WindowMaterial:SimpleGlazingSystem'][0]
    Windowmaterial.U-Factor=1.6

Thanks for all your helps and supports.

**Comment by santoshphilip** [comment]
try 

    Windowmaterial.U_Factor=1.6

**Comment by santoshphilip** [comment]
The above comment is wrong. The following is correct

    Windowmaterial.UFactor=1.6


this is how I usually track the field names down

    import eppy
    idf = eppy.newidf('9.0.1')
    wind = idf.newidfobject("WindowMaterial:SimpleGlazingSystem")
    print(wind.fieldnames)

    # --

    wind.UFactor = 1.6
    print(wind)

prints out:

    ['key', 'Name', 'UFactor', 'Solar_Heat_Gain_Coefficient', 'Visible_Transmittance']

    WINDOWMATERIAL:SIMPLEGLAZINGSYSTEM,
        ,                         !- Name
        1.6;                      !- UFactor

**Comment by intelligent-222** [comment]
Thanks Santoshphilip.

The solution works well. Great help and support as usual. 

I will close the issue.
