### ISSUE TITLE
loopdiagram should give warning when if changes object names

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#33]
graphviz cannot make the diagrams if the object name has a colon ":" in it. This is because colons have meaning in the syntax of the dot file format that graphviz uses. 

So loopdiaggram replaces the ":" with "__" but does not give any indication that it has done so. At the least it should warn that it has changed the names in the diagram. At the best it should give a list of the names it has changed, giving old and new names.

**Comment by jamiebull1** [comment]
I think I've come across a better solution for this, and don't know why I didn't think of it before. Rather than replacing colons, we wrap every object name in double quotes. I'll have a look to see if there's an obvious place for this to happen.

See PyDot issue [#28](https://github.com/erocarrera/pydot/issues/28) and workaround.

**Comment by santoshphilip** [comment]
I hand edited the `Boiler.dot` file and put the colons (:) back in. Then put double quotes around the strings. Cursory tests seem to show that it will work.

**Comment by jamiebull1** [comment]
OK. I think the simplest way to do this is to replace `makeanode`, `makeabranch` and `makeendnode` with the following:

```python
def makeanode(name):
    name = escape_char(name, ':')
    return pydot.Node(name, shape="plaintext", label=name)
    
def makeabranch(name):
    name = escape_char(name, ':')
    return pydot.Node(name, shape="box3d", label=name)

def makeendnode(name):
    name = escape_char(name, ':')
    return pydot.Node(name, shape="doubleoctagon", label=name, 
        style="filled", fillcolor="#e4e4e4")

def escape_char(name, char):
    """escape strings which contain a specific character, char"""
    if char in name:
        return u"\"" + name + u"\""
    else:
        return name
```

For `boiler.idf` in `resources\idffiles\V8_0_1` this produces the loop diagram attached which looks correct to me.

![boiler](https://cloud.githubusercontent.com/assets/3817160/8653969/9f7caf06-2987-11e5-9c8f-6ea7e32d9b8c.png)

**Comment by santoshphilip** [comment]
Can you make a branch `i33_loopdiagram` and push this code change in it.
I'll review and merge it develop (may happen after the license change release)

**Comment by jamiebull1** [comment]
No problem. I've made the change in `loopdiagram.py` and in `ex_loopdiagram.py` too. Not sure which of those is current.

**Comment by santoshphilip** [comment]
Jamie,  I have merged this branch into develop
You have been added onto the copyright as follows

Copyright (c) 2015 Jamie Bull

Let me know if you need that updated (typos etc.)
