### ISSUE TITLE
idf.run does not restore sys.stderr properly

### ISSUE THREAD

**Issue by MaximilianAzendorf** [santoshphilip/eppy#330]
When calling 'idf.run()' while having overwritten `sys.stderr` (e.g. in the context of a test runner), `sys.stderr` gets temporarily overwritten by `run()` in `run_functions.py` and then, instead of remembering the old object and placing it back,  gets set to `sys.__stderr__`, which is not the desired behaviour and breaks e.g. the pycharm test runner.

**Comment by santoshphilip** [comment]
thanks @MaximilianAzendorf 
I'll review soon and merge soon.

**Comment by santoshphilip** [comment]
a test is failing for some obscure reason. I don't think it is your change. something else is happening
