### ISSUE TITLE
runIDFs exits without .err in Linux container, works on Windows

### ISSUE THREAD

**Issue by morronini** [santoshphilip/eppy#338]
Hi, trying to use runIDFs on a Docker container. 

The application runs in a python script on my local Windows 10 machine without error, calling EnergyPlus in the local directory. When the directory is zipped up into a Linux docker container with all the necessary dependencies, the runIDFs function is throwing an error. No .err file is generated, but variable "cmd" is the exact same between the two operations. Any ideas?

**Comment by santoshphilip** [comment]
My first guess is that is is not finding the energyplus installation. It expects the expects Energyplus to be installed in the standard location. 

Where is Energyplus installed in the Linux container?
In Linux the Standard locations `/usr/local/EnergyPlus-{version}`

**Comment by morronini** [comment]
Thanks for the response! I just copied the full install folder into the directory which was made into a container. I've changed the install_paths function to return the exact location.

Here is the error: "subprocess.CalledProcessError: Command '['/app/EnergyPlusV9-4-0/energyplus.exe', '--output-suffix', 'C', '--output-prefix', 'measure2', '--expandobjects', '--output-directory', '/app/runfolder', '--weather', '/app/weatherfolder/USA_KS_Olathe-Johnson.County.Executive.AP.724468_TMY3.epw', '/app/multi_runs/idf_2/in.idf']' returned non-zero exit status 1."

Here is the error with a wrong path: "FileNotFoundError: [Errno 2] No such file or directory: '/EnergyPlusV9-4-0/energyplus.exe': '/EnergyPlusV9-4-0/energyplus.exe'"

If you see anything there or if there is any more info I can give, please let me know.

**Comment by santoshphilip** [comment]
Can you give me your previous error before you made this change.
I want to make sure we are fixing the right problem

**Comment by santoshphilip** [comment]
can you also post your python code snippet where you call `runIDFs` functions. The code before and after the changes (if any) that you have made.

I am flying a little blind here, since I don't  dockers much. But we may still be able to debug this.

**Comment by morronini** [comment]
Here is the previous error before the change:

File "app.py", line 3398, in <module>
main(folder, input_sheet)
File "app.py", line 3337, in main
runIDFs(runs, num_CPUs)
File "/app/eppy/runner/run_functions.py", line 111, in runIDFs
pool.map(multirunner, prepared_runs)
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 266, in map
return self._map_async(func, iterable, mapstar, chunksize).get()
File "/usr/local/lib/python3.6/multiprocessing/pool.py", line 644, in get
raise self._value
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/EnergyPlus-9-4-0/energyplus': '/usr/local/EnergyPlus-9-4-0/energyplus'

Here is an example of my code:
baseidf = IDF(fname, wname)
baseidf.saveas(runfolder + 'baseline.idf')
fnames.append(runfolder + 'baseline.idf')
#more models appended to fnames
idfs = (IDF(f,wname) for f in fnames)
runs = ((idf, make_eplaunch_options(idf)) for idf in idfs)
runIDFs(runs, num_CPUs)
#then results are collected, but the docker does not make it this far

EP Launch options are made how you recommended:

def make_eplaunch_options(idf):
    """Make options for run, so that it runs like EPLaunch on Windows"""
    idfversion = idf.idfobjects['version'][0].Version_Identifier.split('.')
    idfversion.extend([0] * (3 - len(idfversion)))
    idfversionstr = '-'.join([str(item) for item in idfversion])
    fname = idf.idfname
    options = {
        'ep_version':idfversionstr, # runIDFs needs the version number
        'output_prefix':os.path.basename(fname).split('.')[0],
        'output_suffix':'C',
        'output_directory':os.path.dirname(fname),
        'readvars':False,
        'expandobjects':True
        }
    return options

Thanks again for the help!

**Comment by santoshphilip** [comment]
I may be display my ignorance of docker containers here:

- looks like you are copying a windows Energyplus binary into a Linux container
- a Windows Energyplus will not run in Linux
- you need to install energyplus in the Docker container
    - do a search to find out how to install an energyplus in a docker container

**Comment by morronini** [comment]
Thanks for that comment! And it's also possible that you're displaying my ignorance of docker containers. Than's for the help! I'll get back to you if it seems to be actually an eppy problem.

**Comment by santoshphilip** [comment]
post a message here even if you get it working. I would like to know that all is well.

You may be interested in looking at [this functionality](https://witheppy.readthedocs.io/en/latest/runandget.html) on running E+ and extracting specific results. It is still experimental, but could be useful
