### ISSUE TITLE
IDF function could not read idf file   

### ISSUE THREAD

**Issue by debrudra** [santoshphilip/eppy#340]
Hello. I am trying to open an idf file using EPPY but I am getting the error "TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'. Any help on this would be greatly appreciated

Attached is the section of the code:
import sys

pathnameto_eppy = 'C:/Users/debrudra/Pictures/EnergyPlus9-4'
sys.path.append(pathnameto_eppy)

from eppy import modeleditor
from eppy.modeleditor import IDF

basefilepath="C:/Users/debrudra/Downloads/Protytype_buildings_gas_furnace_slab_singlefamily/"
with open(basefilepath+"Prototype2006updatedSensorSchedule.idf") as f:
    with open(basefilepath+"Prototype2006updatedSensorSchedule_EPPY.idf","w") as f1:
        for line in f:
            f1.write(line)
    f1.close()
f.close()      

fname2 = basefilepath+"Prototype2006updatedSensorSchedule_EPPY.idf"

IDF.setiddname(iddfile)
idf2 = IDF(fname2)

The following is the full error code:

1 <class 'int'> None <class 'NoneType'>
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-24-fd21183afd02> in <module>
     18 
     19 IDF.setiddname(iddfile)
---> 20 idf2 = IDF(fname2)

~\anaconda3\lib\site-packages\eppy\modeleditor.py in __init__(self, idfname, epw)
    546         if idfname != None:
    547             self.idfname = idfname
--> 548             self.read()
    549         if epw != None:
    550             self.epw = epw

~\anaconda3\lib\site-packages\eppy\modeleditor.py in read(self)
    670             )
    671             raise IDDNotSetError(errortxt)
--> 672         readout = idfreader1(
    673             self.idfname, self.iddname, self, commdct=self.idd_info, block=self.block
    674         )

~\anaconda3\lib\site-packages\eppy\idfreader.py in idfreader1(fname, iddfile, theidf, conv, commdct, block)
    305     iddgaps.missingkeys_nonstandard(block, commdct, dtls, nofirstfields)
    306     # bunchdt = makebunches(data, commdct)
--> 307     bunchdt = makebunches_alter(data, commdct, theidf, block)
    308     return bunchdt, block, data, commdct, idd_index, versiontuple
    309 

~\anaconda3\lib\site-packages\eppy\idfreader.py in makebunches_alter(data, commdct, theidf, block)
    107         list1 = []
    108         for obj in objs:
--> 109             bobj = makeabunch(commdct, obj, obj_i, block=block)
    110             list1.append(bobj)
    111         bunchdt[key] = Idf_MSequence(list1, objs, theidf)

~\anaconda3\lib\site-packages\eppy\idfreader.py in makeabunch(commdct, obj, obj_i, debugidd, block)
     66         if len(obj) > len(obj_fields):
     67             n = len(obj) - len(obj_fields)
---> 68             extlst = extension_of_extensible(commdct[obj_i], block[obj_i], n)
     69             errortext = "idfobject with key '{}' & first field '{}' has {} fields while the idd for '{}' has only {} fields. Add the following fields to the object '{}' in file Energy+.idd '{};'".format(
     70                 obj[0].upper(),

~\anaconda3\lib\site-packages\eppy\idfreader.py in extension_of_extensible(objidd, objblock, n)
    330     print(n, type(n), ext, type(ext))
    331     # n = int(n / ext)
--> 332     n = n // ext
    333     print(n, type(n))
    334     lastvars = endof_extensible(ext, objblock)

TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'

**Comment by santoshphilip** [comment]
I am having a hard time reading the code, because it is not showing up as code. If you indent a code block by 4 spaces, it will show up as code. For example:

    import sys

    pathnameto_eppy = 'C:/Users/debrudra/Pictures/EnergyPlus9-4'
    sys.path.append(pathnameto_eppy)

    from eppy import modeleditor
    from eppy.modeleditor import IDF

    basefilepath="C:/Users/debrudra/Downloads/Protytype_buildings_gas_furnace_slab_singlefamily/"
    with open(basefilepath+"Prototype2006updatedSensorSchedule.idf") as f:
        with open(basefilepath+"Prototype2006updatedSensorSchedule_EPPY.idf","w") as f1:
            for line in f:

I can't make out where the indents in your code are. I am having to guess.

I have a question. In the line

    IDF.setiddname(iddfile)

Where is iddfile coming from? I am not seeing where you are setting it's value
I think the problem may be here.

**Comment by debrudra** [comment]
Thank you very much. I forgot to assign the idd file. It is working now.
