### ISSUE TITLE
Unclear how to use run() with a new IDF file

### ISSUE THREAD

**Issue by tibbe** [santoshphilip/eppy#342]
I'm trying to use `run()` in combination with creating a new file and I can't figure out the right combinations of invocations to make this work. Here's what I tried:

```python
from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = "EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/Energy+.idd"
try:
  IDF.setiddname(iddfile)
except modeleditor.IDDAlreadySetError as e:
  pass
  
idf = IDF(epw='EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/WeatherData/USA_CO_Golden-NREL.724666_TMY3.epw')
idf.new(fname='test.idf')
idf.newidfobject(
    'Building',
    Name='Simple One Zone (Wireframe DXF)',
    North_Axis=0,
    Terrain='Suburbs',
    Loads_Convergence_Tolerance_Value=0.04,
    Temperature_Convergence_Tolerance_Value=0.004,
    Solar_Distribution='MinimalShadowing',
    Maximum_Number_of_Warmup_Days=30,
    Minimum_Number_of_Warmup_Days=6)
idf.save()
idf.run(expandobjects=True)
```

This gives the output:
```
ERROR: Could not find input data file: /content/in.idf.
Type 'energyplus --help' for usage.
```

Note that I didn't name my file "in.idf"!

File structure:
```
content/
  test.idf
  EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/
    WeatherData/
      USA_CO_Golden-NREL.724666_TMY3.epw
    ...
```

**Comment by tibbe** [comment]
I also tried some other combinations, such as a `epw=` argument to run and not using `new()` and just `IDF(...)` but that led to other errors.

**Comment by santoshphilip** [comment]
try doing a `idf.save()` or `saveas()` before idf.run(), just to make sure the file is on the disk. EnergyPlus expects a file on the disk. 

Try this before we look at other possibilities.

**Comment by santoshphilip** [comment]
just as a sanity check, can you open an example file and do `idf.run()` on it.

**Comment by tibbe** [comment]
I've updated the example above to include `save` and made it completely standalone (just cut-n-paste the whole thing into a file). Same problem. `run` still assumes the name is "in.idf", even though it's "test.idf".

Reloading the file after it has been written fails too:
```python
from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = "EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/Energy+.idd"
try:
  IDF.setiddname(iddfile)
except modeleditor.IDDAlreadySetError as e:
  pass
  
idf = IDF('test.idf', 'EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/WeatherData/USA_CO_Golden-NREL.724666_TMY3.epw')
idf.run(expandobjects=True)
```

Again the generated command uses the wrong filename:
```
/content/EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/energyplus --weather /content/EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/WeatherData/USA_CO_Golden-NREL.724666_TMY3.epw --output-directory /content --idd EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/Energy+.idd --expandobjects /content/in.idf
```

**Comment by tibbe** [comment]
I'm trying to triage if there were changes between the version I'm running:
```
Successfully installed eppy-0.5.56...
```

and the current master but I can't find a tag for 0.5.56. All tags seem older. Do you know which SHA that release corresponds to?

I can now see where "in.idf" comes from. This is from `run`:

```python
self.saveas("in.idf")
```

`saveas` also has a side-effect of mutating `self.`, which doesn't seem ideal because it makes run has the side effect of changing the name for any future calls to `save` because `saveas` is defined as:

```
self.idfname = filename
self.save(filename, lineendings, encoding)
```

`run` should probably call `savecopy` instead.

**Comment by santoshphilip** [comment]
Let me try some variations of your code and see if I can get it to run.
Will give you an update

**Comment by santoshphilip** [comment]
Does it generate a *.err file?
Can you post that here.

**Comment by santoshphilip** [comment]
Energyplus runs the `in.idf` file.
eppy makes an `in.idf` file for energy plus to run

**Comment by santoshphilip** [comment]
The following worked on my machine. (I am running Minimal.idf from the example file)
Can you check if it runs on yours (use the Minimal.idf file)

    from eppy import modeleditor
    from eppy.modeleditor import IDF

    # change these path names for your machine
    iddfile = "/Applications/EnergyPlus-9-3-0/Energy+.idd"
    fname = "/Applications/EnergyPlus-9-3-0/ExampleFiles/Minimal.idf"
    epwfile = "/Applications/EnergyPlus-9-3-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw"


    IDF.setiddname(iddfile)
    idf = IDF(fname, epw=epwfile)
    idf.run()


    /Applications/EnergyPlus-9-3-0/energyplus --weather /Applications/EnergyPlus-9-3-0/WeatherData/USA_CA_San.Francisco.Intl.AP.724940_TMY3.epw --output-directory /Users/santoshphilip/Documents/coolshadow/github/eppy --idd /Applications/EnergyPlus-9-3-0/Energy+.idd /Users/santoshphilip/Documents/coolshadow/github/eppy/in.idf

    EnergyPlus Starting
    EnergyPlus, Version 9.3.0-baff08990c, YMD=2021.07.20 12:31
    Could not find platform independent libraries <prefix>
    Could not find platform dependent libraries <exec_prefix>
    Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
    Adjusting Air System Sizing
    Adjusting Standard 62.1 Ventilation Sizing
    Initializing Simulation
    Reporting Surfaces
    Beginning Primary Simulation
    Initializing New Environment Parameters
    Warming up {1}
    Starting Simulation at 12/21 for DENVER_STAPLETON ANN HTG 99.6% CONDNS DB
    Initializing New Environment Parameters
    Warming up {1}
    Starting Simulation at 07/21 for DENVER_STAPLETON ANN CLG .4% CONDNS DB=>MWB
    Writing tabular output file results using HTML format.
    Writing final SQL reports
    EnergyPlus Run Time=00hr 00min  0.39sec
    EnergyPlus Completed Successfully.

**Comment by tibbe** [comment]
I think I have tracked down the issue. My IDD path wasn't absolute so energyplus failed with:

```
ERROR: Could not find input data dictionary: /tmp/tmpo3mmt_vj/EnergyPlus-9.5.0-de239b2e5f-Linux-Ubuntu18.04-x86_64/Energy+.idd.
Type 'energyplus --help' for usage.
```

I didn't see the error because how `check_call` is used (it hides all the output from the process). I will send a pull request to improve the error output in that case. I will later send a second pull request to fix the file path issue.

**Comment by santoshphilip** [comment]
hmmm.. IDD path does not have to be absolute, it can be relative. See code in tutorial https://eppy.readthedocs.io/en/latest/Main_Tutorial.html#Quick-Start

    from eppy import modeleditor
    from eppy.modeleditor import IDF
    iddfile = "../eppy/resources/iddfiles/Energy+V7_2_0.idd"
    fname1 = "../eppy/resources/idffiles/V_7_2/smallfile.idf"

    IDF.setiddname(iddfile)
    idf1 = IDF(fname1)

Something else is going on here.
Keep me updated

**Comment by tibbe** [comment]
I'm close to figuring it out. I got side-tracked by looking into how subprocess output gets forwarded. I run in a Jupyter notebook which has stdout/stderr set up differently so I don't see normal output from stdout it seems. I'm looking into a general solution that works everywhere.

**Comment by tibbe** [comment]
Fix for the IDD path issue: https://github.com/santoshphilip/eppy/pull/343

The subprocess stdout/stderr is really try if we both want to support streaming output (i.e. the subprocess inheriting the parent process' stdout/stderr file descriptors) and IPython/Jupyter notebooks at the same time. I've opted leaving that issue alone for now but it can lead to hard to debug issues when running in IPython/Jupyter.
