### ISSUE TITLE
TypeError: make_idd_index() missing 1 required positional argument: 'debug' when working on Visual Studio Code on Anaconda.

### ISSUE THREAD

**Issue by ocampogarcia** [santoshphilip/eppy#346]
Hi there,

I am new to eppy, and I have not been able to find out what is going on when I use the IDF method from the eppy package. The code and the error are below. I would really appreciate your help as soon as possible. Thanks in advance!

Python 3.8.8
Windows 10

Code:
BN = 'MathTower'
iddfile = os.getcwd() + "/openStudio/Energy+.idd"
epwfile = os.getcwd() + "/MeasuredData/weather/weather.epw"
IDF.setiddname(iddfile)
idfFileName = './optimizedIDF/'+BN+'.idf'
idf = IDF (idfFileName, epwfile)

Error:

TypeError: make_idd_index() missing 1 required positional argument: 'debug'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-687c47c76c0a> in <module>
      7 
      8 idfFileName = './optimizedIDF/'+BN+'.idf'
----> 9 idf = IDF (idfFileName, epwfile)

~\anaconda3\lib\site-packages\eppy\modeleditor.py in __init__(self, idfname, epw)
    546         if idfname != None:
    547             self.idfname = idfname
--> 548             self.read()
    549         if epw != None:
    550             self.epw = epw

~\anaconda3\lib\site-packages\eppy\modeleditor.py in read(self)
    670             )
    671             raise IDDNotSetError(errortxt)
--> 672         readout = idfreader1(
    673             self.idfname, self.iddname, self, commdct=self.idd_info, block=self.block
    674         )

~\anaconda3\lib\site-packages\eppy\idfreader.py in idfreader1(fname, iddfile, theidf, conv, commdct, block)
    291     versiontuple = iddversiontuple(iddfile)
    292     # import pdb; pdb.set_trace()
--> 293     block, data, commdct, idd_index = readidf.readdatacommdct1(
    294         fname, iddfile=iddfile, commdct=commdct, block=block
    295     )

~\anaconda3\lib\site-packages\eppy\EPlusInterfaceFunctions\readidf.py in readdatacommdct1(idfname, iddfile, commdct, block)
     86     """read the idf file"""
     87     if not commdct:
---> 88         block, commlst, commdct, idd_index = parse_idd.extractidddata(iddfile)
     89         theidd = eplusdata.Idd(block, 2)
     90     else:

~\anaconda3\lib\site-packages\decorator.py in fun(*args, **kw)
    229             if not kwsyntax:
    230                 args, kw = fix(args, kw, sig)
--> 231             return caller(func, *(extras + args), **kw)
    232     fun.__name__ = func.__name__
    233     fun.__doc__ = func.__doc__

TypeError: make_idd_index() missing 1 required positional argument: 'debug'

**Comment by santoshphilip** [comment]
This error came up in issue #332 and in issue #336

You have an older version of the package `decorator` installed.
some of the older versions of decorator are buggy.
See if you can upgrade that package

`pip install -U decorator` will upgrade it.
(not sure how the upgrade is done in Anaconda)

**Comment by santoshphilip** [comment]
I am offline for the next 3 hours. 
Let me know if the fix works. I'll check later

**Comment by ocampogarcia** [comment]
Thank you so much for the prompt response. It worked.

**Comment by santoshphilip** [comment]
glad it got fixed. 
You should close the issue, since you opened it.

**Comment by ocampogarcia** [comment]
Worked perfectly. Thanks!
