### ISSUE TITLE
MutableSequence import will raise DeprecationWarning

### ISSUE THREAD

**Issue by souliane** [santoshphilip/eppy#361]
This won't work with newer python versions from 3.8:

https://github.com/santoshphilip/eppy/blob/2d10381bf0b8f4dbc8bee17ce10cd61f77365517/eppy/idf_msequence.py#L27

The correct way to import MutableSequence is now from collections.abc (and not from collections).

**Comment by santoshphilip** [comment]
good catch. 
I'll look into this

**Comment by santoshphilip** [comment]
Fixed

    :Problem: DeprecationWarning: Using or importing the ABCs from 'collections'
    :Solution: import from 'collections.abc'
