### ISSUE TITLE
readvars falling if you run, RunIDFs script from a bat file

### ISSUE THREAD

**Issue by TRasmus1422** [santoshphilip/eppy#375]
Hello, I have run into a problem with running my script with runIDFs. Then I start the script internally I can get the readvars to output an CSV file, but then I start the script from a bat file, will the function readvars not run. The main issue seems to be that then I run the script from a bat file is readvars dependent on a rvi file which is not created in the folder "\multi_runs\idf_0\in.rvi". Hope you guys have an idea of what to do in this case. 

I have attached a folder with a bat file, script in txt file, and 4 IDF files. The bat file path should be updated if you want to test it. 

I am not sure if this is a bug or me that can't figure it out yet. 

[Speed_01.zip](https://github.com/santoshphilip/eppy/files/7712773/Speed_01.zip)

**Comment by santoshphilip** [comment]
I'll take a look.

**Comment by santoshphilip** [comment]
The zip file is not self-contained.
It has:
- python script with main() that does not take any argument
- a bat file that sends an argument to the script

what I mean is that, I cannot easily recreate the problem

send me a zip file with
- script -> this script runs
- bat file -> the bat file calls the script, but breaks

Make it easy for me to recreate the problem (I'll change path names as needed)

**Comment by santoshphilip** [comment]
Couple of other comments

- there is a slim chance that this is a bug in eppy
- more likely, it a coding error in the script or bat file. 

In either case I should be able to find it. Will let you know (once you send me your new zip file :-)

If you think it is a coding error in your script, <[unmethours.com](https://unmethours.com/questions/)> is a better place to post. More people will see it and you may get a quicker answer

Another comment:
- pathnames in python script have a forward slash
    - `C:\\somefolder\\somefile.py` is not pythonic
    - `C:/somefolder/somefile.py` is the right way to do it. Python will figure out which Operating system you are on and do the right thing. Makes your code easier to read.

**Comment by TRasmus1422** [comment]
Thanks for all the comments, have I updated the Zip file for easier testing and I will move my question to unmethours.com and post my question where. 

Thanks for taking the time to give feedback and guidance :-)

**Comment by santoshphilip** [comment]
I am not seeing the new zip file
Did you forget to attach ?

**Comment by TRasmus1422** [comment]
The attached file is here. Two scripts one which you can run directly with no error and one script you should start via the bat file. The bat file paths still need to be updated based on where you save them. 
[eppy_error.zip](https://github.com/santoshphilip/eppy/files/7720840/eppy_error.zip)

**Comment by santoshphilip** [comment]
got it.

**Comment by santoshphilip** [comment]
Sorry, I got sidelined by an inane bug to took several days to track down.

When I worked on the shell script on my computer I got this::

	location_folder = "location/Users/santoshphilip/Documents/coolshadow/temp/Speed_01_sh1"
	print(location_folder + "/CPH/EnergySim/CPH.epw")

	output >> /CPH/EnergySim/CPH.epwphilip/Documents/coolshadow/temp/Speed_01_sh1

this did not make sense in any universe

Finally I figured out that:

- you cannot run a shell script (batch file) on a mac if the files you are using come from a windows machine (has windows line endings)
- You can run a python script with windows line endings (with arguments or no arguments)
- But you cannot run a shell script (batch file) on a mac if the line endijngs are windows


My testing is giving identical results in the batch file and the direct code.
Can you list out the filenames that the batch file should generate, but does not


I am on vacation adn will not have access to a windows machine for two weeks, So I may not get any useful results until I am back.

**Comment by TRasmus1422** [comment]
I think I have located the problem. Then comparing the options output can a difference be seen.

Running the python script directly: 
C:/EnergyPlusV8-9-0\energyplus.exe --weather C:\Python\Speed_01\CPH\EnergySim\CPH.epw 
--output-directory C:\Python\Speed_01\CPH\EnergySim\Unlimited\smallOffice__WFR15__N__MSF6014__2Layer__PXN\EnergyPlus 
--expandobjects --readvars --output-prefix smallOffice__WFR15__N__MSF6014__2Layer__PXN --output-suffix C **C:\Python\Speed_01\multi_runs\idf_3\in.idf**

Running the python script through a bat file: 
C:/EnergyPlusV8-9-0\energyplus.exe --weather C:\Python\Speed_01\CPH\EnergySim\CPH.epw 
--output-directory C:\Python\Speed_01\CPH\EnergySim\Unlimited\smallOffice__WFR15__N__MSF6014__2Layer__PXN\EnergyPlus 
--expandobjects --readvars --output-prefix smallOffice__WFR15__N__MSF6014__2Layer__PXN --output-suffix C **C:\WINDOWS\system32\multi_runs\idf_3\in.idf**

The multi_runs folder is misplaced because it refers to the cmd.exe and not the simulation folder itself. I have not yet successfully changed this but am currently looking into another way of writing the bat file.  

Thanks again for taking the time to help with my issue
