### ISSUE TITLE
Error on HVAC simple loop design tutorial

### ISSUE THREAD

**Issue by AsutoshBoro** [santoshphilip/eppy#377]
I was trying out your simple tutorial in : https://eppy.readthedocs.io/en/latest/HVAC_Tutorial.html#Building-a-Plant-loops

I get an error saying  " BadEPFieldError: unable to find field Component_1_Branch_Control_Type"

Error in for the line : hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)

The code is :
import sys
from eppy import modeleditor
from eppy.modeleditor import IDF
from eppy.modeleditor import IDF
from eppy import hvacbuilder
from io import StringIO

iddfile = "C:/eppy/resources/iddfiles/V_7_2\V9-5-0-Energy+.idd"
IDF.setiddname(iddfile)

#Defining the file, loops

idf = IDF(StringIO('')) # makes an empty idf file in memory with no file name
loopname = "p_loop"
sloop = ['sb0', ['sb1', 'sb2', 'sb3'], 'sb4'] # supply side of the loop
dloop = ['db0', ['db1', 'db2', 'db3'], 'db4'] # demand side of the loop
hvacbuilder.makeplantloop(idf, loopname, sloop, dloop)
idf.saveas("hhh1.idf")

**Comment by santoshphilip** [comment]
Both HVAC loop builder and HVAC Diagram maker are broken.
I think they broke for the later versions of E+

I have not got to fixing it. ( although it may be an easy fix.)
I am hoping someone else fixes it :-)

I am putting together a longer response to the question you raise in issue #376

**Comment by santoshphilip** [comment]
this is going to take some time to get to :-(
