### ISSUE TITLE
Extracting E+ simulation results generated with run() in python without saving files locally

### ISSUE THREAD

**Issue by FrederikSeeberg** [santoshphilip/eppy#379]
Hi, 

Not an eppy-issue, but I hope you might have inputs for the challenges I am facing using eppy and E+.

I am developing a script that can (i) transfer BIM data from Revit to an IDF file using Eppy. (ii) Simulate the file with the initiation of eppy or witheppy and (iii) read the results from the simulation and map it back into a data structure. It is intended to be a service in a web platform, meaning that the local and temporary storage of result files is not ideal. 

Is it possible to omit the process of E+ saving simulation result files locally and instead extract the results of a simulation directly from Python after running the simulation with eppy´s run() or witheppy.runner.eplaunch_run()? 

Best regards,
Frederik

**Comment by santoshphilip** [comment]
If I understand you right, you want the E+ results to be in memory and not on the disk.

from my best understanding:
- Energyplus does the simulation. (eppy just asks E+ to do the simulation)
- E+ does the simulation using text files. The input is a text file on disk. The output is a text file on disk
- there is no way to avoid the files on disk if you are doing a E+ simulation.

You may want to open an issue on unmethours.com and ask if it is possible to do an E+ simulation without writing any files to disk. There may be ways to do do this I am unaware of, although I think it is unlikely.

I have done a fair amount of web development including E+ simulations. The following is my opinion on the design of the web application:
- It is OK to read and write a file to disk in a web application. 
- In most web frameworks, you need to give full path names (absolute path) to the files.
- There are two strategies for this:
    - make do the runs in the known location. Delete the files after you are finished
    - the python module tempfile which will automatically delete the files after you are done. See https://pymotw.com/2/tempfile/index.html
- If you need input on how to do the eppy part of this, open another issue. I can point you in the right direction. This may lead to the development of eppy functions for use in the future.

**Comment by FrederikSeeberg** [comment]
Thank you very much for your very elaborate (and fast) response, @santoshphilip.  

Based on your feedback I think you got the question just right. From my work with E+, I have the same understanding as you, with regard to the input/output of  E+ simulations. I will raise a question on Unmethours - there might be a workaround. If not, I have already implemented the solution you suggested towards the end of your response, saving the files in a temporary folder and deleting all files stored in that folder after running the simulation using Eppy. I am fairly new to web developing, so I highly appreciate your inputs on this matter as well.
