### ISSUE TITLE
Error in extension_of_extensible when trying to import an IDF file created by DesignBuilder

### ISSUE THREAD

**Issue by Mifehr** [santoshphilip/eppy#413]
On Windows 10, I am trying to import an IDF file of a medium size building. The IDF was created by DesignBuilder, which uses its own IDD file. Everything worked with a small example model (two blocks, three zones), but fails with the actual model. An excerpt of my code:

```
from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = './IDDfiles/Energy+.idd'      # DesignBuilders own IDD file
idffile = 'building.idf'

IDF.setiddname(iddfile)
building = IDF(idffile)
```

The error I'm given:
```
Traceback (most recent call last):
  File "C:\Users\me\Desktop\2023-01-21 IDF Floor Plans\drawFloorPlansFromIDF.py", line 36, in <module>
    building = IDF(idffile)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\modeleditor.py", line 579, in __init__
    self.read()
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\modeleditor.py", line 712, in read
    readout = idfreader1(
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\idfreader.py", line 284, in idfreader1
    bunchdt = makebunches_alter(data, commdct, theidf, block)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\idfreader.py", line 110, in makebunches_alter
    bobj = makeabunch(commdct, obj, obj_i, block=block)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\idfreader.py", line 67, in makeabunch
    objfields = extff.increaseIDDfields(block, commdct, obj_i, key_txt, n)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\ext_field_functions.py", line 51, in increaseIDDfields
    extlst = extension_of_extensible(commdct[key_i], block[key_i], n)
  File "C:\Users\me\AppData\Roaming\Python\Python310\site-packages\eppy\ext_field_functions.py", line 29, in extension_of_extensible
    n = n // ext
TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
```
I spent a lot of time on my script that finally worked with the small example file. Help would be much appreciated. Even a quick and dirty fix. All I'm interested in my script are the building surfaces and the people schedules.

[IDF_and_IDD.zip](https://github.com/santoshphilip/eppy/files/10497568/IDF_and_IDD.zip)

**Comment by santoshphilip** [comment]
I'll take a look today.

**Comment by santoshphilip** [comment]
Looking at the error message, I suspect that you have hit a bug in eppy. Possibly coming from some update I made. Will fix quickly if I can

**Comment by santoshphilip** [comment]
Your files work fine on a Mac. Tested on the latest eppy r0.5.63
I'll test it on a windows machine later today.


What version of eppy are you using. Can you test on the latest version ?

**Comment by santoshphilip** [comment]
I just tested your files on a windows machine. 
It works fine.

Can you double check that the files you sent me fail on your machine.
Your error message is showing where the failure is apparently occurring. But I can't fix unless I can recreate the failure here

By the way, you are right. This failure will occur only with large files. Small files will not trigger this function

**Comment by Mifehr** [comment]
New day and I cannot reproduce the error myself. The example runs. All I think I changed is the file path of the IDD file. Might I have mixed it up with a different IDD file? Eppy was installed yesterday via pip install - so I think it was the latest version.

Thanks a lot for your quick response and your work in general. And apologize the work I triggered unnecessarily.

**Comment by santoshphilip** [comment]
If you run into the error again, reopen this issue.

Here is what is happening.
- The IDD defines the number of fields avaliable in a IDFobject (example: branches in a branchlist)
- A large IDF file may have more fields than defined in the IDD
- eppy will increase the number of fields in the IDD for that it can operate on the IDF file

This code was tricky to write and test. So I am a little concerned about it.
