### ISSUE TITLE
one bug with ext_field_functions.py", line 29

### ISSUE THREAD

**Issue by ymg2007** [santoshphilip/eppy#417]
![msedge_SrCvNwrAdE](https://user-images.githubusercontent.com/24608776/232314107-b0dea000-8dc8-4ab4-8dd1-a1f8136ee5d2.png)
![msedge_NVdynhucbT](https://user-images.githubusercontent.com/24608776/232314147-227f9cf3-bd58-4ee4-8c4d-ee8c425b3246.png)
Hi,guys.I am a newbee for eppy.
I used python3.7.15 and eppy 0.5.63. 
TypeError: unsupported operand type(s) for //: 'int' and 'NoneType'
Please help me debug this.

**Comment by santoshphilip** [comment]
Can you post a snippet of the code that triggered this error.
It will help to figure out what is going on

**Comment by ymg2007** [comment]
Thanks fpr your quick reply. I user streamlit to load idf file and epw file,then run it.
Here is the code:
`import streamlit as st
import plotly.graph_objs as go
from eppy.modeleditor import IDF

iddfile = "C:/EnergyPlusV22-1-0/Energy+.idd"
IDF.setiddname(iddfile)
# Upload IDF file
idf_file = st.file_uploader("Upload IDF file", type=["idf"])
#new_idf = st.write(idf_file)
# Upload EPW file
epw_file = st.file_uploader("Upload EPW file", type=["epw"])
# Save IDF file
if idf_file:
    with open("new_idf_file.idf", "wb") as f:
        f.write(idf_file.getbuffer())
# Save EPW file
if epw_file:
    with open("new_epw_file.epw", "wb") as f:
        f.write(epw_file.getbuffer())
# Load IDF file
#idf = eppy.read_idf("new_idf_file.idf")
idf = IDF('new_idf_file.idf','new_epw_file.epw')
# Simulate
idf.run()
`

**Comment by ymg2007** [comment]
Sorry, I found one bug in my code. The version of idf which I upload is 22.2, but the idd file I set is 22.1. It is different I uploaded a new idf, the code can run file.
I will close this issue.
