### ISSUE TITLE
Parse IDF from string (as opposed to path)

### ISSUE THREAD

**Issue by daren-thomas** [santoshphilip/eppy#43]
For my workflow, I'd like to be able to pass in a string containing the contents of the input file as opposed to the path to that file.

A file-like parameter with `StringIO` would work too...

**Comment by daren-thomas** [comment]
oops... it seems that actually works... this would be nice to see in the tutorial :-)

**Comment by santoshphilip** [comment]
I thought it was too advanced for the tutorial.
It does appear deep in the documentation at.
<http://pythonhosted.org//eppy/newfunctions.html#blank-idf-file>

email me at 
santosh_philip at yahoo dot com 
If you have other questions. I am also starting a eppy yahoogroup for eppy usage question.
(will be announcing that soon)
I also just got eppy working under python3. It passes all the unit tests.

I am going to go ahead and close this issue
