### ISSUE TITLE
 Issue with adding a movable solar shading

### ISSUE THREAD

**Issue by simonmarti1992** [santoshphilip/eppy#444]
Hello,

I am a DesignBuilder user, and I use eppy to facilitate and automate my energy modeling process. 
I have encountered an issue when trying to add movable solar shading to my simulation.

Specifically, when I attempt to include movable shading devices in my model using Eppy, I receive the following error 

```
iddgaps.a_missingkey_standard(commdct, key_i, key_txt, nofirstfields)
File "C:\Users\simon\micromamba\envs\oreni\lib\site-packages\eppy\iddgaps.py", line 125, in a_missingkey_standard
thefield = cmt["field"][0]
KeyError: 'field'
```
here is a print of a part of the comm object found in iddgaps.py

> Fenestration Surface 9 Name'], 'type': ['object-list'], 'object-list': ['GlazedExtSubSurfNames'], 'note': ['When Multiple Surface Control Type is set to Sequential the shades will be deployed for the referenced surface objects in order.', 'When that field is set to Group the entire list is controlled simultaneously.'], 'validobjects': {'GLAZEDDOOR', 'FENESTRATIONSURFACE:DETAILED', 'WINDOW'}}, {'field': ['Fenestration Surface 10 Name'], 'type': ['object-list'], 'object-list': ['GlazedExtSubSurfNames'], 'note': ['When Multiple Surface Control Type is set to Sequential the shades will be deployed for the referenced surface objects in order.', 'When that field is set to Group the entire list is controlled simultaneously.'], 'validobjects': {'GLAZEDDOOR', 'FENESTRATIONSURFACE:DETAILED', 'WINDOW'}}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}, {}]

Thank you for your support!
Simon

**Comment by santoshphilip** [comment]
Can you give me the version of E+ that is being used ? 

`iddgaps.a_missingkey_standard`

was a workaround for a badly structured IDD file. I need to know which E+ version is being used to track down what is going on.

I am traveling right now. It will be a few days before I get to this.

**Comment by simonmarti1992** [comment]
@santoshphilip 
As a DesignBuilder user, I am required to use EnergyPlusV9-4-0 by default.

**Comment by santoshphilip** [comment]
not a problem. 
I will test with that version.

**Comment by santoshphilip** [comment]
@simonmarti1992  Can you help me recreate the bug.

Give me some lines of code that will trigger the bug.

**Comment by santoshphilip** [comment]
thanx, I am able to recreate the problem. I'll be able to figure it out.

**Comment by santoshphilip** [comment]
OK, It is a bug in eppy. It is a really tricky bug to fix.

I am looking at temporary fix so that you can continue your work.
Then I'll go for the real fix.

More later.

**Comment by santoshphilip** [comment]
### Hot Fix

@simonmarti1992 , Here is a hot fix for the bug. Take the following steps:

- copy C:/EnergyPlusV9-4-0/Energy+.idd to C:/someotherplace/Energy_update.idd
- got to line 12498 in C:/someotherplace/Energy_update.idd
- change line
    -   N3 , \field Setpoint 2
    - to
    -   N3 , \field Setpoint two

Now run your script with some changes::

    from eppy import modeleditor
    from eppy.modeleditor import IDF
    # iddfile = r"C:/EnergyPlusV9-4-0/Energy+.idd"
    iddfile = r"C:/someotherplace/Energy_update.idd"
    fname1 = os.path.join(os.getcwd(), f"lagord_utf8.idf") #todo 
    IDF.setiddname(iddfile)
    idf1 = IDF(fname1)

It should work for now.

**Comment by santoshphilip** [comment]
Now I need to change the code so that this hot fix is not needed

**Comment by santoshphilip** [comment]
@simonmarti1992 , I have fixed this issue in the code. Now it will work without any changes to the IDD
the fix is in branch `i444_hotfix`. 
Your scripts will work with this branch. 

I am still working on the unit tests that deal with this fix. So I am going to leave this issue open until I am done. Once the tests are updated, I'll merge into the master branch and do a new release

**Comment by santoshphilip** [comment]
fixed issue #444

:**Problem**: Extensible fields not expanding automatically in IDD for WINDOWSHADINGCONTROL 
:**Solution**: fixed how Extensible fields were identified

eppy was using the presence of an integer in the extensible field to identify it as extensible. Some non-extensible fields have integers in them. Now eppy identifies the Extensible field by key-words such as begin-extensible

Need to make a release with these changes. Will close this issue once a new version of eppy is released

**Comment by santoshphilip** [comment]
hmmm ... continious testing tests are failing on github ???

**Comment by santoshphilip** [comment]
The fix has been merged into master branch

Not yet released to pypi.
PyPi is making me jump through too many hoops. 
Open an issue on setting up release to pypi
