### ISSUE TITLE
ImportError: No module named bunch

### ISSUE THREAD

**Issue by vinc85** [santoshphilip/eppy#46]
Why when I execute the code at link 
http://pythonhosted.org//eppy/Main_Tutorial.html, 
without installing eppy, I have the following error:
--------------------------------------------------
Traceback (most recent call last):
  File "C:\eppy\prova.py", line 3, in <module>
    from eppy import modeleditor
  File "C:\eppy\eppy\modeleditor.py", line 20, in <module>
    from idfreader import makebunches
  File "C:\eppy\eppy\idfreader.py", line 22, in <module>
    from bunch_subclass import EpBunch
  File "C:\eppy\eppy\bunch_subclass.py", line 25, in <module>
    from bunch import *
ImportError: No module named bunch
-------------------------------------------------------

Many thanks.

**Comment by santoshphilip** [comment]
eppy uses a number of external libraries.
bunch is one of the libraries.
If you look into the file requirements.txt, you will see the libraries needed for eppy to work

eppy needs the following to be fully functional:
- bunch>=1.0
- beautifulsoup4>=4.2.1
- numpy>=1.7.1
- pydot>1.0
- pyparsing==1.5.7
- pytest>=2.3.5

most of eppy should work with just
- bunch
- numpy

if you have pip installed:
- pip install bunch
- pip install numpy
should get you going

Later you can uninstall by 
- pip uninstall bunch
- pip uninstall numpy

**Comment by vinc85** [comment]
Many thanks ;-)
 


     Il Mercoledì 10 Giugno 2015 17:14, santoshphilip <notifications@github.com> ha scritto:
   

 eppy uses a number of external libraries.
bunch is one of the libraries.
If you look into the file requirements.txt, you will see the libraries needed for eppy to workeppy needs the following to be fully functional:   
   - bunch>=1.0
   - beautifulsoup4>=4.2.1
   - numpy>=1.7.1
   - pydot>1.0
   - pyparsing==1.5.7
   - pytest>=2.3.5
most of eppy should work with just   
   - bunch
   - numpy
if you have pip installed:   
   - pip install bunch
   - pip install numpyshould get you going
Later you can uninstall by    
   - pip uninstall bunch
   - pip uninstall numpy

**Comment by vinc85** [comment]
Dear,I have another question about eppy. If I want to integrate eppy library in a Java Web Application, how can I do it? Into which folder I enter eppy?Many thanks.
Best Regards  


     Il Mercoledì 10 Giugno 2015 19:28, santoshphilip <notifications@github.com> ha scritto:
   

 Closed #46.—

**Comment by santoshphilip** [comment]
good question.
If you were using a python framework like django or even bottle.py, it would be trivial. 
Java apps, I am less familiar with


I have started a yahoo group for eppy.
It is at:
https://groups.yahoo.com/neo/groups/eppy/info
Shall we move this discussion there ?

**Comment by vinc85** [comment]
No, I'm using Netbeans and I am developing a Java Web Application. I want to integrate eppy as I doing it in a desktop mode. Can I import in a Java Web eppy folder as a library?
Many thanks. 


     Il Lunedì 15 Giugno 2015 22:22, santoshphilip <notifications@github.com> ha scritto:
   

 good question.
If you were using a python framework like django or even bottle.py, it would be trivial. 
Java apps, I am less familiar withI have started a yahoo group for eppy.
It is at:
https://groups.yahoo.com/neo/groups/eppy/info
Shall we move this discussion there ?—
