### ISSUE TITLE
import eppy in a Java Web Application

### ISSUE THREAD

**Issue by vinc85** [santoshphilip/eppy#48]
Dear all,
I have one question about eppy. If I want to integrate eppy library in a Java Web Application, how can I do it? Into which folder I enter eppy?

Many thanks for your time.

Best Regards

**Comment by santoshphilip** [comment]
you mentioned in another thread that you are using netbeans.
I am rather unfamiliar with the java world.
Would have to hear from others who know more.

In the meantime I have posted a reply at eppy yahoo group
https://groups.yahoo.com/neo/groups/eppy/conversations/messages/3
that may be less than useful to you :-(

**Comment by santoshphilip** [comment]
Vincenzo, Let us know if this works. I would like to add this to to the documentation, so that other users know that it is possible.

**Comment by vinc85** [comment]
Yes, it works :-))))
Many thanks!
Vincenzo 


     Il Venerdì 19 Giugno 2015 8:22, santoshphilip <notifications@github.com> ha scritto:
   

 Vincenzo, Let us know if this works. I would like to add this to to the documentation, so that other users know that it is possible.—

**Comment by santoshphilip** [comment]
Did you do anything interesting with it ?
Is this some kind of a web interface you are working on ?

**Comment by vinc85** [comment]
I'm sorry, but I have this error? What is mean?Many thanks.

exception javax.servlet.ServletException: Traceback (most recent call last):
  File "C:\Users\vincenzo.molendini\Desktop\prova\build\web\modIdf.py", line 1, in <module>
    import os
  File "C:\Users\vincenzo.molendini\Desktop\prova\build\web\WEB-INF\lib\Lib\os.py", line 64, in <module>
    import ntpath as path
  File "C:\Users\vincenzo.molendini\Desktop\prova\build\web\WEB-INF\lib\Lib\ntpath.py", line 12, in <module>
    import warnings
  File "C:\Users\vincenzo.molendini\Desktop\prova\build\web\WEB-INF\lib\Lib\warnings.py", line 6, in <module>
    import linecache
SyntaxError: ("'with' will become a reserved keyword in Python 2.6", ('C:\\Users\\vincenzo.molendini\\Desktop\\prova\\build\\web\\WEB-INF\\lib\\Lib\\linecache.py', 127, 8, ''))

	org.python.util.PyServlet.createInstance(PyServlet.java:224)
	org.python.util.PyServlet.loadServlet(PyServlet.java:188)
	org.python.util.PyServlet.getServlet(PyServlet.java:178)
	org.python.util.PyServlet.service(PyServlet.java:155)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
 


     Il Venerdì 19 Giugno 2015 14:23, santoshphilip <notifications@github.com> ha scritto:
   

 Did you do anything interesting with it ?
Is this some kind of a web interface you are working on ?—

**Comment by daren-thomas** [comment]
It looks to me like the version of Python you are running is lower than
Python 2.6? Are you using Jython? What version?

**Comment by vinc85** [comment]
Isn't an error about the version of Jython and Python. I have solved removing other jar libraries in a project. I don't know why... 


     Il Venerdì 19 Giugno 2015 15:08, Daren Thomas <notifications@github.com> ha scritto:
   

 It looks to me like the version of Python you are running is lower than
Python 2.6? Are you using Jython? What version?

**Comment by santoshphilip** [comment]
apparently this is successful
