### ISSUE TITLE
Transition from GPLv3 to MIT license

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#57]
Steps for the transition

- **Task (Assignee)**

1. make a new branch `i57_license` from branch `develop` (santosh)
2. checkout `i57_license` for license transition work (santosh)
- update all the files that need the license change (jamie)
- review updates (Eric ?)
- update documentation to reflect the change (santosh & leora)
- package for release (santosh)
- release new version (santosh)
- announce new release on all mailing lists (santosh)

**Comment by santoshphilip** [comment]
Step 4 (review updates) in above comment seems redundant.
But it might be a good idea to have a second pair of eyes look over any updates.

my thinking is that we should do this for all code and documentation updates.
And get a sign off from the reviewer.

Let us try this out and see if we can come up with a workable process flow
Or abandon it if it seems too cumbersome

**Comment by santoshphilip** [comment]
made branch `i57_license ` on github

Jamie, you are good to go. Please update the files in branch `i57_license ` with the MIT license

Eric, As potential reviewer, can you research the MIT license. Are there versions in the license. Are we using the right version. Any other issues we need to be aware of ?

**Comment by jamiebull1** [comment]
Thanks, I'll get on with it then. There are [various versions](https://www.wikiwand.com/en/MIT_License#/Various_versions) of the MIT licence but I'd suggest we go with the one on [choosealicence.com](http://choosealicense.com/licenses/mit/) unless there's any reason not too.

What copyright statement should I add in the licence file - "Copyright (c) 2012 Santosh Philip" as in the majority of modules? Or something else?

**Comment by jamiebull1** [comment]
Ok, that's done and pushed. I've left any additional copyright statements in the modules and put the one in my comment above in the main licence file.

**Comment by santoshphilip** [comment]
folder `EPlusInterfaceFunctions` has files with GPLv2 license. These need to be changed

**Comment by jamiebull1** [comment]
Thanks. I've removed those too now.

**Comment by eayoungs** [comment]
A couple of things I noticed:
1. Looks like there is a duplicate branch for this issue:
  -i57_license: Santosh
  -i57_licence: Jamie
2. On Jamie's branch (i57_licence) the GPL3 header text has been removed but I don't see the MIT license in it's place, only copyright attribution to Santosh. Maybe the last change hasn't been pushed?

**Comment by eayoungs** [comment]
As far as versions of the MIT license, I'm fine with the version Jamie linked above. It looks like the same text as promote by the [OSI](http://opensource.org/about), at least [according to Wikipedia](https://en.wikipedia.org/wiki/MIT_License).

**Comment by santoshphilip** [comment]
use:
- i57_licence: Jamie

I will delete 
- i57_license: Santosh

**Comment by santoshphilip** [comment]
Should the text of the license be on each file ?
Most software with MIT license do not have it on each file.

Guidance from [GNU indicates](http://www.gnu.org/licenses/gpl-howto.en.html) that it should be on each page. This was the reason I put the license on each page, with the statement that this file is part of eppy

Regarding Copyright date.
Most files are dated 2012
Files within folder `EPlusInterfaceFunctions` are dated 2004.

The main license page will have 
Copyright 2004, 2012 Santosh Philip

As additional authors start to contribute to eppy, their names will be added to the copyright list.

**Comment by jamiebull1** [comment]
Ok, I've changed the main copyright line to say "Copyright (c) 2004, 2012 Santosh Philip, Tuan Tran" (as Tuan Tran is listed as the author on various modules in the geometry package).

**Comment by santoshphilip** [comment]
"Copyright (c) 2004, 2012 Santosh Philip, Tuan Tran"
is correct for now

When Eric's non-numpy code and your logging code gets into the new releases, we can add updated dates and names.

**Comment by santoshphilip** [comment]
- Eppy uses a lot of code from [EPlusInterface](https://github.com/santoshphilip/EPlusInterface_original) a software I wrote in 2004.
- Eppy uses the following code from EPlusInterface with only minor changes.
    - All the data structure for `idd` and `idf` files
    - idd parser and reader
    - idf parser and reader
- EPlusInterface was released under GPLv2
- I am the only author of EPlusInterface
- I will release a version of EPlusInterface under MIT license
- this will keep the licensing trail clean

**Comment by santoshphilip** [comment]
license on [EPlusInterface](https://github.com/santoshphilip/EPlusInterface_original) has been changed from GPLv2 to MIT license in release version 0.3

**Comment by santoshphilip** [comment]
Added a reference to MIT license in all the *.py files

**Comment by santoshphilip** [comment]
made the release as version 0.5
pip install eppy 
will install version 0.5

If everything looks good, I will close this issue

**Comment by jamiebull1** [comment]
Well the tests for parts I'm using are passing in my app so it looks good to me.

**Comment by santoshphilip** [comment]
Everything looks good and I have not had any complaints so far. 
So I am closing this issue
