### ISSUE TITLE
Object is not pickable in Eppy

### ISSUE THREAD

**Issue by nancynanxiaodan** [santoshphilip/eppy#67]
Dear guys,
I am new to eppy and github as well. May I report some issues I have when I tried with eppy tutorial.

From the tutorial at very beginning to explore the objective of MATERIAL in construction.idf. I followed the tutorial and entered the following code, however, I didnt get the same result as indicated in the tutorial,

from eppy import modeleditor
from eppy.modeleditor import IDF

iddfile = "../eppy/resources/iddfiles/Energy+V7_2_0.idd"
try:
    IDF.setiddname(iddfile)
except modeleditor.IDDAlreadySetError as e:
    pass

fname1 = "../eppy/resources/idffiles/V_7_2/constructions.idf"
idf1 = IDF(fname1)

materials = idf1.idfobjects["MATERIAL"]
print materials

firstmaterial = materials[0]
secondmaterial = materials[1]
print firstmaterial

except 'print firstmaterial' function, others are fine so far. I could print the whole 'MATERIAL' object. However, when I tried to print the sub-object, such as the first material, it will give an error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\bunch\__init__.py", line 384, in toYAML
    return yaml.safe_dump(self, **opts)
  File "C:\Python27\lib\site-packages\yaml\__init__.py", line 218, in safe_dump
    return dump_all([data], stream, Dumper=SafeDumper, **kwds)
  File "C:\Python27\lib\site-packages\yaml\__init__.py", line 190, in dump_all
    dumper.represent(data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 28, in represent
    node = self.represent_data(data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 61, in represent_data
    node = self.yaml_multi_representers[data_type](self, data)
  File "C:\Python27\lib\site-packages\bunch\__init__.py", line 342, in to_yaml_safe
    return dumper.represent_dict(data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 57, in represent_data
    node = self.yaml_representers[data_types[0]](self, data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 223, in represent_dict
    return self.represent_mapping(u'tag:yaml.org,2002:map', data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 123, in represent_mapping
    node_value = self.represent_data(item_value)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 67, in represent_data
    node = self.yaml_representers[None](self, data)
  File "C:\Python27\lib\site-packages\yaml\representer.py", line 247, in represent_undefined
    raise RepresenterError("cannot represent an object: %s" % data)
yaml.representer.RepresenterError: cannot represent an object: <eppy.bunch_subclass.CheckRange object at 0x0D1A2B30>

And when i would like to see the firstmaterial this variable from the 'Variable Explorer' it threw an error saying: 'Unable to retrieve date' Object firstmaterial is not pickable. 

I followed the exactly step from the tutorial, but I couldnt get the results I expected. Is there anything I did wrong. Please, may I ask some suggestions?

Thanks
Nancy

**Comment by santoshphilip** [comment]
I am looking into this.

**Comment by santoshphilip** [comment]
I am not able to recreate this error.
(I am on a mac)
Anyone have any ideas ?

Nancy,
Can you describe the programing environment you are in.
How are you running this. 
- what computer are you on
- what operating system

Are you in any of the following
- ipython notebook ?
- ipython in terminal ?
- python shell ?
- using idle ?
- are you running your script saying `python my script.py`

If none of the above makes any sense to you, simply describe in your words how you are going about working thru the tutorial. The code you are typing looks good. I am really interested in everything else

**Comment by santoshphilip** [comment]
More questions:
- did you install eppy using `pip install eppy` ?
- are you running virtualenv ? (debugging this would be easier with virtualenv)

**Comment by nancynanxiaodan** [comment]
Thank you very much for your kind help here.
For your question:
     I download Python(x,y) and using Spider2. And I am not using MAC which I tried but Python is not working properly, so my codes are running on windows 7. 
     And I think I installed eppy by using pip install eppy, and I am not running virtualenv.

Thank you again!

**Comment by santoshphilip** [comment]
I will try to recreate your environment in windows 7 and see what I can track down. The error you are running into is unusual. I have not seen it before. 
It is coming from an external library called `bunch`, that eppy uses. I suspect there is some clash with Python(x,y)/Spider2 and bunch.

If you have run into this error, others may run into it too. It is important we resolve it.

**Comment by nancynanxiaodan** [comment]
Thanks very much for your help. I used my laptop and PC to try, however, I
got the error. For both time that I used  Python(x,y)/Spider2 to execute
the codes.

Thanks again.

**Comment by nancynanxiaodan** [comment]
Thanks very much for your help. I used my laptop and PC to try, however, I got the error. For both time that I used  Python(x,y)/Spider2 to execute the codes.

Thanks again.

**Comment by santoshphilip** [comment]
Would you get the error if you are not using Python(x,y)/Spider2, but using a standard Python install from Python.org?

**Comment by nancynanxiaodan** [comment]
I will try tonight!

**Comment by santoshphilip** [comment]
OK ... I am able to recreate the problem with  Python(x,y)/Spider2
Now to debug this.

**Comment by santoshphilip** [comment]
This bug has been fixed
the errors occurs only when `yaml` is installed
python(x,y) environment installs`yaml` by default

I have updated the code so that the error does not occur even when yaml is installed
This code change is now in the `develop` branch

Nancy,
You will have to use the code in the `develop` branch. Google to see how get the code from any branch in github. 

I'll close this issue once Nancy gets it working under python(x,y)

**Comment by nancynanxiaodan** [comment]
Thanks very much! I will get the code from the develop branch and try to
run it!

**Comment by nancynanxiaodan** [comment]
Thank you very much! It is working on my Spider 2 now with Python(x,y)

Thanks again.
Nancy

**Comment by santoshphilip** [comment]
That is great. I'll close this issue.
Thank you for finding this problem. I would not have run into it on my own.
It was a three line fix, but took a while to track it down and figure out the fix

**Comment by andreabotti** [comment]
Hi Philip,
apologies for commenting after the issue has already been closed, but I came across the same error and I am struggling to understand how to get the amended code in the develop branch.
Thanks

**Comment by santoshphilip** [comment]
Andrea,    This bug was fixed. It is in the develop branch. It has not yet been merged into the master branch.
You will have to pull the develop branch.See if you can do it on your own.If you are not able to, I can help you.
Santosh

**Comment by santoshphilip** [comment]
This has been fixed in develop branch.
I'll merge it into master release it

**Comment by santoshphilip** [comment]
develop branch has been merged into master.
This has been released as version 0.5.2

**Comment by santoshphilip** [comment]
@andreabotti Can you confirm that this is working in your environment.
If it is I can close this issue

**Comment by jamiebull1** [comment]
I think we can safely close this. We can always reopen if @andreabotti still has an issue.
