### ISSUE TITLE
tinynumpy not working with python3

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#69]
Eric,
    As we discussed yesterday. The updated file attached below will fix python3 problem with tinynumpy. Please release a new version of tinynumpy at pypi.

I have tested this only with eppy. Although I think there should not be any other problems.

I have attached the tinynympy.py file as tinynumpy.txt (github is not accepting .py files). So change the extension before you use it.
[tinynumpy.txt](https://github.com/santoshphilip/eppy/files/81922/tinynumpy.txt)

**Comment by eayoungs** [comment]
Santosh,
    I've made the changes to tinynumpy required for compatibility under Python 3. They've been tested under both Python 2 & 3. Changes are committed to the master branch on Github. Changes are available on PyPI under a new version number (1.2.1). The new version (tinynumpy-1.2.1) installs by default (pip install tinynumpy). All tests pass.
    I've tested eppy with the new install of tinynumpy (without numpy installed) under Python 2 & 3. All tests pass. The requirements.txt file has been updated to reflect the new version of tinynumpy and this changes has been pushed to eayoungs branch of eppy on Github.

Let me know if I missed anything!

Cheers

**Comment by santoshphilip** [comment]
Thanks Eric,
I'll confirm the tests and if all looks good, I'll merge this branch into develop

**Comment by santoshphilip** [comment]
Yup ! tested and it works on both python2 and python3.
Closing this issue
