### ISSUE TITLE
AttributeError with Prototype Building Model IDFs

### ISSUE THREAD

**Issue by MatthewSteen** [santoshphilip/eppy#79]
I'm following the tutorial with a [DOE PBM](https://www.energycodes.gov/commercial-prototype-building-models) and getting the following error, which doesn't happen with a simple IDF of just a few objects.

    In [10]:    idf1 = IDF(fname1)
    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-10-0079c40d1fdc> in <module>()
    ----> 1 idf1 = IDF(fname1)

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in __init__(self, idfname)
        660     """subclass of IDF3. Uses functions of IDF1, IDF2, IDF3"""
        661     def __init__(self, idfname=None):
    --> 662         super(IDF4, self).__init__(idfname)
        663     def save(self, filename=None, lineendings='default'):
        664         """lineendings = ['default', 'windows', 'unix' ]"""

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in __init__(self, idfname)
        623     """
        624     def __init__(self, idfname=None):
    --> 625         super(IDF3, self).__init__(idfname)
        626     def initread(self, idfname):
        627         """use the latest iddfile and read file fname

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in __init__(self, idfname)
        568     """
        569     def __init__(self, idfname=None):
    --> 570         super(IDF2, self).__init__(idfname)
        571         self.outputtype = "standard" # standard,
        572                                     # nocomment,

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in __init__(self, idfname)
        493     """
        494     def __init__(self, idfname=None):
    --> 495         super(IDF1, self).__init__(idfname)
        496     def newidfobject(self, key, aname='', **kwargs):
        497     # def newidfobject(self, key, *args, **kwargs):

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in __init__(self, idfname)
        446         if idfname != None:
        447             self.idfname = idfname
    --> 448             self.read()
        449     @classmethod
        450     def setiddname(cls, arg, testing=False):

    C:\Miniconda\lib\site-packages\eppy\modeleditor.pyc in read(self)
        478         readout = idfreader1(
        479             self.idfname, self.iddname,
    --> 480             commdct=self.idd_info, block=self.block)
        481         self.idfobjects, block, self.model, idd_info = readout
        482         self.__class__.setidd(idd_info, block)

    C:\Miniconda\lib\site-packages\eppy\idfreader.pyc in idfreader1(fname, iddfile, conv, commdct, block)
        157         iddfile=iddfile,
        158         commdct=commdct,
    --> 159         block=block)
        160     if conv:
        161         convertallfields(data, commdct)

    C:\Miniconda\lib\site-packages\eppy\EPlusInterfaceFunctions\readidf.pyc in readdatacommdct1(idfname, iddfile, commdct, block)
         91     else:
         92         theidd = eplusdata.Idd(block, 2)
    ---> 93     data = eplusdata.Eplusdata(theidd, idfname)
         94     return block, data, commdct

    C:\Miniconda\lib\site-packages\eppy\EPlusInterfaceFunctions\eplusdata.pyc in __init__(self, dictfile, fname)
        101         if isinstance(fname, str) and isinstance(dictfile, Idd):
        102             fnamefobject = open(fname, 'rb')
    --> 103             self.makedict(dictfile, fnamefobject)
        104         from StringIO import StringIO
        105         try:

    C:\Miniconda\lib\site-packages\eppy\EPlusInterfaceFunctions\eplusdata.pyc in makedict(self, dictfile, fnamefobject)
        187             pass
        188         fnamefobject.close()
    --> 189         nocom = removecomment(astr, '!')
        190         idfst = nocom
        191         # alist = string.split(idfst, ';')

    C:\Miniconda\lib\site-packages\eppy\EPlusInterfaceFunctions\eplusdata.pyc in removecomment(astr, cphrase)
         36 
         37     # return string.join(alist, linesep)
    ---> 38     return linesep.join(alist)
         39 
         40 

    AttributeError: 'NoneType' object has no attribute 'join'

**Comment by santoshphilip** [comment]
@MatthewSteen  I'll take a look

**Comment by santoshphilip** [comment]
@MatthewSteen Can you give me a link to the specific file on the DOE PBM page

**Comment by santoshphilip** [comment]
I think I tracked it down.
Some of the files in `DOE PMB` have mix of DOS and Unix line endings.
I think the file was edited on a windows machine and then edited on a unix machine :-(

eppy has some code written long back (2004) that is tripping on this.
I'll try to make a branch with a fix for you so that you can start using it immediately

**Comment by santoshphilip** [comment]
@MatthewSteen Download the branch `master_hotfix_2016-02-06` and use it instead of the `master' branch
I'll leave this issue open in case you further problems

I'll make a bug fix release soon and upload to pypi for pip install

**Comment by MatthewSteen** [comment]
Thanks @santoshphilip. For reference I was using the `ASHRAE90.1_ApartmentHighRise_STD2004_Albuquerque` IDF, which I had moved using `shutil`. Forgot to mention that I'm on a Windows 7 64 bit machine. My work isn't urgent so I will likely wait for the bugfix release.

**Comment by santoshphilip** [comment]
ha! by sheer chance, I happened to test that file

**Comment by santoshphilip** [comment]
bug fixed
released as version 0.5.1

do `pip install -U eppy` to upgrade

**Comment by MatthewSteen** [comment]
Confirming that this issue is fixed in 0.5.2.

**Comment by santoshphilip** [comment]
thanks. It was an easy fix. it took more time finding the problem
