### ISSUE TITLE
refactor code for class IDF and class EpBunch

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#83]
The child classes that lead to IDF and EpBunch reflect the chronological order in which the classes were developed. This makes it hard for someone reading them to make sense of it
There are two options in refactoring them. 
1. Make a single class that embodies the entire functionality OR
2. Retain the child classes, but have a logical structure within the class inheritance

Earlier discussion on this issue happens here 
https://github.com/santoshphilip/eppy/issues/62#issuecomment-178088044
and
https://github.com/santoshphilip/eppy/issues/62#issuecomment-183790728

**Comment by jamiebull1** [comment]
Those are the two options and I put a bit of thought into what would make
sense I'm terms of separation of responsibilities. In the end the structure
you have would make sense as mixins, not as layers of multiple inheritance.

The problem with having things like `IDF_file_io`, `IDF_object_handler`,
etc. as subclasses of `IDF` is that then you have to change everywhere you
refer to IDF to refer to one of those instead.

The argument against mixins is less clearcut. In favour: it might help to
have the various types of functions clearly separated and in class with
useful names. Against: it's a less clear style of programming, and they
would depend so closely on `IDF` that there is little chance they'd be used
anywhere else.

If you want to take a look at `IDF` in a single class (with documentation),
have a look in my repo. My feeling is that's the right way to go, supported
by comprehensive unit tests.

**Comment by santoshphilip** [comment]
@jamiebull1 ,
You may have convinced me to go for the single big class with all the functions and variables for IDF. I like the code in your link to single IDF class

Some thoughts:

### Single class
When you have a big class with a lot of functionality it can be intimidating to make changes to it

### Mixins
I don't like mixins unless there is an explicit need that is unavoidable. I find them a little opaque when used liberally.

I have been thinking about this and want to articulate some of my thoughts

For the lack of a better word, I am going to define a concept -> "Constuctability"

### Constructability
Ease of being able to build or construct something. 

**External Constructablity** 
Ease of building something external with the code. Right now "eppy" has good *external constructability* to build and manipulate IDF files

**Internal Constructablity**
Ease of building withing the code. Or developing the code further. For those of us who are working on the code, *internal constructability* is vital as it makes our work easier. 
I was using child classes IDF0->IDF1->IDF2 as an easy way of building things. As I make a child class, I only make the changes i am interested in and override only those functions (or make new functions, variables). Clearly this has resulted in code being hard to read :-(

One possibility develop using a child class. Once it is well tested, reffactor the code back into the single class


I am going to a python meetup tonight. I'll talk to the more exprienced developers and see if I can get some feedback on this.

**Comment by jamiebull1** [comment]
@santoshphilip 

I agree completely on mixins, and was only really mentioning them to be complete. I certainly don't see them helping much with the `IDF` class.

On the subject of being intimidated by making changes to large classes, I personally am much more intimidated by making changes to a long chain of inheritance. Mitigating that fear was my motivation for getting up to 95% test coverage of the module, and putting the CI build in place, before really getting into the refactoring.

What I'm trying to say is that I see simple design and a good workflow as making for a more approachable codebase. A good workflow could be to do as you suggested and create a child class when developing, but then fold that back into the main class, or at the very least give it a descriptive name. And if there's no suitable name then that probably means it's not a good candidate for a class!

Finally, I think `IDF` was the easy one of the two. I've had a bit of a look at `EpBunch` too and didn't get very far with it.

Enjoy the meetup, if it's not already over, and don't forget to ask for any hints and tips on CI if you get the chance.

**Comment by santoshphilip** [comment]
@jamiebull1 , I had a very good exchange at the python meetup. @digwanderlust (who is an engineer at twitter) spent a long time with me discussing the code. (Thank you @digwanderlust ) He even tweeted about it [link](https://twitter.com/digwanderlust/status/700198925198692352)

So @jamiebull1 , you were right about a number of issues:
- We should keep IDF as a single class
- Your code in [link](https://github.com/jamiebull1/eppy/blob/single_idf_class/eppy/modeleditor.py) is good. We should merge it into the develop branch. I'll open an issue on this and assign it to you.
- Using Travis is a great idea.

We also discussed a number of other issues. I'll post in more detail in the appropriate issues and link from here. We covered:
- python3 transition and deployment
- integration testing
- process flow for collaborators to work on the code (do a pull/fork OR make a branch ?)

**Comment by digwanderlust** [comment]
glad I could help out

**Comment by jamiebull1** [comment]
@santoshphilip @digwanderlust

Great to have some feedback and I'd love to hear the thoughts on integration testing and process flow.

The `IDF` code is still more or less up to date with the `develop` branch so I raise a PR against that, or if you want to start a new branch that's fine with me too. I'd like to get your suggested fixes to the `modeleditor` tests as mentioned in #81 finished first before pulling it in.

**Comment by digwanderlust** [comment]
@jamiebull1 Be happy to chat with you guys about testing if it would be helpful.  Do you guys use a slack channel or something to chat?  Not sure if the rest of your comments are directed at me or not.

**Comment by santoshphilip** [comment]
@digwanderlust I am the holdup here. 
@jamiebull1 is ready to go and I have not yet opened an issue with a description of what we discussed on testing. Will be doing so in a moment.
I don't think the comments are directed at you. When we need help from you, we will word it explicitly :-)

**Comment by jamiebull1** [comment]
@digwanderlust yep, just thanking you for the input but definitely appreciate the offer. We do have a sla

**Comment by digwanderlust** [comment]
No problem, glad to help.  Thanks for the clarification.

**Comment by santoshphilip** [comment]
@jamiebull1 can you clarify some of the acronyms you re using

What is WIP
in
`Back to WIP pending changes mentioned in #81`
from [here](https://github.com/santoshphilip/eppy/pull/82#issuecomment-186382917)

and 
PR
in
`The IDF code is still more or less up to date with the develop branch so I raise a PR against that`
from [here](https://github.com/santoshphilip/eppy/issues/83#issuecomment-186372864)

**Comment by jamiebull1** [comment]
Work in progress. It means it's not ready to merge yet, but is close enough
to be worth discussing. It's what they tag PRs (pull requests) as over at
`scikit-learn` when they have suggestions for more work needed before it
gets merged.

**Comment by jamiebull1** [comment]
@santoshphilip Given that these are two separate issues, and you'd rather have branches here than pull requests, I'll start a new branch and issue for the single IDF class and push what I've done over to this repo. I'll also start another issue for the EPBunch refactoring but I don't really have anything worth contributing on that as yet.

**Comment by digwanderlust** [comment]
I am confused.  Separate branches and pull requests are not necessarily mutually exclusive.  When I work on code I often use a separate branch and then when I am ready I create a pull request for my branch.  Branches are generally a way to organize code.  For example I will often have separate branches for bug fixes and feature work, it helps keep things logically organized.  Pull requests on the other hand are a way to notify people you have something you need them to look at and githubs mechanism of merging the request if its ready.  It is often effective to do both branches and pull requests.  Although if you didn't want to use pull requests for some reason I would still recommend some way to do a code review before merging into master.

**Comment by santoshphilip** [comment]
I suspect I may have confused @jamiebull1 too

This is coming from my misunderstanding of terminology
I had to google "pull request" and I realize my understanding of the term was incorrect.

I am going to do some experiments with my other repository with a fake contributor.
Then I can make sure I am explaining this correctly.

- I have a good sense of what I want in the workflow
- and I know what is giving me trouble in the workflow

will clarify this soon 
and will ask for feedback to make sure I am thinking straight on this.

**Comment by santoshphilip** [comment]
I am slowly understanding the terminology - especially of github.
I'll write more on this over the weekend.
(I have some deadlines coming up for Friday :-(

and I see that github has some sweet tools I have not used yet.

**Comment by santoshphilip** [comment]
This is now in branch `i83_refactor_idf_and_epbunch`
the fix in issue #99 has been merged into this branch.

This may be ready to merge into develop

**Comment by santoshphilip** [comment]
this branch has been merged into develop
