### ISSUE TITLE
Unit testing and Integration testing

### ISSUE THREAD

**Issue by santoshphilip** [santoshphilip/eppy#85]
### Unit Testing
- Unit tests should be light-weight test that can be run frequently (with any code change)
- unit tests should be Operating system agnostic. It should not care what operating system it runs on
- when testing functions that read or write files, use file handles in the test (`fhandle = StringIO.StringIO("Hello world!")`)
- Unit test should not test external dependencies.
- Consider using mock tests when you want to unit-test code that has external dependencies
### Mock tests
- This is new ground for me. So I will have a learning curve on this.
- My inclination is to do the integration tests first and then start messing with mock testing
- some links for mock testing
  - [google "python mock test"](https://www.google.com/search?client=safari&rls=en&q=python+mock+test&ie=UTF-8&oe=UTF-8)
  - [ google "mock test pytest"](https://www.google.com/search?client=safari&rls=en&q=python+mock+test+pytest&ie=UTF-8&oe=UTF-8#q=mock+test+pytest)
### Integration testing
- These are tests for external external dependencies including
  - running E+
  - locating a specific version of E+
  - IO operations
- These tests are not run as frequently as unit tests
- Integration tests will allow us to test on all operating systems that E+ runs on
- They should be run when a new version of E+ is released.
- They may need to be run when a new version of the OS is released.

The integration test can be run as `py.test ./eppy/tests/integration/integration.py`
Since the word `test` is not in `integration.py` it will not be invoked with `py.test` during unit tests

Integration tests will need a number of files to run and will generate a number of output files. The test will need `setup` and `teardown` functions. We should use pytest's conventions when doing this

**Comment by santoshphilip** [comment]
made a branch `i85_testing` for this issue.

on a unix machine
`sh integration.sh` 
will run the integration tests. It tests for read and write from the disk.
Just a start on doing integration tests.

**Comment by jamiebull1** [comment]
This is now handled by setting the environment variable `EPPY_INTEGRATION` to `TRUE` and decorating tests that should only be run as integration tests. It would nice to have set it up so that we could call `setup.py integration` and have `setuptools` automatically set the environment variable and run the tests.

**Comment by santoshphilip** [comment]
EPPY_INTEGRATION to TRUE is good for now.
Closing this issue
