### ISSUE TITLE
Refactor code for class EpBunch

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#90]
Issue for review of refactoring EpBunch to simplify it into a single class.

https://github.com/santoshphilip/eppy/tree/i90_single_epbunch

**Comment by santoshphilip** [comment]
Jamie,
     I had written some background documentation of EpBunch. Take a look and see it it makes sense. I was trying to give a high level view of how EpBunch was written.

http://pythonhosted.org/eppy/dev_docs/index.html
http://pythonhosted.org/eppy/dev_docs/epbunch.html

**Comment by jamiebull1** [comment]
Ah, that's really handy. I'd seen it before but forgot the details (and where to find it...).

The one additional thing it says to me is that we can potentially drop support for `__aliases`. I kept it in since it's tested for, but can easily remove both it.

I'm also not 100% clear on why `GetRange` and `SetRange` were in `__functions` rather than just being methods of one of the `EpBunch` classes. Is the approach I've taken going against any design intent?
