### ISSUE TITLE
bunch / munch ?

### ISSUE THREAD

**Issue by lafrech** [santoshphilip/eppy#92]
Hi.

I read bunch suffers from lack of maintenance / responsiveness (https://github.com/dsc/bunch/issues/32).

It has been forked into [munch](https://github.com/Infinidat/munch). munch releases Py2 and Py3 versions:
https://pypi.python.org/pypi/munch
https://packages.debian.org/search?keywords=munch

Are there any plans to move to munch?

This question is linked to https://github.com/santoshphilip/eppy/issues/64. I'm wondering how Eppy can be packaged for Python3 if depending on a library that ships only for Python2.

**Comment by lafrech** [comment]
I just checked the tests passed on Python 2 when replacing bunch with munch.

```
python setup.py nosetests
[...]
Ran 73 tests in 7.135s
OK
```

I don't know how to perform nosetests with Python 3 version.

If you wish, I may send a PR.

**Comment by santoshphilip** [comment]
@lafrech Thanks for letting me know about the state of `bunch`. This has been news to me.
Indeed `munch` may be the way to go.

My gut reaction is to fork `bunch` so that is still available to `eppy`
(in case `bunch` gets deleted for some reason)
I also feel comfortable maintaining an internal version `bunch` just for `eppy`

Having said that, I am okay with moving to `munch` if that is the right move.

Regarding python3 and `bunch`. 
I am pretty sure `bunch` works with python3.
in `eppy` see folder `p3`. This contains the python3 version of `eppy`. It does pass all the unit tests. And pip will install the python3 version of `bunch`

@jamiebull1 Can you also take a look at this issue. I would like your opinion.

**Comment by lafrech** [comment]
> My gut reaction is to fork bunch so that is still available to eppy
(in case bunch gets deleted for some reason)

I guess cloning it won't hurt, but I don't think it'll vanish. There are clones everywhere, anyway (Debian repo, even munch is a clone).

> I also feel comfortable maintaining an internal version bunch just for eppy

Sure, but why bother?

> Having said that, I am okay with moving to munch if that is the right move.

That's my feeling after a quick search with no prior knowledge. It's wise to double-check.

> I am pretty sure bunch works with python3
> pip will install the python3 version of bunch

I thought bunch worked with Python3 but the maintainer never cared to release a Python3 version on Pypi. But you're right, although the [page on Pypi](https://pypi.python.org/pypi/bunch/1.0.1) only lists P2, I can `pip install bunch` in a Python3 virtualenv and I get a P3 version. I'm a bit surprised.

**Comment by santoshphilip** [comment]
@lafrech Did `munch` work without any changes to eppy code.
Is this just a matter of changing `bunch` to `munch` in `requirements.txt` ?

**Comment by lafrech** [comment]
Nope. You have to modify `bunch_subclass.py`:

```
git diff
diff --git a/eppy/bunch_subclass.py b/eppy/bunch_subclass.py
index 4c0659b..2c2be45 100644
--- a/eppy/bunch_subclass.py
+++ b/eppy/bunch_subclass.py
@@ -15,7 +15,7 @@ from __future__ import unicode_literals
 
 import copy
 from eppy.EPlusInterfaceFunctions import readidf
-from bunch import Bunch
+from munch import Munch
 # import eppy.bunchhelpers
 
 class BadEPFieldError(Exception):
@@ -38,7 +38,7 @@ def extendlist(lst, i, value=''):
     else:
         lst.extend([value, ] * (i - len(lst) + 1))
 
-class EpBunch_1(Bunch):
+class EpBunch_1(Munch):
     """Has data in bunch"""
     def __init__(self, obj, objls, objidd, *args, **kwargs):
         super(EpBunch_1, self).__init__(*args, **kwargs)

```

You should also modify setup.py (`install_requires`).

**Comment by santoshphilip** [comment]
Yes, You are right.
I think I wrote my reply before the coffee got to my brain :-)

**Comment by jamiebull1** [comment]
I also didn't realise bunch wasn't maintained any more. Personally I'd be more comfortable with a maintained dependency, and if the change is really as simple as to search and replace bunch with munch in a couple of places then I think we should do that, subject to tests passing in p3.

**Comment by lafrech** [comment]
You may prefer to change just one line in `bunch_subclass.py`:

    from bunch import Bunch

into 

    from munch import Munch as Bunch

so that the rest of the code remains unchanged.

Practically, it is equivalent.

**Comment by jamiebull1** [comment]
That sounds good to me. That also saves changing the docs where we refer to bunches. Do you want to raise a PR against the `develop` branch?

**Comment by lafrech** [comment]
Sure.

What's the procedure for the PY3 tests? I got the PY2 tests to run, but don't know how to test against PY3.

**Comment by santoshphilip** [comment]
I have the instructions for this somewhere in one of the issues. I'll try to find it or make a new one.

**Comment by santoshphilip** [comment]
## to run pytest in python3

### generate the python3 file:

    cd eppy/eppy
    sh 2to3sh.sh # sometimes takes a while
    
### do the python3 tests:
switch to a python3 virtualenv

    cd eppy/p3
    py.test

**Comment by lafrech** [comment]
OK, I managed to test P3 as well. All fine.

Here's a PR: https://github.com/santoshphilip/eppy/pull/94

Note that I didn't take the time to make a full tour of all bunch forks/alternatives, but from what I gathered, munch seemed like the one to bet on.

**Comment by jamiebull1** [comment]
Closing.
