### ISSUE TITLE
Eppy and Python newbie question and comments

### ISSUE THREAD

**Issue by crollinjones** [santoshphilip/eppy#98]
Thank you Philip,
I am exploring EnergyPlus and the DOE Commercial Reference Buildings prototype models. I have been looking for a scripting tool to assist with my research. I have been reading the EnergyPlus and unmethours egroups for the past 3 years. I have been reading Ruby books to learn OpenStudio measure writing.I asked the unmethours if ruby could write measures for the EnergyPlus model. A user directed my at Eppy. Now I am reading Python documentation.

Your tutorial is excellent. The examples of Materials and Constructions is exactly what I am looking for. I want to "move" the prototype from ASHRAE to the NECB, our National Energy Code for Buildings in Canada. With Eppy, I can create scripts to set the characteristics of the ASHRAE building to the NECB equivalent building in a different city. The construction U value is a good place to start. 

I am wondering why you chose Python over using the existing ruby measure writing capabilities? I do like what I have read of Python in the past two days and I am looking forward to diving in.

**Comment by santoshphilip** [comment]
lot of the early code that went into eppy was written in 2004.
I have mentioned some of this background in the developer documentation of eppy http://pythonhosted.org/eppy/dev_docs/hist_eppy.html. 

In a sense eppy code was written before OpenStudio was written.

I hope that explains why eppy is not in Ruby.


Thank you for your comment on the tutorial. @le0ra helped in making that work. We were trying to write a tutorial that was targeted to a person who did not know python and was only a little familiar with E+

It would be good to have a function that would calculate the u-Value of a construction. If you can come up with the calculation for doing so, I can implement it in eppy. It will look something like this:

`construction.uvalue`
`construction.rvalue`

We could do it for both metric and IP units

**Comment by jamiebull1** [comment]
+1 for `uvalue` and `rvalue` - really useful additions.

**Comment by crollinjones** [comment]
RSI [m2-K/W] Value material = Thickness [m] / Conductivity [W/m-K]
RSI Value Construction = sum of material RSI Values
USI Value Construction = 1/RSI Value Construction
Heat Capacity material [kJ/m2-C] = Density [kg/m3] * Specific Heat [J/kg-K]*Thickness [m] * 0.001
Heat Capacity Construction [kJ/m2-C] = sum of material Heat Capacities

My apologies for not responding sooner.

**Comment by jamiebull1** [comment]
So onto how should these be implemented. We currently have additional functions for surfaces (azimuth, area, etc) so it would make sense to have a similar approach for these. I'm having a look at this at the moment to see how easy or hard it would be.

**Comment by jamiebull1** [comment]
So as I see it, there are a couple of issues. It's easy enough to add a `material.rvalue` function in the same way as we have `surface.azimuth`, etc. But it's not so simple to have `construction.rvalue`, since the `EPBunch` representing a construction object doesn't have a reference to the materials it's made up of, or to the parent IDF. It's easy enough to do when you have a reference to the IDF:

        construction = idf.getobject('CONSTRUCTION', 'TestConstruction')
        layers = construction.obj[2:]
        rvalue = sum(idf.getobject('MATERIAL', l).rvalue for l in layers)

I can't immediately see how to package that into a `construction.rvalue` function.

The other issue is boundary layers. What r value should we use for these? The best idea might be to have a look into EnergyPlus and see what happens in there.

**Comment by crollinjones** [comment]
The R-value of the inside and outside air films is included with some simulation programs and excluded with others. eQuest (DOE2.2) includes the  inside air film - RSI = 0.12 but excludes the outside air film when reporting the construction RSI value. The EnergyPlus envelope summary table reports the USI value with and without Film but doesn't specify if Film includes both inside and outside. If you subtract the Without from the With, it appears that EnergyPlus includes both the inside and outside air films. Inside RSI=0.12, outside RSI=0.03 - more or less.

**Comment by jamiebull1** [comment]
It's probably in the docs somewhere so I'll see if I can dig it out.

@santoshphilip any thoughts on the architecture question?

**Comment by santoshphilip** [comment]
I have done some work in branch `i102_zonesurfaces` that make it possible.
`construction.theidf` will give you full access to the idf that the construction belongs to. 

I coded this while resolving the issue #102 
It is pretty robust right now.
There are couple of things left to code, but will not impact the issue we are addressing here

**Comment by jamiebull1** [comment]
Great timing! I'll fork that branch and work in there then.

**Comment by santoshphilip** [comment]
a code snippet that shows the change:

    class EpBunch(Bunch):
        """
        Fields, values, and descriptions of fields in an EnergyPlus IDF object 
        stored in a `bunch` which is a `dict` extended to allow access to dict 
        fields as attributes as well as by keys.
    
        """
        def __init__(self, obj, objls, objidd, theidf, *args, **kwargs):
            super(EpBunch, self).__init__(*args, **kwargs)
            self.obj = obj        # field names
            self.objls = objls    # field values
            self.objidd = objidd  # field metadata (minimum, maximum, type, etc.)
            self.theidf = theidf  # pointer to the idf this epbunch belongs to
                                  # This is None if there is no idf - a standalone epbunch      
            self['__functions'] = {} # initialize the functions
            addfunctions(self)

**Comment by jamiebull1** [comment]
Closing as the outstanding issue is being handled in #104
