### ISSUE TITLE
my_surface.coords doesn't work when called on created surfaces

### ISSUE THREAD

**Issue by jamiebull1** [santoshphilip/eppy#99]
When adding a surface using `window = idf.newidfobject('FENESTRATIONSURFACE:DETAILED')` (and I assume the same applies to `BUILDINGSURFACE:DETAILED` objects too), the coordinates are not automatically available through `window.coords`.

It does work if you call `eppy.function_helpers.getcoords(window)` though.

This looks to be because `idfreader.addfunctions` is only called when first reading the IDF.

**Comment by santoshphilip** [comment]
You are right. There is a problem there.

I have hacked a quick fix in branch `i99_coords`
Found another bug in `idfreader.addfunctions` that I have fixed.
do a diff with bench `develop` to see the changes

It is not pretty, but all the tests pass.

**Comment by santoshphilip** [comment]
The way functions are added to `EpBunch` is a little expedient.
I did it the quickest way I could at that time.

It is potentially a very powerful feature of eppy.
I would like to reorganize it so that there would be a more obvious way to add more functions.

**Comment by santoshphilip** [comment]
### limitation of EPBunch function

Right now the functions can look into the EPBunch object. So it can look at the coordinates of the window and calculate the tilt or area. It cannot look outside. For instance it cannot do.

`window.getparent # to get the surface on which the window is located`

or

`surface.windows # should get a list of all the windows in that surface`

This would need a rethink of how EPBunch is structured to be able to do this

**Comment by jamiebull1** [comment]
Have you had a chance to look at my attempt at streamlining/simplifying the EPBunch part of the code [here](https://github.com/santoshphilip/eppy/pull/93)?

I think you're right, having parent/child function calls would be useful. `window.getparent` seems easy enough since it's there in the fenestration object. `surface.windows` is a little harder but it shouldn't be a problem to loop through all the fenestration objects looking for ones which have the parent as their `Building Surface Name`.

**Comment by santoshphilip** [comment]
I should go back and revisit your streamlining.
I think I need a few more hours in my days :-)

**Comment by jamiebull1** [comment]
I know that feeling. Let me know if you'd like me to bring it in line with the latest develop branch before it gets left too far behind. I see there are already conflicts.

**Comment by santoshphilip** [comment]
Can you see if branch `develop` will merge into it

**Comment by jamiebull1** [comment]
It wouldn't, but it was just a minor conflict (`Bunch` vs `Munch`).

**Comment by santoshphilip** [comment]
the code in #83 looks good.
That was a lot of work.  great job. 
I'll review it carefully and we can merge it into develop.

**Comment by santoshphilip** [comment]
resolved and merged into develop

**Comment by jamiebull1** [comment]
Hi @santoshphilip - first off, happy birthday for yesterday! And second, could we get this change merged into `master`? It's more a bugfix than a new feature, and it keeps tripping me up!

**Comment by santoshphilip** [comment]
How did you know it was my birthday ?
thank you.

I'll go ahead and merge develop into master.
Soon after I'll do a release on pypy so that pip install works

**Comment by jamiebull1** [comment]
Skype knows all! Hope you had a good one.

**Comment by santoshphilip** [comment]
Wow ! I had no idea that skype had it.
I am still a little hungover.

`develop` has been merged into `master`

**Comment by santoshphilip** [comment]
hmmm.. I am going to fudge birth date. on Skype.
It is the kind of data that can be grabbed in an identity theft.

**Comment by jamiebull1** [comment]
Probably wise.

The Python 3 build is still failing on `master` on the Travis CI server. The bugfix from a couple of days ago ought to fix it though #120

**Comment by santoshphilip** [comment]
tests are still failing.
I'll take a look tomorrow. too much happening today.

Can you take a look if you have the time ?

**Comment by santoshphilip** [comment]
for some reason module `decorator` is not getting installed (it is in the requirements.txt)

**Comment by jamiebull1** [comment]
It needs to be in `setup.py`

**Comment by jamiebull1** [comment]
I've fixed it in my branch and will raise another PR

**Comment by jamiebull1** [comment]
Resolved in #120
